/**
 * Defines country-specific map presentation and scoring configuration for
 * GeoPedia's town quizzes.
 *
 * This file is generated by:
 *
 * scripts/generate/world/generateTownCountryConfigs.ts
 *
 * Do not manually edit generated values here. Modify the generator and
 * regenerate this file instead.
 */

export type TownCountryConfig = {
  initialView: {
    center: [number, number];
    zoom: number;
  };

  maxErrorKm: number;
};

export type TownQuizInitialView = {
  center: [number, number];
  zoom: number;
};

const townCountryConfigs: Record<string, TownCountryConfig> = {
  abw: {
    initialView: {
      center: [-69.9696, 12.5249],
      zoom: 10.91,
    },
    maxErrorKm: 11,
  },
  afg: {
    initialView: {
      center: [67.6895, 34.0517],
      zoom: 5.26,
    },
    maxErrorKm: 329,
  },
  ago: {
    initialView: {
      center: [17.8656, -11.2922],
      zoom: 4.92,
    },
    maxErrorKm: 435,
  },
  aia: {
    initialView: {
      center: [-63.1773, 18.3853],
      zoom: 9.86,
    },
    maxErrorKm: 25,
  },
  ala: {
    initialView: {
      center: [20.3049, 60.1939],
      zoom: 8.51,
    },
    maxErrorKm: 26,
  },
  alb: {
    initialView: {
      center: [20.1544, 41.1633],
      zoom: 6.72,
    },
    maxErrorKm: 82,
  },
  and: {
    initialView: {
      center: [1.5858, 42.5391],
      zoom: 10.46,
    },
    maxErrorKm: 5,
  },
  are: {
    initialView: {
      center: [53.9765, 24.3597],
      zoom: 6.8,
    },
    maxErrorKm: 82,
  },
  arg: {
    initialView: {
      center: [-63.6171, -40.4323],
      zoom: 3.26,
    },
    maxErrorKm: 638,
  },
  arm: {
    initialView: {
      center: [45.0195, 40.0879],
      zoom: 7.06,
    },
    maxErrorKm: 81,
  },
  asm: {
    initialView: {
      center: [-169.4959, -14.351],
      zoom: 7.89,
    },
    maxErrorKm: 25,
  },
  ata: {
    initialView: {
      center: [-125.0572, -77.9459],
      zoom: 1,
    },
    maxErrorKm: 25,
  },
  atf: {
    initialView: {
      center: [69.5893, -49.1475],
      zoom: 7.9,
    },
    maxErrorKm: 25,
  },
  atg: {
    initialView: {
      center: [-62.0079, 17.3303],
      zoom: 8.98,
    },
    maxErrorKm: 10,
  },
  aus: {
    initialView: {
      center: [133.275, -27.7826],
      zoom: 3.42,
    },
    maxErrorKm: 804,
  },
  aut: {
    initialView: {
      center: [13.3347, 47.7108],
      zoom: 6.37,
    },
    maxErrorKm: 146,
  },
  aze: {
    initialView: {
      center: [47.7002, 40.1641],
      zoom: 6.53,
    },
    maxErrorKm: 164,
  },
  bdi: {
    initialView: {
      center: [29.9104, -3.3838],
      zoom: 7.61,
    },
    maxErrorKm: 84,
  },
  bel: {
    initialView: {
      center: [4.4482, 50.5063],
      zoom: 7.07,
    },
    maxErrorKm: 61,
  },
  ben: {
    initialView: {
      center: [2.2986, 9.3203],
      zoom: 6.07,
    },
    maxErrorKm: 166,
  },
  bes: {
    initialView: {
      center: [-65.6585, 14.8329],
      zoom: 6.26,
    },
    maxErrorKm: 818,
  },
  bfa: {
    initialView: {
      center: [-1.5662, 12.2512],
      zoom: 6.18,
    },
    maxErrorKm: 197,
  },
  bgd: {
    initialView: {
      center: [90.3323, 23.7143],
      zoom: 6.04,
    },
    maxErrorKm: 172,
  },
  bgr: {
    initialView: {
      center: [25.4743, 42.7513],
      zoom: 6.66,
    },
    maxErrorKm: 158,
  },
  bhr: {
    initialView: {
      center: [50.6002, 25.9342],
      zoom: 9.07,
    },
    maxErrorKm: 11,
  },
  bhs: {
    initialView: {
      center: [-76.0013, 23.9555],
      zoom: 6,
    },
    maxErrorKm: 197,
  },
  bih: {
    initialView: {
      center: [17.6675, 43.9375],
      zoom: 6.8,
    },
    maxErrorKm: 104,
  },
  blm: {
    initialView: {
      center: [-62.8295, 17.9056],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  blr: {
    initialView: {
      center: [27.9426, 53.768],
      zoom: 5.66,
    },
    maxErrorKm: 204,
  },
  blz: {
    initialView: {
      center: [-88.5098, 17.1898],
      zoom: 7.27,
    },
    maxErrorKm: 93,
  },
  bmu: {
    initialView: {
      center: [-64.7668, 32.3184],
      zoom: 11,
    },
    maxErrorKm: 14,
  },
  bol: {
    initialView: {
      center: [-63.5661, -16.4006],
      zoom: 4.93,
    },
    maxErrorKm: 335,
  },
  bra: {
    initialView: {
      center: [-54.406, -15.1244],
      zoom: 3.36,
    },
    maxErrorKm: 846,
  },
  brb: {
    initialView: {
      center: [-59.5406, 13.1979],
      zoom: 10.45,
    },
    maxErrorKm: 16,
  },
  brn: {
    initialView: {
      center: [114.6798, 4.5371],
      zoom: 8.66,
    },
    maxErrorKm: 40,
  },
  btn: {
    initialView: {
      center: [90.4094, 27.5304],
      zoom: 7.56,
    },
    maxErrorKm: 97,
  },
  bwa: {
    initialView: {
      center: [24.6642, -22.4114],
      zoom: 5.42,
    },
    maxErrorKm: 273,
  },
  caf: {
    initialView: {
      center: [20.9143, 6.6381],
      zoom: 5.58,
    },
    maxErrorKm: 335,
  },
  can: {
    initialView: {
      center: [-96.8111, 71.3424],
      zoom: 1.87,
    },
    maxErrorKm: 830,
  },
  che: {
    initialView: {
      center: [8.2107, 46.8201],
      zoom: 7.13,
    },
    maxErrorKm: 84,
  },
  chl: {
    initialView: {
      center: [-71.0661, -39.2743],
      zoom: 3.08,
    },
    maxErrorKm: 362,
  },
  chn: {
    initialView: {
      center: [104.1874, 36.9625],
      zoom: 3.14,
    },
    maxErrorKm: 924,
  },
  civ: {
    initialView: {
      center: [-5.5625, 7.547],
      zoom: 6.03,
    },
    maxErrorKm: 240,
  },
  cmr: {
    initialView: {
      center: [12.3564, 7.4048],
      zoom: 5.19,
    },
    maxErrorKm: 269,
  },
  cod: {
    initialView: {
      center: [21.7455, -4.0968],
      zoom: 4.48,
    },
    maxErrorKm: 895,
  },
  cog: {
    initialView: {
      center: [14.8782, -0.6576],
      zoom: 5.59,
    },
    maxErrorKm: 323,
  },
  cok: {
    initialView: {
      center: [-159.7911, -21.2202],
      zoom: 11,
    },
    maxErrorKm: 5,
  },
  col: {
    initialView: {
      center: [-72.9483, 4.1601],
      zoom: 4.65,
    },
    maxErrorKm: 360,
  },
  com: {
    initialView: {
      center: [43.8711, -11.8713],
      zoom: 8.66,
    },
    maxErrorKm: 71,
  },
  cpv: {
    initialView: {
      center: [-24.0135, 16.0039],
      zoom: 7.4,
    },
    maxErrorKm: 168,
  },
  cri: {
    initialView: {
      center: [-84.2546, 9.6261],
      zoom: 7.03,
    },
    maxErrorKm: 71,
  },
  cub: {
    initialView: {
      center: [-79.5412, 21.5569],
      zoom: 5.87,
    },
    maxErrorKm: 254,
  },
  cuw: {
    initialView: {
      center: [-68.9557, 12.2165],
      zoom: 10.2,
    },
    maxErrorKm: 25,
  },
  cym: {
    initialView: {
      center: [-80.5716, 19.5109],
      zoom: 8.55,
    },
    maxErrorKm: 85,
  },
  cyp: {
    initialView: {
      center: [33.1854, 34.9065],
      zoom: 8.44,
    },
    maxErrorKm: 56,
  },
  cze: {
    initialView: {
      center: [15.4568, 49.8149],
      zoom: 6.55,
    },
    maxErrorKm: 141,
  },
  deu: {
    initialView: {
      center: [10.4373, 51.3335],
      zoom: 5.08,
    },
    maxErrorKm: 233,
  },
  dji: {
    initialView: {
      center: [42.5839, 11.8203],
      zoom: 7.86,
    },
    maxErrorKm: 60,
  },
  dma: {
    initialView: {
      center: [-61.3691, 15.4179],
      zoom: 9.88,
    },
    maxErrorKm: 17,
  },
  dnk: {
    initialView: {
      center: [11.6227, 56.1929],
      zoom: 6.2,
    },
    maxErrorKm: 130,
  },
  dom: {
    initialView: {
      center: [-70.1692, 18.7459],
      zoom: 7.38,
    },
    maxErrorKm: 111,
  },
  dza: {
    initialView: {
      center: [1.6432, 28.4208],
      zoom: 4.35,
    },
    maxErrorKm: 287,
  },
  ecu: {
    initialView: {
      center: [-78.1201, -1.7914],
      zoom: 6.03,
    },
    maxErrorKm: 190,
  },
  egy: {
    initialView: {
      center: [30.7938, 26.9288],
      zoom: 5.28,
    },
    maxErrorKm: 235,
  },
  eri: {
    initialView: {
      center: [39.7738, 15.2013],
      zoom: 6.17,
    },
    maxErrorKm: 106,
  },
  esh: {
    initialView: {
      center: [-12.8927, 24.2609],
      zoom: 5.8,
    },
    maxErrorKm: 458,
  },
  esp: {
    initialView: {
      center: [-2.4774, 39.6165],
      zoom: 5.24,
    },
    maxErrorKm: 435,
  },
  est: {
    initialView: {
      center: [25.0094, 58.61],
      zoom: 6.64,
    },
    maxErrorKm: 110,
  },
  eth: {
    initialView: {
      center: [40.4845, 9.1879],
      zoom: 5.18,
    },
    maxErrorKm: 358,
  },
  fin: {
    initialView: {
      center: [26.0963, 65.4412],
      zoom: 4.1,
    },
    maxErrorKm: 217,
  },
  fji: {
    initialView: {
      center: [179.4389, -18.4116],
      zoom: 6.46,
    },
    maxErrorKm: 94,
  },
  flk: {
    initialView: {
      center: [-58.7279, -51.7984],
      zoom: 7.9,
    },
    maxErrorKm: 25,
  },
  fra: {
    initialView: {
      center: [2.2134, 46.443],
      zoom: 4.9,
    },
    maxErrorKm: 339,
  },
  fro: {
    initialView: {
      center: [-6.9002, 61.8692],
      zoom: 7.72,
    },
    maxErrorKm: 38,
  },
  fsm: {
    initialView: {
      center: [148.2012, 8.191],
      zoom: 4.96,
    },
    maxErrorKm: 1232,
  },
  gab: {
    initialView: {
      center: [11.5973, -0.8084],
      zoom: 6.07,
    },
    maxErrorKm: 291,
  },
  gbr: {
    initialView: {
      center: [-3.2013, 54.5502],
      zoom: 4.81,
    },
    maxErrorKm: 175,
  },
  geo: {
    initialView: {
      center: [43.3404, 42.3227],
      zoom: 6.56,
    },
    maxErrorKm: 121,
  },
  ggy: {
    initialView: {
      center: [-2.4219, 49.5717],
      zoom: 9.74,
    },
    maxErrorKm: 25,
  },
  gha: {
    initialView: {
      center: [-1.0373, 7.9626],
      zoom: 6.02,
    },
    maxErrorKm: 207,
  },
  gib: {
    initialView: {
      center: [-5.3486, 36.1258],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  gin: {
    initialView: {
      center: [-11.3718, 9.9433],
      zoom: 6.24,
    },
    maxErrorKm: 250,
  },
  glp: {
    initialView: {
      center: [-61.5338, 16.1784],
      zoom: 9.43,
    },
    maxErrorKm: 27,
  },
  gmb: {
    initialView: {
      center: [-15.3242, 13.4428],
      zoom: 7.72,
    },
    maxErrorKm: 105,
  },
  gnb: {
    initialView: {
      center: [-15.1946, 11.8049],
      zoom: 7.69,
    },
    maxErrorKm: 86,
  },
  gnq: {
    initialView: {
      center: [9.8792, 2.3494],
      zoom: 7.21,
    },
    maxErrorKm: 122,
  },
  grc: {
    initialView: {
      center: [23.9331, 38.3657],
      zoom: 5.58,
    },
    maxErrorKm: 232,
  },
  grd: {
    initialView: {
      center: [-61.6061, 12.2664],
      zoom: 9.61,
    },
    maxErrorKm: 16,
  },
  grl: {
    initialView: {
      center: [-42.217, 76.031],
      zoom: 2.22,
    },
    maxErrorKm: 584,
  },
  gtm: {
    initialView: {
      center: [-90.2336, 15.784],
      zoom: 6.63,
    },
    maxErrorKm: 97,
  },
  guf: {
    initialView: {
      center: [-53.3049, 4.656],
      zoom: 7.7,
    },
    maxErrorKm: 182,
  },
  gum: {
    initialView: {
      center: [144.7882, 13.4477],
      zoom: 9.96,
    },
    maxErrorKm: 13,
  },
  guy: {
    initialView: {
      center: [-58.9393, 4.882],
      zoom: 5.83,
    },
    maxErrorKm: 100,
  },
  hkg: {
    initialView: {
      center: [114.1193, 22.3706],
      zoom: 9.98,
    },
    maxErrorKm: 16,
  },
  hnd: {
    initialView: {
      center: [-86.2471, 15.2109],
      zoom: 6.52,
    },
    maxErrorKm: 127,
  },
  hrv: {
    initialView: {
      center: [16.4547, 44.5182],
      zoom: 6.19,
    },
    maxErrorKm: 175,
  },
  hti: {
    initialView: {
      center: [-73.0641, 19.0611],
      zoom: 7.59,
    },
    maxErrorKm: 106,
  },
  hun: {
    initialView: {
      center: [19.4858, 47.1741],
      zoom: 6.54,
    },
    maxErrorKm: 132,
  },
  idn: {
    initialView: {
      center: [118.0875, -2.3833],
      zoom: 3.79,
    },
    maxErrorKm: 710,
  },
  imn: {
    initialView: {
      center: [-4.551, 54.2384],
      zoom: 9.41,
    },
    maxErrorKm: 18,
  },
  ind: {
    initialView: {
      center: [82.7528, 22.4589],
      zoom: 3.82,
    },
    maxErrorKm: 970,
  },
  irl: {
    initialView: {
      center: [-8.2358, 53.4617],
      zoom: 5.99,
    },
    maxErrorKm: 124,
  },
  irn: {
    initialView: {
      center: [53.6672, 32.7179],
      zoom: 4.59,
    },
    maxErrorKm: 471,
  },
  irq: {
    initialView: {
      center: [43.6669, 33.3183],
      zoom: 5.41,
    },
    maxErrorKm: 272,
  },
  isl: {
    initialView: {
      center: [-19.0214, 65.0274],
      zoom: 5.81,
    },
    maxErrorKm: 196,
  },
  isr: {
    initialView: {
      center: [35.0682, 31.4687],
      zoom: 6.52,
    },
    maxErrorKm: 58,
  },
  ita: {
    initialView: {
      center: [12.5601, 41.5465],
      zoom: 4.77,
    },
    maxErrorKm: 352,
  },
  jam: {
    initialView: {
      center: [-77.2813, 18.1146],
      zoom: 8.18,
    },
    maxErrorKm: 67,
  },
  jey: {
    initialView: {
      center: [-2.1252, 49.2192],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  jor: {
    initialView: {
      center: [37.1207, 31.304],
      zoom: 6.43,
    },
    maxErrorKm: 54,
  },
  jpn: {
    initialView: {
      center: [134.3816, 35.5895],
      zoom: 4.01,
    },
    maxErrorKm: 271,
  },
  kaz: {
    initialView: {
      center: [66.901, 48.5507],
      zoom: 3.95,
    },
    maxErrorKm: 865,
  },
  ken: {
    initialView: {
      center: [37.8877, 0.1771],
      zoom: 5.44,
    },
    maxErrorKm: 238,
  },
  kgz: {
    initialView: {
      center: [74.7419, 41.2572],
      zoom: 5.84,
    },
    maxErrorKm: 214,
  },
  khm: {
    initialView: {
      center: [104.962, 12.5691],
      zoom: 6.58,
    },
    maxErrorKm: 222,
  },
  kir: {
    initialView: {
      center: [-172.0817, 1.6852],
      zoom: 4.41,
    },
    maxErrorKm: 20,
  },
  kna: {
    initialView: {
      center: [-62.6989, 17.2583],
      zoom: 10.32,
    },
    maxErrorKm: 10,
  },
  kor: {
    initialView: {
      center: [128.2381, 35.9575],
      zoom: 5.98,
    },
    maxErrorKm: 158,
  },
  kwt: {
    initialView: {
      center: [47.4826, 29.3189],
      zoom: 7.88,
    },
    maxErrorKm: 31,
  },
  lao: {
    initialView: {
      center: [103.8807, 18.2587],
      zoom: 5.54,
    },
    maxErrorKm: 310,
  },
  lbn: {
    initialView: {
      center: [35.8519, 33.8755],
      zoom: 7.75,
    },
    maxErrorKm: 52,
  },
  lbr: {
    initialView: {
      center: [-9.4302, 6.4607],
      zoom: 6.63,
    },
    maxErrorKm: 221,
  },
  lby: {
    initialView: {
      center: [17.2214, 26.5423],
      zoom: 4.78,
    },
    maxErrorKm: 588,
  },
  lca: {
    initialView: {
      center: [-60.9807, 13.9134],
      zoom: 10.01,
    },
    maxErrorKm: 17,
  },
  lie: {
    initialView: {
      center: [9.5458, 47.1577],
      zoom: 10.41,
    },
    maxErrorKm: 3,
  },
  lka: {
    initialView: {
      center: [80.773, 7.8813],
      zoom: 6.74,
    },
    maxErrorKm: 119,
  },
  lso: {
    initialView: {
      center: [28.219, -29.6202],
      zoom: 7.46,
    },
    maxErrorKm: 83,
  },
  ltu: {
    initialView: {
      center: [23.8626, 55.1852],
      zoom: 6.56,
    },
    maxErrorKm: 123,
  },
  lux: {
    initialView: {
      center: [6.1088, 49.8095],
      zoom: 8.54,
    },
    maxErrorKm: 35,
  },
  lva: {
    initialView: {
      center: [24.5929, 56.8905],
      zoom: 6.45,
    },
    maxErrorKm: 130,
  },
  mac: {
    initialView: {
      center: [113.5537, 22.1631],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  maf: {
    initialView: {
      center: [-63.0788, 18.0778],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  mar: {
    initialView: {
      center: [-9.0229, 28.9263],
      zoom: 4.67,
    },
    maxErrorKm: 263,
  },
  mco: {
    initialView: {
      center: [7.4016, 43.7407],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  mda: {
    initialView: {
      center: [28.3747, 46.9953],
      zoom: 6.57,
    },
    maxErrorKm: 93,
  },
  mdg: {
    initialView: {
      center: [46.8634, -18.9102],
      zoom: 4.87,
    },
    maxErrorKm: 387,
  },
  mdv: {
    initialView: {
      center: [73.492, 3.036],
      zoom: 7.45,
    },
    maxErrorKm: 216,
  },
  mex: {
    initialView: {
      center: [-102.5347, 23.9483],
      zoom: 4.32,
    },
    maxErrorKm: 544,
  },
  mhl: {
    initialView: {
      center: [171.2146, 7.1192],
      zoom: 10.79,
    },
    maxErrorKm: 25,
  },
  mkd: {
    initialView: {
      center: [21.7269, 41.6143],
      zoom: 7.7,
    },
    maxErrorKm: 79,
  },
  mli: {
    initialView: {
      center: [-4.0142, 17.7211],
      zoom: 4.75,
    },
    maxErrorKm: 321,
  },
  mlt: {
    initialView: {
      center: [14.3754, 35.9385],
      zoom: 10.28,
    },
    maxErrorKm: 5,
  },
  mmr: {
    initialView: {
      center: [96.6744, 19.4343],
      zoom: 4.4,
    },
    maxErrorKm: 380,
  },
  mne: {
    initialView: {
      center: [19.3944, 42.7059],
      zoom: 7.51,
    },
    maxErrorKm: 51,
  },
  mng: {
    initialView: {
      center: [103.8214, 47.1182],
      zoom: 4.3,
    },
    maxErrorKm: 504,
  },
  mnp: {
    initialView: {
      center: [145.4715, 14.6922],
      zoom: 8.46,
    },
    maxErrorKm: 67,
  },
  moz: {
    initialView: {
      center: [35.5309, -18.8645],
      zoom: 4.6,
    },
    maxErrorKm: 604,
  },
  mrt: {
    initialView: {
      center: [-10.9514, 21.1426],
      zoom: 4.97,
    },
    maxErrorKm: 378,
  },
  msr: {
    initialView: {
      center: [-62.1853, 16.7474],
      zoom: 11,
    },
    maxErrorKm: 4,
  },
  mtq: {
    initialView: {
      center: [-60.9562, 14.6261],
      zoom: 10.34,
    },
    maxErrorKm: 14,
  },
  mus: {
    initialView: {
      center: [57.5496, -20.2486],
      zoom: 9.52,
    },
    maxErrorKm: 24,
  },
  mwi: {
    initialView: {
      center: [34.2838, -13.2893],
      zoom: 5.73,
    },
    maxErrorKm: 211,
  },
  mys: {
    initialView: {
      center: [114.4033, 4.1102],
      zoom: 6.01,
    },
    maxErrorKm: 309,
  },
  myt: {
    initialView: {
      center: [45.1688, -12.829],
      zoom: 10.69,
    },
    maxErrorKm: 14,
  },
  nam: {
    initialView: {
      center: [18.4887, -23.0891],
      zoom: 5.01,
    },
    maxErrorKm: 392,
  },
  ncl: {
    initialView: {
      center: [165.88, -21.155],
      zoom: 7.01,
    },
    maxErrorKm: 122,
  },
  ner: {
    initialView: {
      center: [8.0616, 17.7038],
      zoom: 5.09,
    },
    maxErrorKm: 389,
  },
  nfk: {
    initialView: {
      center: [167.9542, -29.0388],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  nga: {
    initialView: {
      center: [8.6705, 9.1085],
      zoom: 5.44,
    },
    maxErrorKm: 424,
  },
  nic: {
    initialView: {
      center: [-85.2058, 12.8815],
      zoom: 6.57,
    },
    maxErrorKm: 123,
  },
  niu: {
    initialView: {
      center: [-169.8667, -19.0534],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  nld: {
    initialView: {
      center: [5.274, 52.175],
      zoom: 6.52,
    },
    maxErrorKm: 77,
  },
  nor: {
    initialView: {
      center: [17.8604, 65.3922],
      zoom: 3.75,
    },
    maxErrorKm: 325,
  },
  npl: {
    initialView: {
      center: [84.0997, 28.3999],
      zoom: 6.28,
    },
    maxErrorKm: 216,
  },
  nzl: {
    initialView: {
      center: [172.2263, -44.0862],
      zoom: 4.04,
    },
    maxErrorKm: 338,
  },
  omn: {
    initialView: {
      center: [55.9116, 21.5961],
      zoom: 5.33,
    },
    maxErrorKm: 168,
  },
  pak: {
    initialView: {
      center: [68.9467, 30.6043],
      zoom: 4.76,
    },
    maxErrorKm: 333,
  },
  pan: {
    initialView: {
      center: [-80.1083, 8.4194],
      zoom: 6.75,
    },
    maxErrorKm: 157,
  },
  per: {
    initialView: {
      center: [-75.0109, -9.3029],
      zoom: 4.5,
    },
    maxErrorKm: 493,
  },
  phl: {
    initialView: {
      center: [121.903, 12.1899],
      zoom: 4.98,
    },
    maxErrorKm: 358,
  },
  plw: {
    initialView: {
      center: [132.9292, 5.5284],
      zoom: 6.35,
    },
    maxErrorKm: 25,
  },
  png: {
    initialView: {
      center: [148.4084, -6.5177],
      zoom: 5.35,
    },
    maxErrorKm: 527,
  },
  pol: {
    initialView: {
      center: [19.1335, 52.0115],
      zoom: 5.47,
    },
    maxErrorKm: 247,
  },
  pri: {
    initialView: {
      center: [-66.5912, 18.2231],
      zoom: 7.88,
    },
    maxErrorKm: 53,
  },
  prk: {
    initialView: {
      center: [127.4556, 40.3957],
      zoom: 5.91,
    },
    maxErrorKm: 196,
  },
  prt: {
    initialView: {
      center: [-7.8517, 39.6083],
      zoom: 5.97,
    },
    maxErrorKm: 173,
  },
  pry: {
    initialView: {
      center: [-58.4478, -23.5021],
      zoom: 5.54,
    },
    maxErrorKm: 160,
  },
  pse: {
    initialView: {
      center: [34.8864, 31.8794],
      zoom: 8.07,
    },
    maxErrorKm: 40,
  },
  pyf: {
    initialView: {
      center: [-145.8993, -13.3678],
      zoom: 5.5,
    },
    maxErrorKm: 183,
  },
  qat: {
    initialView: {
      center: [51.1838, 25.3626],
      zoom: 7.9,
    },
    maxErrorKm: 33,
  },
  reu: {
    initialView: {
      center: [55.5338, -21.1302],
      zoom: 9.63,
    },
    maxErrorKm: 33,
  },
  rou: {
    initialView: {
      center: [24.9712, 46.0108],
      zoom: 5.99,
    },
    maxErrorKm: 222,
  },
  rus: {
    initialView: {
      center: [108.9749, 69.6267],
      zoom: 1.95,
    },
    maxErrorKm: 1188,
  },
  rwa: {
    initialView: {
      center: [29.8725, -1.943],
      zoom: 7.9,
    },
    maxErrorKm: 91,
  },
  sau: {
    initialView: {
      center: [45.1052, 24.4921],
      zoom: 4.6,
    },
    maxErrorKm: 634,
  },
  sdn: {
    initialView: {
      center: [30.2067, 15.5656],
      zoom: 4.9,
    },
    maxErrorKm: 574,
  },
  sen: {
    initialView: {
      center: [-14.4569, 14.5094],
      zoom: 6.54,
    },
    maxErrorKm: 215,
  },
  sgp: {
    initialView: {
      center: [103.8219, 1.3565],
      zoom: 10.77,
    },
    maxErrorKm: 25,
  },
  shn: {
    initialView: {
      center: [-5.72, -15.9589],
      zoom: 11,
    },
    maxErrorKm: 1297,
  },
  sjm: {
    initialView: {
      center: [14.9293, 78.1441],
      zoom: 8.78,
    },
    maxErrorKm: 37,
  },
  slb: {
    initialView: {
      center: [161.6222, -9.5164],
      zoom: 6.13,
    },
    maxErrorKm: 335,
  },
  sle: {
    initialView: {
      center: [-11.7917, 8.4608],
      zoom: 7.08,
    },
    maxErrorKm: 126,
  },
  slv: {
    initialView: {
      center: [-88.904, 13.8029],
      zoom: 8.03,
    },
    maxErrorKm: 70,
  },
  smr: {
    initialView: {
      center: [12.439, 43.9373],
      zoom: 11,
    },
    maxErrorKm: 5,
  },
  som: {
    initialView: {
      center: [46.1912, 5.1834],
      zoom: 4.94,
    },
    maxErrorKm: 485,
  },
  srb: {
    initialView: {
      center: [20.9148, 44.2374],
      zoom: 6.26,
    },
    maxErrorKm: 119,
  },
  ssd: {
    initialView: {
      center: [30.0212, 7.8761],
      zoom: 5.58,
    },
    maxErrorKm: 394,
  },
  stp: {
    initialView: {
      center: [6.9622, 0.862],
      zoom: 7.98,
    },
    maxErrorKm: 92,
  },
  sur: {
    initialView: {
      center: [-56.027, 3.9252],
      zoom: 6.65,
    },
    maxErrorKm: 117,
  },
  svk: {
    initialView: {
      center: [19.6921, 48.6844],
      zoom: 6.8,
    },
    maxErrorKm: 115,
  },
  svn: {
    initialView: {
      center: [14.9403, 46.1485],
      zoom: 7.65,
    },
    maxErrorKm: 68,
  },
  swe: {
    initialView: {
      center: [17.6358, 62.9801],
      zoom: 3.82,
    },
    maxErrorKm: 244,
  },
  swz: {
    initialView: {
      center: [31.4502, -26.5289],
      zoom: 7.9,
    },
    maxErrorKm: 65,
  },
  sxm: {
    initialView: {
      center: [-63.0682, 18.0406],
      zoom: 11,
    },
    maxErrorKm: 2,
  },
  syc: {
    initialView: {
      center: [55.4518, -4.6822],
      zoom: 10.76,
    },
    maxErrorKm: 25,
  },
  syr: {
    initialView: {
      center: [39.0503, 34.8571],
      zoom: 6.11,
    },
    maxErrorKm: 178,
  },
  tca: {
    initialView: {
      center: [-71.7345, 21.6472],
      zoom: 9.03,
    },
    maxErrorKm: 81,
  },
  tcd: {
    initialView: {
      center: [18.7168, 15.6056],
      zoom: 4.66,
    },
    maxErrorKm: 414,
  },
  tgo: {
    initialView: {
      center: [0.8081, 8.6261],
      zoom: 6.37,
    },
    maxErrorKm: 175,
  },
  tha: {
    initialView: {
      center: [101.5012, 13.1491],
      zoom: 4.79,
    },
    maxErrorKm: 364,
  },
  tjk: {
    initialView: {
      center: [71.2534, 38.8928],
      zoom: 6.23,
    },
    maxErrorKm: 170,
  },
  tkm: {
    initialView: {
      center: [59.5417, 39.0695],
      zoom: 5.42,
    },
    maxErrorKm: 437,
  },
  tls: {
    initialView: {
      center: [125.6716, -8.8188],
      zoom: 7.59,
    },
    maxErrorKm: 58,
  },
  ton: {
    initialView: {
      center: [-174.6395, -20.0168],
      zoom: 7.1,
    },
    maxErrorKm: 13,
  },
  tto: {
    initialView: {
      center: [-61.2254, 10.6973],
      zoom: 8.31,
    },
    maxErrorKm: 34,
  },
  tun: {
    initialView: {
      center: [9.522, 33.8611],
      zoom: 5.62,
    },
    maxErrorKm: 171,
  },
  tur: {
    initialView: {
      center: [35.2351, 39.029],
      zoom: 5.05,
    },
    maxErrorKm: 477,
  },
  tuv: {
    initialView: {
      center: [179.2044, -8.5014],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  twn: {
    initialView: {
      center: [120.1425, 23.6069],
      zoom: 6.84,
    },
    maxErrorKm: 103,
  },
  tza: {
    initialView: {
      center: [34.8852, -6.3867],
      zoom: 5.28,
    },
    maxErrorKm: 495,
  },
  uga: {
    initialView: {
      center: [32.2775, 1.3739],
      zoom: 6.21,
    },
    maxErrorKm: 209,
  },
  ukr: {
    initialView: {
      center: [31.1462, 48.9192],
      zoom: 5.13,
    },
    maxErrorKm: 423,
  },
  ury: {
    initialView: {
      center: [-55.7751, -32.5683],
      zoom: 6.19,
    },
    maxErrorKm: 192,
  },
  usa: {
    initialView: {
      center: [-95.856, 37.995],
      zoom: 3.45,
    },
    maxErrorKm: 1665,
  },
  uzb: {
    initialView: {
      center: [64.5622, 41.5071],
      zoom: 5.2,
    },
    maxErrorKm: 283,
  },
  vct: {
    initialView: {
      center: [-61.2919, 12.9833],
      zoom: 9.01,
    },
    maxErrorKm: 13,
  },
  ven: {
    initialView: {
      center: [-66.6034, 6.457],
      zoom: 5.18,
    },
    maxErrorKm: 324,
  },
  vgb: {
    initialView: {
      center: [-64.5201, 18.4475],
      zoom: 10.67,
    },
    maxErrorKm: 20,
  },
  vir: {
    initialView: {
      center: [-64.8004, 18.035],
      zoom: 9.15,
    },
    maxErrorKm: 66,
  },
  vnm: {
    initialView: {
      center: [105.7955, 16.1037],
      zoom: 4.77,
    },
    maxErrorKm: 574,
  },
  vut: {
    initialView: {
      center: [168.0122, -17.1583],
      zoom: 6.32,
    },
    maxErrorKm: 356,
  },
  wlf: {
    initialView: {
      center: [-176.1626, -13.2796],
      zoom: 11,
    },
    maxErrorKm: 25,
  },
  wsm: {
    initialView: {
      center: [-172.1101, -13.758],
      zoom: 8.88,
    },
    maxErrorKm: 45,
  },
  xkx: {
    initialView: {
      center: [20.8988, 42.5576],
      zoom: 7.77,
    },
    maxErrorKm: 47,
  },
  yem: {
    initialView: {
      center: [47.818, 15.8221],
      zoom: 5.91,
    },
    maxErrorKm: 203,
  },
  zaf: {
    initialView: {
      center: [24.6815, -28.6661],
      zoom: 4.86,
    },
    maxErrorKm: 426,
  },
  zmb: {
    initialView: {
      center: [27.827, -13.1815],
      zoom: 5.38,
    },
    maxErrorKm: 464,
  },
  zwe: {
    initialView: {
      center: [29.1311, -19.0407],
      zoom: 5.88,
    },
    maxErrorKm: 245,
  },
};

/**
 * Returns the generated town quiz configuration for a country.
 *
 * @param countryId - GeoPedia's lowercase three-letter country identifier.
 * @returns The country's configuration when one exists.
 */
export function getTownCountryConfig(
  countryId: string,
): TownCountryConfig | undefined {
  return townCountryConfigs[countryId.toLowerCase()];
}

/**
 * Determines whether a generated town quiz configuration exists.
 *
 * @param countryId - GeoPedia's lowercase three-letter country identifier.
 */
export function hasTownCountryConfig(countryId: string): boolean {
  return getTownCountryConfig(countryId) !== undefined;
}
