from pathlib import Path
import re


PROJECT_ROOT = Path(__file__).resolve().parents[4]

PUBLIC_JAPAN_DIR = (
    PROJECT_ROOT
    / "public"
    / "data"
    / "countries"
    / "japan"
)

OUTPUT_FILE = (
    PROJECT_ROOT
    / "src"
    / "quiz"
    / "quizzes"
    / "countries"
    / "asia"
    / "japan"
    / "data"
    / "poleMetaQuestions.ts"
)

QUESTION_SETS = [
    {
        "folder": "pole-plates",
        "constant": "JAPAN_POLE_PLATE_QUESTIONS",
        "alt": "Japanese utility pole plate",
    },
    {
        "folder": "pole-tops",
        "constant": "JAPAN_POLE_TOP_QUESTIONS",
        "alt": "Japanese utility pole top",
    },
]


def get_question_data(filename: str) -> tuple[str, str]:
    stem = Path(filename).stem

    match = re.fullmatch(r"(.+)_(\d+)", stem)

    if not match:
        raise ValueError(
            f"Unexpected filename format: {filename}"
        )

    region_id = match.group(1)
    answer = stem

    return region_id, answer


def get_display_name(region_id: str) -> str:
    return (
        region_id
        .replace("-", " ")
        .replace("_", " ")
        .title()
    )


def generate_question_set(config: dict) -> str:
    folder = config["folder"]
    constant = config["constant"]
    alt = config["alt"]

    source_dir = PUBLIC_JAPAN_DIR / folder

    if not source_dir.exists():
        raise FileNotFoundError(
            f"Image directory does not exist: {source_dir}"
        )

    images = sorted(source_dir.glob("*.webp"))

    if not images:
        raise ValueError(
            f"No WebP images found in {source_dir}"
        )

    lines = [
        f'export const {constant}: FeatureQuiz["questions"] = ['
    ]

    for image in images:
        region_id, answer = get_question_data(image.name)
        display = get_display_name(region_id)

        image_url = (
            f"/data/countries/japan/{folder}/{image.name}"
        )

        lines.extend(
            [
                "  {",
                f'    answer: "{answer}",',
                f'    display: "{display}",',
                "    prompt: {",
                '      type: "image",',
                f'      imageUrl: "{image_url}",',
                f'      alt: "{alt}",',
                "    },",
                "  },",
            ]
        )

    lines.append("];")

    return "\n".join(lines)


def main() -> None:
    question_sets = [
        generate_question_set(config)
        for config in QUESTION_SETS
    ]

    header = """/**
 * Generated Japan pole-meta quiz-support data.
 *
 * Do not edit this file manually.
 *
 * Regenerate with:
 *   python scripts/countries/japan/generate/pole-meta-questions.py
 */
"""

    content = (
        header
        + '\nimport type { FeatureQuiz } from "@/types/quiz";\n\n'
        + "\n\n".join(question_sets)
        + "\n"
    )

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    OUTPUT_FILE.write_text(
        content,
        encoding="utf-8",
    )

    print(
        f"Generated: "
        f"{OUTPUT_FILE.relative_to(PROJECT_ROOT)}"
    )

    for config in QUESTION_SETS:
        folder = PUBLIC_JAPAN_DIR / config["folder"]
        count = len(list(folder.glob("*.webp")))

        print(
            f"  {config['constant']}: "
            f"{count} questions"
        )


if __name__ == "__main__":
    main()