/**
 * AUTO-GENERATED FILE.
 *
 * Generated by:
 *
 *   scripts/generateCountryNamesQuiz.ts
 *
 * Do not edit the question list manually. Update the source world-country
 * data or generator and rerun the script instead.
 */

import type { FeatureQuiz } from "@/types/quiz";

const COUNTRY_NAME_QUESTIONS: FeatureQuiz["questions"] = [
  {
    answer: "AFG",
    display: "Afghanistan",
  },
  {
    answer: "ALA",
    display: "Åland Islands",
  },
  {
    answer: "ALB",
    display: "Albania",
  },
  {
    answer: "DZA",
    display: "Algeria",
  },
  {
    answer: "ASM",
    display: "American Samoa",
  },
  {
    answer: "AND",
    display: "Andorra",
  },
  {
    answer: "AGO",
    display: "Angola",
  },
  {
    answer: "AIA",
    display: "Anguilla",
  },
  {
    answer: "ATA",
    display: "Antarctica",
  },
  {
    answer: "ATG",
    display: "Antigua and Barbuda",
  },
  {
    answer: "ARG",
    display: "Argentina",
  },
  {
    answer: "ARM",
    display: "Armenia",
  },
  {
    answer: "ABW",
    display: "Aruba",
  },
  {
    answer: "AUS",
    display: "Australia",
  },
  {
    answer: "AUT",
    display: "Austria",
  },
  {
    answer: "AZE",
    display: "Azerbaijan",
  },
  {
    answer: "BHS",
    display: "Bahamas",
  },
  {
    answer: "BHR",
    display: "Bahrain",
  },
  {
    answer: "BGD",
    display: "Bangladesh",
  },
  {
    answer: "BRB",
    display: "Barbados",
  },
  {
    answer: "BLR",
    display: "Belarus",
  },
  {
    answer: "BEL",
    display: "Belgium",
  },
  {
    answer: "BLZ",
    display: "Belize",
  },
  {
    answer: "BEN",
    display: "Benin",
  },
  {
    answer: "BMU",
    display: "Bermuda",
  },
  {
    answer: "BTN",
    display: "Bhutan",
  },
  {
    answer: "BOL",
    display: "Bolivia",
  },
  {
    answer: "BIH",
    display: "Bosnia and Herzegovina",
  },
  {
    answer: "BWA",
    display: "Botswana",
  },
  {
    answer: "BVT",
    display: "Bouvet Island",
  },
  {
    answer: "BRA",
    display: "Brazil",
  },
  {
    answer: "IOT",
    display: "British Indian Ocean Territory",
  },
  {
    answer: "VGB",
    display: "British Virgin Islands",
  },
  {
    answer: "BRN",
    display: "Brunei",
  },
  {
    answer: "BGR",
    display: "Bulgaria",
  },
  {
    answer: "BFA",
    display: "Burkina Faso",
  },
  {
    answer: "BDI",
    display: "Burundi",
  },
  {
    answer: "CPV",
    display: "Cabo Verde",
  },
  {
    answer: "KHM",
    display: "Cambodia",
  },
  {
    answer: "CMR",
    display: "Cameroon",
  },
  {
    answer: "CAN",
    display: "Canada",
  },
  {
    answer: "BES",
    display: "Caribbean Netherlands",
  },
  {
    answer: "CYM",
    display: "Cayman Islands",
  },
  {
    answer: "CAF",
    display: "Central African Republic",
  },
  {
    answer: "TCD",
    display: "Chad",
  },
  {
    answer: "CHL",
    display: "Chile",
  },
  {
    answer: "CHN",
    display: "China",
  },
  {
    answer: "CXR",
    display: "Christmas Island",
  },
  {
    answer: "CCK",
    display: "Cocos (Keeling) Islands",
  },
  {
    answer: "COL",
    display: "Colombia",
  },
  {
    answer: "COM",
    display: "Comoros",
  },
  {
    answer: "COG",
    display: "Congo",
  },
  {
    answer: "COK",
    display: "Cook Islands",
  },
  {
    answer: "CRI",
    display: "Costa Rica",
  },
  {
    answer: "HRV",
    display: "Croatia",
  },
  {
    answer: "CUB",
    display: "Cuba",
  },
  {
    answer: "CUW",
    display: "Curaçao",
  },
  {
    answer: "CYP",
    display: "Cyprus",
  },
  {
    answer: "CZE",
    display: "Czechia",
  },
  {
    answer: "DNK",
    display: "Denmark",
  },
  {
    answer: "DJI",
    display: "Djibouti",
  },
  {
    answer: "DMA",
    display: "Dominica",
  },
  {
    answer: "DOM",
    display: "Dominican Republic",
  },
  {
    answer: "COD",
    display: "DRC",
  },
  {
    answer: "ECU",
    display: "Ecuador",
  },
  {
    answer: "EGY",
    display: "Egypt",
  },
  {
    answer: "SLV",
    display: "El Salvador",
  },
  {
    answer: "GNQ",
    display: "Equatorial Guinea",
  },
  {
    answer: "ERI",
    display: "Eritrea",
  },
  {
    answer: "EST",
    display: "Estonia",
  },
  {
    answer: "SWZ",
    display: "Eswatini",
  },
  {
    answer: "ETH",
    display: "Ethiopia",
  },
  {
    answer: "FLK",
    display: "Falkland Islands",
  },
  {
    answer: "FRO",
    display: "Faroe Islands",
  },
  {
    answer: "FJI",
    display: "Fiji",
  },
  {
    answer: "FIN",
    display: "Finland",
  },
  {
    answer: "FRA",
    display: "France",
  },
  {
    answer: "GUF",
    display: "French Guiana",
  },
  {
    answer: "PYF",
    display: "French Polynesia",
  },
  {
    answer: "ATF",
    display: "French Southern and Antarctic Lands",
  },
  {
    answer: "GAB",
    display: "Gabon",
  },
  {
    answer: "GMB",
    display: "Gambia",
  },
  {
    answer: "GEO",
    display: "Georgia",
  },
  {
    answer: "DEU",
    display: "Germany",
  },
  {
    answer: "GHA",
    display: "Ghana",
  },
  {
    answer: "GIB",
    display: "Gibraltar",
  },
  {
    answer: "GRC",
    display: "Greece",
  },
  {
    answer: "GRL",
    display: "Greenland",
  },
  {
    answer: "GRD",
    display: "Grenada",
  },
  {
    answer: "GLP",
    display: "Guadeloupe",
  },
  {
    answer: "GUM",
    display: "Guam",
  },
  {
    answer: "GTM",
    display: "Guatemala",
  },
  {
    answer: "GGY",
    display: "Guernsey",
  },
  {
    answer: "GIN",
    display: "Guinea",
  },
  {
    answer: "GNB",
    display: "Guinea-Bissau",
  },
  {
    answer: "GUY",
    display: "Guyana",
  },
  {
    answer: "HTI",
    display: "Haiti",
  },
  {
    answer: "HMD",
    display: "Heard Island and McDonald Islands",
  },
  {
    answer: "HND",
    display: "Honduras",
  },
  {
    answer: "HKG",
    display: "Hong Kong",
  },
  {
    answer: "HUN",
    display: "Hungary",
  },
  {
    answer: "ISL",
    display: "Iceland",
  },
  {
    answer: "IND",
    display: "India",
  },
  {
    answer: "IDN",
    display: "Indonesia",
  },
  {
    answer: "IRN",
    display: "Iran",
  },
  {
    answer: "IRQ",
    display: "Iraq",
  },
  {
    answer: "IRL",
    display: "Ireland",
  },
  {
    answer: "IMN",
    display: "Isle of Man",
  },
  {
    answer: "ISR",
    display: "Israel",
  },
  {
    answer: "ITA",
    display: "Italy",
  },
  {
    answer: "CIV",
    display: "Ivory Coast",
  },
  {
    answer: "JAM",
    display: "Jamaica",
  },
  {
    answer: "JPN",
    display: "Japan",
  },
  {
    answer: "JEY",
    display: "Jersey",
  },
  {
    answer: "JOR",
    display: "Jordan",
  },
  {
    answer: "KAZ",
    display: "Kazakhstan",
  },
  {
    answer: "KEN",
    display: "Kenya",
  },
  {
    answer: "KIR",
    display: "Kiribati",
  },
  {
    answer: "XKX",
    display: "Kosovo",
  },
  {
    answer: "KWT",
    display: "Kuwait",
  },
  {
    answer: "KGZ",
    display: "Kyrgyzstan",
  },
  {
    answer: "LAO",
    display: "Laos",
  },
  {
    answer: "LVA",
    display: "Latvia",
  },
  {
    answer: "LBN",
    display: "Lebanon",
  },
  {
    answer: "LSO",
    display: "Lesotho",
  },
  {
    answer: "LBR",
    display: "Liberia",
  },
  {
    answer: "LBY",
    display: "Libya",
  },
  {
    answer: "LIE",
    display: "Liechtenstein",
  },
  {
    answer: "LTU",
    display: "Lithuania",
  },
  {
    answer: "LUX",
    display: "Luxembourg",
  },
  {
    answer: "MAC",
    display: "Macau",
  },
  {
    answer: "MDG",
    display: "Madagascar",
  },
  {
    answer: "MWI",
    display: "Malawi",
  },
  {
    answer: "MYS",
    display: "Malaysia",
  },
  {
    answer: "MDV",
    display: "Maldives",
  },
  {
    answer: "MLI",
    display: "Mali",
  },
  {
    answer: "MLT",
    display: "Malta",
  },
  {
    answer: "MHL",
    display: "Marshall Islands",
  },
  {
    answer: "MTQ",
    display: "Martinique",
  },
  {
    answer: "MRT",
    display: "Mauritania",
  },
  {
    answer: "MUS",
    display: "Mauritius",
  },
  {
    answer: "MYT",
    display: "Mayotte",
  },
  {
    answer: "MEX",
    display: "Mexico",
  },
  {
    answer: "FSM",
    display: "Micronesia",
  },
  {
    answer: "MDA",
    display: "Moldova",
  },
  {
    answer: "MCO",
    display: "Monaco",
  },
  {
    answer: "MNG",
    display: "Mongolia",
  },
  {
    answer: "MNE",
    display: "Montenegro",
  },
  {
    answer: "MSR",
    display: "Montserrat",
  },
  {
    answer: "MAR",
    display: "Morocco",
  },
  {
    answer: "MOZ",
    display: "Mozambique",
  },
  {
    answer: "MMR",
    display: "Myanmar",
  },
  {
    answer: "NAM",
    display: "Namibia",
  },
  {
    answer: "NRU",
    display: "Nauru",
  },
  {
    answer: "NPL",
    display: "Nepal",
  },
  {
    answer: "NLD",
    display: "Netherlands",
  },
  {
    answer: "NCL",
    display: "New Caledonia",
  },
  {
    answer: "NZL",
    display: "New Zealand",
  },
  {
    answer: "NIC",
    display: "Nicaragua",
  },
  {
    answer: "NER",
    display: "Niger",
  },
  {
    answer: "NGA",
    display: "Nigeria",
  },
  {
    answer: "NIU",
    display: "Niue",
  },
  {
    answer: "NFK",
    display: "Norfolk Island",
  },
  {
    answer: "PRK",
    display: "North Korea",
  },
  {
    answer: "MKD",
    display: "North Macedonia",
  },
  {
    answer: "MNP",
    display: "Northern Mariana Islands",
  },
  {
    answer: "NOR",
    display: "Norway",
  },
  {
    answer: "OMN",
    display: "Oman",
  },
  {
    answer: "PAK",
    display: "Pakistan",
  },
  {
    answer: "PLW",
    display: "Palau",
  },
  {
    answer: "PSE",
    display: "Palestine",
  },
  {
    answer: "PAN",
    display: "Panama",
  },
  {
    answer: "PNG",
    display: "Papua New Guinea",
  },
  {
    answer: "PRY",
    display: "Paraguay",
  },
  {
    answer: "PER",
    display: "Peru",
  },
  {
    answer: "PHL",
    display: "Philippines",
  },
  {
    answer: "PCN",
    display: "Pitcairn Islands",
  },
  {
    answer: "POL",
    display: "Poland",
  },
  {
    answer: "PRT",
    display: "Portugal",
  },
  {
    answer: "PRI",
    display: "Puerto Rico",
  },
  {
    answer: "QAT",
    display: "Qatar",
  },
  {
    answer: "REU",
    display: "Réunion",
  },
  {
    answer: "ROU",
    display: "Romania",
  },
  {
    answer: "RUS",
    display: "Russia",
  },
  {
    answer: "RWA",
    display: "Rwanda",
  },
  {
    answer: "BLM",
    display: "Saint Barthélemy",
  },
  {
    answer: "SHN",
    display: "Saint Helena, Ascension and Tristan da Cunha",
  },
  {
    answer: "KNA",
    display: "Saint Kitts and Nevis",
  },
  {
    answer: "LCA",
    display: "Saint Lucia",
  },
  {
    answer: "MAF",
    display: "Saint Martin",
  },
  {
    answer: "SPM",
    display: "Saint Pierre and Miquelon",
  },
  {
    answer: "VCT",
    display: "Saint Vincent and the Grenadines",
  },
  {
    answer: "WSM",
    display: "Samoa",
  },
  {
    answer: "SMR",
    display: "San Marino",
  },
  {
    answer: "STP",
    display: "São Tomé and Príncipe",
  },
  {
    answer: "SAU",
    display: "Saudi Arabia",
  },
  {
    answer: "SEN",
    display: "Senegal",
  },
  {
    answer: "SRB",
    display: "Serbia",
  },
  {
    answer: "SYC",
    display: "Seychelles",
  },
  {
    answer: "SLE",
    display: "Sierra Leone",
  },
  {
    answer: "SGP",
    display: "Singapore",
  },
  {
    answer: "SXM",
    display: "Sint Maarten",
  },
  {
    answer: "SVK",
    display: "Slovakia",
  },
  {
    answer: "SVN",
    display: "Slovenia",
  },
  {
    answer: "SLB",
    display: "Solomon Islands",
  },
  {
    answer: "SOM",
    display: "Somalia",
  },
  {
    answer: "ZAF",
    display: "South Africa",
  },
  {
    answer: "SGS",
    display: "South Georgia",
  },
  {
    answer: "KOR",
    display: "South Korea",
  },
  {
    answer: "SSD",
    display: "South Sudan",
  },
  {
    answer: "ESP",
    display: "Spain",
  },
  {
    answer: "LKA",
    display: "Sri Lanka",
  },
  {
    answer: "SDN",
    display: "Sudan",
  },
  {
    answer: "SUR",
    display: "Suriname",
  },
  {
    answer: "SJM",
    display: "Svalbard and Jan Mayen",
  },
  {
    answer: "SWE",
    display: "Sweden",
  },
  {
    answer: "CHE",
    display: "Switzerland",
  },
  {
    answer: "SYR",
    display: "Syria",
  },
  {
    answer: "TWN",
    display: "Taiwan",
  },
  {
    answer: "TJK",
    display: "Tajikistan",
  },
  {
    answer: "TZA",
    display: "Tanzania",
  },
  {
    answer: "THA",
    display: "Thailand",
  },
  {
    answer: "TLS",
    display: "Timor-Leste",
  },
  {
    answer: "TGO",
    display: "Togo",
  },
  {
    answer: "TKL",
    display: "Tokelau",
  },
  {
    answer: "TON",
    display: "Tonga",
  },
  {
    answer: "TTO",
    display: "Trinidad and Tobago",
  },
  {
    answer: "TUN",
    display: "Tunisia",
  },
  {
    answer: "TUR",
    display: "Turkey",
  },
  {
    answer: "TKM",
    display: "Turkmenistan",
  },
  {
    answer: "TCA",
    display: "Turks and Caicos Islands",
  },
  {
    answer: "TUV",
    display: "Tuvalu",
  },
  {
    answer: "UGA",
    display: "Uganda",
  },
  {
    answer: "UKR",
    display: "Ukraine",
  },
  {
    answer: "ARE",
    display: "United Arab Emirates",
  },
  {
    answer: "GBR",
    display: "United Kingdom",
  },
  {
    answer: "USA",
    display: "United States",
  },
  {
    answer: "UMI",
    display: "United States Minor Outlying Islands",
  },
  {
    answer: "VIR",
    display: "United States Virgin Islands",
  },
  {
    answer: "URY",
    display: "Uruguay",
  },
  {
    answer: "UZB",
    display: "Uzbekistan",
  },
  {
    answer: "VUT",
    display: "Vanuatu",
  },
  {
    answer: "VAT",
    display: "Vatican City",
  },
  {
    answer: "VEN",
    display: "Venezuela",
  },
  {
    answer: "VNM",
    display: "Vietnam",
  },
  {
    answer: "WLF",
    display: "Wallis and Futuna",
  },
  {
    answer: "ESH",
    display: "Western Sahara",
  },
  {
    answer: "YEM",
    display: "Yemen",
  },
  {
    answer: "ZMB",
    display: "Zambia",
  },
  {
    answer: "ZWE",
    display: "Zimbabwe",
  },
];

const COUNTRY_NAMES_DESCRIPTION = `Identify all ${COUNTRY_NAME_QUESTIONS.length} countries by their names on the map, with filters for GeoGuessr countries only, continent, region, and subregion.`;
/**
 * Tests recognition of countries by name on GeoPedia's global country map.
 *
 * Each question displays a country name and expects the user to select the
 * corresponding geographic country.
 */
export const countryNamesQuiz: FeatureQuiz = {
  id: "country-names",
  name: "Country Names",
  description: COUNTRY_NAMES_DESCRIPTION,

  mapId: "world-country-names",
  kind: "feature",

  answerProperty: "iso_a3",
  answerType: "single",

  grouping: {
    properties: [
      {
        property: "continent",
        label: "Continent",
        valueType: "string",
      },
      {
        property: "region",
        label: "Region",
        valueType: "string",
      },
      {
        property: "subregion",
        label: "Subregion",
        valueType: "string",
      },
    ],
  },

  questions: COUNTRY_NAME_QUESTIONS,
};
