import type { FeatureQuiz } from "@/types/quiz";

import { COSTA_RICA_CANTON_NAMES_BY_ID } from "./cantonsQuiz";
import { COSTA_RICA_PROVINCE_NAMES_BY_ID } from "./provincesQuiz";

/**
 * Costa Rica's districts, with duplicate names disambiguated by canton.
 */
const COSTA_RICA_DISTRICT_QUESTIONS = [
  { answer: "10101", display: "Carmen (San José)" },
  { answer: "10102", display: "Merced" },
  { answer: "10103", display: "Hospital" },
  { answer: "10104", display: "Catedral" },
  { answer: "10105", display: "Zapote (San José)" },
  { answer: "10106", display: "San Francisco de Dos Ríos" },
  { answer: "10107", display: "Uruca (San José)" },
  { answer: "10108", display: "Mata Redonda" },
  { answer: "10109", display: "Pavas" },
  { answer: "10110", display: "Hatillo" },
  { answer: "10111", display: "San Sebastián" },
  { answer: "10201", display: "Escazú" },
  { answer: "10202", display: "San Antonio (Escazú)" },
  { answer: "10203", display: "San Rafael (Escazú)" },
  { answer: "10301", display: "Desamparados (Desamparados)" },
  { answer: "10302", display: "San Miguel (Desamparados)" },
  { answer: "10303", display: "San Juan de Dios" },
  { answer: "10304", display: "San Rafael Arriba" },
  { answer: "10305", display: "San Antonio (Desamparados)" },
  { answer: "10306", display: "Frailes" },
  { answer: "10307", display: "Patarrá" },
  { answer: "10308", display: "San Cristobal" },
  { answer: "10309", display: "Rosario" },
  { answer: "10310", display: "Damas" },
  { answer: "10311", display: "San Rafael Abajo" },
  { answer: "10312", display: "Gravilias" },
  { answer: "10313", display: "Los Guido" },
  { answer: "10401", display: "Santiago (Puriscal)" },
  { answer: "10402", display: "Mercedes Sur" },
  { answer: "10403", display: "Barbacoas" },
  { answer: "10404", display: "Grifo Alto" },
  { answer: "10405", display: "San Antonio (Puriscal)" },
  { answer: "10406", display: "Candelarita" },
  { answer: "10407", display: "Desamparaditos" },
  { answer: "10408", display: "San Rafael (Puriscal)" },
  { answer: "10409", display: "Chires" },
  { answer: "10501", display: "San Marcos" },
  { answer: "10502", display: "San Lorenzo (Tarrazú)" },
  { answer: "10503", display: "San Carlos" },
  { answer: "10601", display: "Aserrí" },
  { answer: "10602", display: "Tarbaca" },
  { answer: "10603", display: "Vuelta de Jorco" },
  { answer: "10604", display: "San Gabriel" },
  { answer: "10605", display: "Legua" },
  { answer: "10606", display: "Monterrey (Aserrí)" },
  { answer: "10607", display: "Salitrillos" },
  { answer: "10701", display: "Colón" },
  { answer: "10702", display: "Guayabo" },
  { answer: "10703", display: "Tabarcia" },
  { answer: "10704", display: "Piedras Negras" },
  { answer: "10705", display: "Picagres" },
  { answer: "10706", display: "Jaris" },
  { answer: "10707", display: "Quitirrisí" },
  { answer: "10801", display: "Guadalupe (Goicoechea)" },
  { answer: "10802", display: "San Francisco (Goicoechea)" },
  { answer: "10803", display: "Calle Blancos" },
  { answer: "10804", display: "Mata de Plátano" },
  { answer: "10805", display: "Ipís" },
  { answer: "10806", display: "Rancho Redondo" },
  { answer: "10807", display: "Purral" },
  { answer: "10901", display: "Santa Ana" },
  { answer: "10902", display: "Salitral" },
  { answer: "10903", display: "Pozos" },
  { answer: "10904", display: "Uruca (Santa Ana)" },
  { answer: "10905", display: "Piedades" },
  { answer: "10906", display: "Brasil" },
  { answer: "11001", display: "Alajuelita" },
  { answer: "11002", display: "San Josecito (Alajuelita)" },
  { answer: "11003", display: "San Antonio (Alajuelita)" },
  { answer: "11004", display: "Concepción (Alajuelita)" },
  { answer: "11005", display: "San Felipe" },
  { answer: "11101", display: "San Isidro (Vázquez de Coronado)" },
  { answer: "11102", display: "San Rafael (Vázquez de Coronado)" },
  { answer: "11103", display: "Dulce Nombre de Jesús" },
  { answer: "11104", display: "Patalillo" },
  { answer: "11105", display: "Cascajal" },
  { answer: "11201", display: "San Ignacio" },
  { answer: "11202", display: "Guaitil" },
  { answer: "11203", display: "Palmichal" },
  { answer: "11204", display: "Cangrejal" },
  { answer: "11205", display: "Sabanillas" },
  { answer: "11301", display: "San Juan (Tibás)" },
  { answer: "11302", display: "Cinco Esquinas" },
  { answer: "11303", display: "Anselmo Llorente" },
  { answer: "11304", display: "León XIII" },
  { answer: "11305", display: "Colima" },
  { answer: "11401", display: "San Vicente (Moravia)" },
  { answer: "11402", display: "San Jerónimo (Moravia)" },
  { answer: "11403", display: "La Trinidad" },
  { answer: "11501", display: "San Pedro (Montes de Oca)" },
  { answer: "11502", display: "Sabanilla (Montes de Oca)" },
  { answer: "11503", display: "Mercedes (Montes de Oca)" },
  { answer: "11504", display: "San Rafael (Montes de Oca)" },
  { answer: "11601", display: "San Pablo (Turrubares)" },
  { answer: "11602", display: "San Pedro (Turrubares)" },
  { answer: "11603", display: "San Juan de Mata" },
  { answer: "11604", display: "San Luis" },
  { answer: "11605", display: "Carara" },
  { answer: "11701", display: "Santa María" },
  { answer: "11702", display: "Jardín" },
  { answer: "11703", display: "Copey" },
  { answer: "11801", display: "Curridabat" },
  { answer: "11802", display: "Granadilla" },
  { answer: "11803", display: "Sánchez" },
  { answer: "11804", display: "Tirrases" },
  { answer: "11901", display: "San Isidro de El General" },
  { answer: "11902", display: "El General" },
  { answer: "11903", display: "Daniel Flores" },
  { answer: "11904", display: "Rivas" },
  { answer: "11905", display: "San Pedro (Pérez Zeledón)" },
  { answer: "11906", display: "Platanares" },
  { answer: "11907", display: "Pejibaye (Pérez Zeledón)" },
  { answer: "11908", display: "Cajón" },
  { answer: "11909", display: "Barú" },
  { answer: "11910", display: "Río Nuevo" },
  { answer: "11911", display: "Páramo" },
  { answer: "11912", display: "La Amistad" },
  { answer: "12001", display: "San Pablo (León Cortés Castro)" },
  { answer: "12002", display: "San Andrés" },
  { answer: "12003", display: "Llano Bonito" },
  { answer: "12004", display: "San Isidro (León Cortés Castro)" },
  { answer: "12005", display: "Santa Cruz (León Cortés Castro)" },
  { answer: "12006", display: "San Antonio (León Cortés Castro)" },
  { answer: "20101", display: "Alajuela" },
  { answer: "20102", display: "San José (Alajuela)" },
  { answer: "20103", display: "Carrizal" },
  { answer: "20104", display: "San Antonio (Alajuela)" },
  { answer: "20105", display: "Guácima" },
  { answer: "20106", display: "San Isidro (Alajuela)" },
  { answer: "20107", display: "Sabanilla (Alajuela)" },
  { answer: "20108", display: "San Rafael (Alajuela)" },
  { answer: "20109", display: "Río Segundo" },
  { answer: "20110", display: "Desamparados (Alajuela)" },
  { answer: "20111", display: "Turrúcares" },
  { answer: "20112", display: "Tambor" },
  { answer: "20113", display: "Garita" },
  { answer: "20114", display: "Sarapiquí" },
  { answer: "20201", display: "San Ramón (San Ramón)" },
  { answer: "20202", display: "Santiago (San Ramón)" },
  { answer: "20203", display: "San Juan (San Ramón)" },
  { answer: "20204", display: "Piedades Norte" },
  { answer: "20205", display: "Piedades Sur" },
  { answer: "20206", display: "San Rafael (San Ramón)" },
  { answer: "20207", display: "San Isidro (San Ramón)" },
  { answer: "20208", display: "Ángeles (San Ramón)" },
  { answer: "20209", display: "Alfaro" },
  { answer: "20210", display: "Volio" },
  { answer: "20211", display: "Concepción (San Ramón)" },
  { answer: "20212", display: "Zapotal (San Ramón)" },
  { answer: "20213", display: "Peñas Blancas" },
  { answer: "20214", display: "San Lorenzo (San Ramón)" },
  { answer: "20301", display: "Grecia" },
  { answer: "20302", display: "San Isidro (Grecia)" },
  { answer: "20303", display: "San José (Grecia)" },
  { answer: "20304", display: "San Roque (Grecia)" },
  { answer: "20305", display: "Tacares" },
  { answer: "20307", display: "Puente de Piedra" },
  { answer: "20308", display: "Bolivar" },
  { answer: "20401", display: "San Mateo" },
  { answer: "20402", display: "Desmonte" },
  { answer: "20403", display: "Jesús María" },
  { answer: "20404", display: "Labrador" },
  { answer: "20501", display: "Atenas" },
  { answer: "20502", display: "Jesús (Atenas)" },
  { answer: "20503", display: "Mercedes (Atenas)" },
  { answer: "20504", display: "San Isidro (Atenas)" },
  { answer: "20505", display: "Concepción (Atenas)" },
  { answer: "20506", display: "San José (Atenas)" },
  { answer: "20507", display: "Santa Eulalia" },
  { answer: "20508", display: "Escobal" },
  { answer: "20601", display: "Naranjo" },
  { answer: "20602", display: "San Miguel (Naranjo)" },
  { answer: "20603", display: "San José (Naranjo)" },
  { answer: "20604", display: "Cirrí Sur" },
  { answer: "20605", display: "San Jerónimo (Naranjo)" },
  { answer: "20606", display: "San Juan (Naranjo)" },
  { answer: "20607", display: "El Rosario" },
  { answer: "20608", display: "Palmitos" },
  { answer: "20701", display: "Palmares" },
  { answer: "20702", display: "Zaragoza" },
  { answer: "20703", display: "Buenos Aires (Palmares)" },
  { answer: "20704", display: "Santiago (Palmares)" },
  { answer: "20705", display: "Candelaria" },
  { answer: "20706", display: "Esquipulas" },
  { answer: "20707", display: "La Granja" },
  { answer: "20801", display: "San Pedro (Poás)" },
  { answer: "20802", display: "San Juan (Poás)" },
  { answer: "20803", display: "San Rafael (Poás)" },
  { answer: "20804", display: "Carrillos" },
  { answer: "20805", display: "Sabana Redonda" },
  { answer: "20901", display: "Orotina" },
  { answer: "20902", display: "El Mastate" },
  { answer: "20903", display: "Hacienda Vieja" },
  { answer: "20904", display: "Coyolar" },
  { answer: "20905", display: "La Ceiba" },
  { answer: "21001", display: "Quesada" },
  { answer: "21002", display: "Florencia" },
  { answer: "21003", display: "Buenavista (San Carlos)" },
  { answer: "21004", display: "Aguas Zarcas" },
  { answer: "21005", display: "Venecia" },
  { answer: "21006", display: "Pital" },
  { answer: "21007", display: "La Fortuna (San Carlos)" },
  { answer: "21008", display: "La Tigra" },
  { answer: "21009", display: "La Palmera" },
  { answer: "21010", display: "Venado" },
  { answer: "21011", display: "Cutris" },
  { answer: "21012", display: "Monterrey (San Carlos)" },
  { answer: "21013", display: "Pocosol" },
  { answer: "21101", display: "Zarcero" },
  { answer: "21102", display: "Laguna" },
  { answer: "21103", display: "Tapesco" },
  { answer: "21104", display: "Guadalupe (Zarcero)" },
  { answer: "21105", display: "Palmira (Zarcero)" },
  { answer: "21106", display: "Zapote (Zarcero)" },
  { answer: "21107", display: "Brisas" },
  { answer: "21201", display: "Sarchí Norte" },
  { answer: "21202", display: "Sarchí Sur" },
  { answer: "21203", display: "Toro Amarillo" },
  { answer: "21204", display: "San Pedro (Sarchí)" },
  { answer: "21205", display: "Rodríguez" },
  { answer: "21301", display: "Upala" },
  { answer: "21302", display: "Aguas Claras" },
  { answer: "21303", display: "San José O Pizote" },
  { answer: "21304", display: "Bijagua" },
  { answer: "21305", display: "Delicias" },
  { answer: "21306", display: "Dos Ríos" },
  { answer: "21307", display: "Yolillal" },
  { answer: "21308", display: "Canalete" },
  { answer: "21401", display: "Los Chiles" },
  { answer: "21402", display: "Caño Negro" },
  { answer: "21403", display: "El Amparo" },
  { answer: "21404", display: "San Jorge" },
  { answer: "21501", display: "San Rafael (Guatuso)" },
  { answer: "21502", display: "Buenavista (Guatuso)" },
  { answer: "21503", display: "Cote" },
  { answer: "21504", display: "Katira" },
  { answer: "21601", display: "Río Cuarto" },
  { answer: "21602", display: "Santa Rita (Río Cuarto)" },
  { answer: "21603", display: "Santa Isabel" },
  { answer: "30101", display: "Oriental" },
  { answer: "30102", display: "Occidental" },
  { answer: "30103", display: "Carmen (Cartago)" },
  { answer: "30104", display: "San Nicolás" },
  { answer: "30105", display: "Aguacaliente o San Francisco" },
  { answer: "30106", display: "Guadalupe o Arenilla" },
  { answer: "30107", display: "Corralillo" },
  { answer: "30108", display: "Tierra Blanca" },
  { answer: "30109", display: "Dulce Nombre (Cartago)" },
  { answer: "30110", display: "Llano Grande" },
  { answer: "30111", display: "Quebradilla" },
  { answer: "30201", display: "Paraíso" },
  { answer: "30202", display: "Santiago (Paraíso)" },
  { answer: "30203", display: "Orosi" },
  { answer: "30204", display: "Cachí" },
  { answer: "30205", display: "Llanos de Santa Lucía" },
  { answer: "30206", display: "Birrisito" },
  { answer: "30301", display: "Tres Ríos" },
  { answer: "30302", display: "San Diego" },
  { answer: "30303", display: "San Juan (La Unión)" },
  { answer: "30304", display: "San Rafael (La Unión)" },
  { answer: "30305", display: "Concepción (La Unión)" },
  { answer: "30306", display: "Dulce Nombre (La Unión)" },
  { answer: "30307", display: "San Ramón (La Unión)" },
  { answer: "30308", display: "Río Azul" },
  { answer: "30401", display: "Juan Viñas" },
  { answer: "30402", display: "Tucurrique" },
  { answer: "30403", display: "Pejibaye (Jiménez)" },
  { answer: "30404", display: "La Victoria" },
  { answer: "30501", display: "Turrialba" },
  { answer: "30502", display: "La Suiza" },
  { answer: "30503", display: "Peralta" },
  { answer: "30504", display: "Santa Cruz (Turrialba)" },
  { answer: "30505", display: "Santa Teresita" },
  { answer: "30506", display: "Pavones" },
  { answer: "30507", display: "Tuis" },
  { answer: "30508", display: "Tayutic" },
  { answer: "30509", display: "Santa Rosa (Turrialba)" },
  { answer: "30510", display: "Tres Equis" },
  { answer: "30511", display: "La Isabel" },
  { answer: "30512", display: "Chirripó" },
  { answer: "30601", display: "Pacayas" },
  { answer: "30602", display: "Cervantes" },
  { answer: "30603", display: "Capellades" },
  { answer: "30701", display: "San Rafael (Oreamuno)" },
  { answer: "30702", display: "Cot" },
  { answer: "30703", display: "Potrero Cerrado" },
  { answer: "30704", display: "Cipreses" },
  { answer: "30705", display: "Santa Rosa (Oreamuno)" },
  { answer: "30801", display: "El Tejar" },
  { answer: "30802", display: "San Isidro (El Guarco)" },
  { answer: "30803", display: "Tobosi" },
  { answer: "30804", display: "Patio de Agua" },
  { answer: "40101", display: "Heredia" },
  { answer: "40102", display: "Mercedes (Heredia)" },
  { answer: "40103", display: "San Francisco (Heredia)" },
  { answer: "40104", display: "Ulloa" },
  { answer: "40105", display: "Varablanca" },
  { answer: "40201", display: "Barva" },
  { answer: "40202", display: "San Pedro (Barva)" },
  { answer: "40203", display: "San Pablo (Barva)" },
  { answer: "40204", display: "San Roque (Barva)" },
  { answer: "40205", display: "Santa Lucía" },
  { answer: "40206", display: "San José de la Montaña" },
  { answer: "40207", display: "Puente Salas" },
  { answer: "40301", display: "Santo Domingo (Santo Domingo)" },
  { answer: "40302", display: "San Vicente (Santo Domingo)" },
  { answer: "40303", display: "San Miguel (Santo Domingo)" },
  { answer: "40304", display: "Paracito" },
  { answer: "40305", display: "Santo Tomás" },
  { answer: "40306", display: "Santa Rosa (Santo Domingo)" },
  { answer: "40307", display: "Tures" },
  { answer: "40308", display: "Pará" },
  { answer: "40401", display: "Santa Bárbara" },
  { answer: "40402", display: "San Pedro (Santa Bárbara)" },
  { answer: "40403", display: "San Juan (Santa Bárbara)" },
  { answer: "40404", display: "Jesús (Santa Bárbara)" },
  { answer: "40405", display: "Santo Domingo (Santa Bárbara)" },
  { answer: "40406", display: "Purabá" },
  { answer: "40501", display: "San Rafael (San Rafael)" },
  { answer: "40502", display: "San Josecito (San Rafael)" },
  { answer: "40503", display: "Santiago (San Rafael)" },
  { answer: "40504", display: "Ángeles (San Rafael)" },
  { answer: "40505", display: "Concepción (San Rafael)" },
  { answer: "40601", display: "San Isidro (San Isidro)" },
  { answer: "40602", display: "San José (San Isidro)" },
  { answer: "40603", display: "Concepción (San Isidro)" },
  { answer: "40604", display: "San Francisco (San Isidro)" },
  { answer: "40701", display: "San Antonio (Belén)" },
  { answer: "40702", display: "La Ribera" },
  { answer: "40703", display: "La Asunción" },
  { answer: "40801", display: "San Joaquín" },
  { answer: "40802", display: "Barrantes" },
  { answer: "40803", display: "Llorente" },
  { answer: "40901", display: "San Pablo (San Pablo)" },
  { answer: "40902", display: "Rincón de Sabanilla" },
  { answer: "41001", display: "Puerto Viejo" },
  { answer: "41002", display: "La Virgen" },
  { answer: "41003", display: "Las Horquetas" },
  { answer: "41004", display: "Llanuras del Gaspar" },
  { answer: "41005", display: "Cureña" },
  { answer: "50101", display: "Liberia" },
  { answer: "50102", display: "Cañas Dulces" },
  { answer: "50103", display: "Mayorga" },
  { answer: "50104", display: "Nacascolo" },
  { answer: "50105", display: "Curubandé" },
  { answer: "50201", display: "Nicoya" },
  { answer: "50202", display: "Mansión" },
  { answer: "50203", display: "San Antonio (Nicoya)" },
  { answer: "50204", display: "Quebrada Honda" },
  { answer: "50205", display: "Sámara" },
  { answer: "50206", display: "Nosara" },
  { answer: "50207", display: "Belén de Nosarita" },
  { answer: "50301", display: "Santa Cruz (Santa Cruz)" },
  { answer: "50302", display: "Bolsón" },
  { answer: "50303", display: "Veintisiete de Abril" },
  { answer: "50304", display: "Tempate" },
  { answer: "50305", display: "Cartagena" },
  { answer: "50306", display: "Cuajiniquil" },
  { answer: "50307", display: "Diriá" },
  { answer: "50308", display: "Cabo Velas" },
  { answer: "50309", display: "Tamarindo" },
  { answer: "50401", display: "Bagaces" },
  { answer: "50402", display: "La Fortuna (Bagaces)" },
  { answer: "50403", display: "Mogote" },
  { answer: "50404", display: "Río Naranjo" },
  { answer: "50501", display: "Filadelfia" },
  { answer: "50502", display: "Palmira (Carrillo)" },
  { answer: "50503", display: "Sardinal" },
  { answer: "50504", display: "Belén" },
  { answer: "50601", display: "Cañas" },
  { answer: "50602", display: "Palmira (Cañas)" },
  { answer: "50603", display: "San Miguel (Cañas)" },
  { answer: "50604", display: "Bebedero" },
  { answer: "50605", display: "Porozal" },
  { answer: "50701", display: "Las Juntas" },
  { answer: "50702", display: "Sierra" },
  { answer: "50703", display: "San Juan (Abangares)" },
  { answer: "50704", display: "Colorado (Abangares)" },
  { answer: "50801", display: "Tilarán" },
  { answer: "50802", display: "Quebrada Grande" },
  { answer: "50803", display: "Tronadora" },
  { answer: "50804", display: "Santa Rosa (Tilarán)" },
  { answer: "50805", display: "Líbano" },
  { answer: "50806", display: "Tierras Morenas" },
  { answer: "50807", display: "Arenal" },
  { answer: "50808", display: "Cabeceras" },
  { answer: "50901", display: "Carmona" },
  { answer: "50902", display: "Santa Rita (Nandayure)" },
  { answer: "50903", display: "Zapotal (Nandayure)" },
  { answer: "50904", display: "San Pablo (Nandayure)" },
  { answer: "50905", display: "Porvenir" },
  { answer: "50906", display: "Bejuco" },
  { answer: "51001", display: "La Cruz" },
  { answer: "51002", display: "Santa Cecilia" },
  { answer: "51003", display: "La Garita" },
  { answer: "51004", display: "Santa Elena" },
  { answer: "51101", display: "Hojancha" },
  { answer: "51102", display: "Monte Romo" },
  { answer: "51103", display: "Puerto Carrillo" },
  { answer: "51104", display: "Huacas" },
  { answer: "51105", display: "Matambú" },
  { answer: "60101", display: "Puntarenas" },
  { answer: "60102", display: "Pitahaya" },
  { answer: "60103", display: "Chomes" },
  { answer: "60104", display: "Lepanto" },
  { answer: "60105", display: "Paquera" },
  { answer: "60106", display: "Manzanillo" },
  { answer: "60107", display: "Guacimal" },
  { answer: "60108", display: "Barranca" },
  { answer: "60110", display: "Isla del Coco" },
  { answer: "60111", display: "Cóbano" },
  { answer: "60112", display: "Chacarita" },
  { answer: "60113", display: "Chira" },
  { answer: "60114", display: "Acapulco" },
  { answer: "60115", display: "El Roble" },
  { answer: "60116", display: "Arancibia" },
  { answer: "60201", display: "Espíritu Santo" },
  { answer: "60202", display: "San Juan Grande" },
  { answer: "60203", display: "Macacona" },
  { answer: "60204", display: "San Rafael (Esparza)" },
  { answer: "60205", display: "San Jerónimo (Esparza)" },
  { answer: "60206", display: "Caldera" },
  { answer: "60301", display: "Buenos Aires (Buenos Aires)" },
  { answer: "60302", display: "Volcán" },
  { answer: "60303", display: "Potrero Grande" },
  { answer: "60304", display: "Boruca" },
  { answer: "60305", display: "Pilas" },
  { answer: "60306", display: "Colinas" },
  { answer: "60307", display: "Chánguena" },
  { answer: "60308", display: "Biolley" },
  { answer: "60309", display: "Brunka" },
  { answer: "60401", display: "Miramar" },
  { answer: "60402", display: "La Unión" },
  { answer: "60403", display: "San Isidro (Montes de Oro)" },
  { answer: "60501", display: "Puerto Cortés" },
  { answer: "60502", display: "Palmar" },
  { answer: "60503", display: "Sierpe" },
  { answer: "60504", display: "Bahía Ballena" },
  { answer: "60505", display: "Piedras Blancas" },
  { answer: "60506", display: "Bahía Drake" },
  { answer: "60601", display: "Quepos" },
  { answer: "60602", display: "Savegre" },
  { answer: "60603", display: "Naranjito" },
  { answer: "60701", display: "Golfito" },
  { answer: "60703", display: "Guaycará" },
  { answer: "60704", display: "Pavón" },
  { answer: "60801", display: "San Vito" },
  { answer: "60802", display: "Sabalito" },
  { answer: "60803", display: "Aguabuena" },
  { answer: "60804", display: "Limoncito" },
  { answer: "60805", display: "Pittier" },
  { answer: "60806", display: "Gutiérrez Braun" },
  { answer: "60901", display: "Parrita" },
  { answer: "61001", display: "Corredor" },
  { answer: "61002", display: "La Cuesta" },
  { answer: "61003", display: "Canoas" },
  { answer: "61004", display: "Laurel" },
  { answer: "61101", display: "Jacó" },
  { answer: "61102", display: "Tárcoles" },
  { answer: "61103", display: "Lagunillas" },
  { answer: "61201", display: "Monteverde" },
  { answer: "61301", display: "Puerto Jiménez" },
  { answer: "70101", display: "Limón" },
  { answer: "70102", display: "Valle La Estrella" },
  { answer: "70103", display: "Río Blanco" },
  { answer: "70104", display: "Matama" },
  { answer: "70201", display: "Guápiles" },
  { answer: "70202", display: "Jiménez" },
  { answer: "70203", display: "Rita" },
  { answer: "70204", display: "Roxana" },
  { answer: "70205", display: "Cariari" },
  { answer: "70206", display: "Colorado (Pococí)" },
  { answer: "70207", display: "La Colonia" },
  { answer: "70301", display: "Siquirres" },
  { answer: "70302", display: "Pacuarito" },
  { answer: "70303", display: "Florida" },
  { answer: "70304", display: "Germania" },
  { answer: "70305", display: "El Cairo" },
  { answer: "70306", display: "Alegría" },
  { answer: "70307", display: "Reventazón" },
  { answer: "70401", display: "Bratsi" },
  { answer: "70402", display: "Sixaola" },
  { answer: "70403", display: "Cahuita" },
  { answer: "70404", display: "Telire" },
  { answer: "70501", display: "Matina" },
  { answer: "70502", display: "Batán" },
  { answer: "70503", display: "Carrandí" },
  { answer: "70601", display: "Guácimo" },
  { answer: "70602", display: "Mercedes (Guácimo)" },
  { answer: "70603", display: "Pocora" },
  { answer: "70604", display: "Río Jiménez" },
  { answer: "70605", display: "Duacarí" },
] as const;

/**
 * User-facing description for Costa Rica's districts quiz.
 */
const COSTA_RICA_DISTRICTS_DESCRIPTION =
  `Learn all ${COSTA_RICA_DISTRICT_QUESTIONS.length} districts of Costa Rica. ` +
  `Filters let you practice districts by province or canton.`;

/**
 * District quiz for Costa Rica.
 */
export const costaRicaDistrictsQuiz: FeatureQuiz = {
  id: "costa-rica-districts",
  name: "Districts",
  description: COSTA_RICA_DISTRICTS_DESCRIPTION,

  kind: "feature",
  mapId: "costa-rica-districts",

  answerProperty: "district_id",
  answerType: "single",

  grouping: {
    properties: [
      {
        property: "province_id",
        label: "Province",
        valueType: "string",
        valueLabels: COSTA_RICA_PROVINCE_NAMES_BY_ID,
      },
      {
        property: "canton_id",
        label: "Canton",
        valueType: "string",
        valueLabels: COSTA_RICA_CANTON_NAMES_BY_ID,
      },
    ],
  },

  questions: [...COSTA_RICA_DISTRICT_QUESTIONS],
};
