/**
 * Defines country-specific map presentation and scoring configuration for
 * GeoPedia's town quizzes.
 *
 * This file is generated by:
 *
 * scripts/generate/world/generateTownCountryConfigs.ts
 *
 * Do not manually edit generated values here. Adjust the generator or its
 * country-specific overrides and regenerate instead.
 */

export type TownCountryConfig = {
  initialView: {
    center: [number, number];
    zoom: number;
  };

  maxErrorKm: number;
};

const townCountryConfigs: Record<string, TownCountryConfig> = {
  "abw": {
    initialView: {
      center: [-69.9671, 12.4801],
      zoom: 12.29,
    },
    maxErrorKm: 11,
  },
  "afg": {
    initialView: {
      center: [66.7789, 34.5128],
      zoom: 5.97,
    },
    maxErrorKm: 329,
  },
  "ago": {
    initialView: {
      center: [16.1463, -11.5619],
      zoom: 5.32,
    },
    maxErrorKm: 435,
  },
  "aia": {
    initialView: {
      center: [-63.0578, 18.217],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "ala": {
    initialView: {
      center: [20.3299, 60.2128],
      zoom: 8.88,
    },
    maxErrorKm: 26,
  },
  "alb": {
    initialView: {
      center: [20.2223, 41.0097],
      zoom: 7.33,
    },
    maxErrorKm: 82,
  },
  "and": {
    initialView: {
      center: [1.5444, 42.5157],
      zoom: 11.64,
    },
    maxErrorKm: 5,
  },
  "are": {
    initialView: {
      center: [55.3798, 24.8907],
      zoom: 7.49,
    },
    maxErrorKm: 82,
  },
  "arg": {
    initialView: {
      center: [-62.2719, -34.1328],
      zoom: 4.42,
    },
    maxErrorKm: 638,
  },
  "arm": {
    initialView: {
      center: [45.0019, 40.3497],
      zoom: 7.68,
    },
    maxErrorKm: 81,
  },
  "asm": {
    initialView: {
      center: [-170.72, -14.3358],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "ata": {
    initialView: {
      center: [166.7527, -77.8411],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "atf": {
    initialView: {
      center: [70.2194, -49.3492],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "atg": {
    initialView: {
      center: [-61.789, 17.3279],
      zoom: 9.43,
    },
    maxErrorKm: 10,
  },
  "aus": {
    initialView: {
      center: [143.748, -29.9015],
      zoom: 3.89,
    },
    maxErrorKm: 804,
  },
  "aut": {
    initialView: {
      center: [14.2679, 47.6968],
      zoom: 6.98,
    },
    maxErrorKm: 146,
  },
  "aze": {
    initialView: {
      center: [47.1303, 40.2501],
      zoom: 6.86,
    },
    maxErrorKm: 164,
  },
  "bdi": {
    initialView: {
      center: [29.8629, -3.4294],
      zoom: 8.05,
    },
    maxErrorKm: 84,
  },
  "bel": {
    initialView: {
      center: [4.3977, 50.8272],
      zoom: 7.95,
    },
    maxErrorKm: 61,
  },
  "ben": {
    initialView: {
      center: [2.1917, 8.536],
      zoom: 6.6,
    },
    maxErrorKm: 166,
  },
  "bes": {
    initialView: {
      center: [-65.6585, 14.8165],
      zoom: 6.35,
    },
    maxErrorKm: 818,
  },
  "bfa": {
    initialView: {
      center: [-1.8822, 12.1631],
      zoom: 6.59,
    },
    maxErrorKm: 197,
  },
  "bgd": {
    initialView: {
      center: [90.1879, 23.9115],
      zoom: 6.81,
    },
    maxErrorKm: 172,
  },
  "bgr": {
    initialView: {
      center: [25.1938, 42.7143],
      zoom: 6.95,
    },
    maxErrorKm: 158,
  },
  "bhr": {
    initialView: {
      center: [50.5703, 26.1524],
      zoom: 10.91,
    },
    maxErrorKm: 11,
  },
  "bhs": {
    initialView: {
      center: [-76.5877, 24.6211],
      zoom: 6.63,
    },
    maxErrorKm: 197,
  },
  "bih": {
    initialView: {
      center: [17.8655, 44.0639],
      zoom: 7.18,
    },
    maxErrorKm: 104,
  },
  "blm": {
    initialView: {
      center: [-62.8498, 17.8962],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "blr": {
    initialView: {
      center: [27.6148, 53.906],
      zoom: 5.97,
    },
    maxErrorKm: 204,
  },
  "blz": {
    initialView: {
      center: [-88.5525, 17.1482],
      zoom: 7.68,
    },
    maxErrorKm: 93,
  },
  "bmu": {
    initialView: {
      center: [-64.7305, 32.3383],
      zoom: 12.1,
    },
    maxErrorKm: 14,
  },
  "bol": {
    initialView: {
      center: [-65.022, -18.2381],
      zoom: 5.57,
    },
    maxErrorKm: 335,
  },
  "bra": {
    initialView: {
      center: [-45.4939, -18.4469],
      zoom: 3.96,
    },
    maxErrorKm: 846,
  },
  "brb": {
    initialView: {
      center: [-59.5605, 13.1607],
      zoom: 11.25,
    },
    maxErrorKm: 16,
  },
  "brn": {
    initialView: {
      center: [114.6514, 4.8053],
      zoom: 9.65,
    },
    maxErrorKm: 40,
  },
  "btn": {
    initialView: {
      center: [90.4713, 27.3435],
      zoom: 8.28,
    },
    maxErrorKm: 97,
  },
  "bwa": {
    initialView: {
      center: [24.7444, -22.6038],
      zoom: 6.31,
    },
    maxErrorKm: 273,
  },
  "caf": {
    initialView: {
      center: [18.8232, 5.6579],
      zoom: 6.35,
    },
    maxErrorKm: 335,
  },
  "can": {
    initialView: {
      center: [-87.7669, 52.2521],
      zoom: 3.27,
    },
    maxErrorKm: 830,
  },
  "che": {
    initialView: {
      center: [8.1679, 46.8586],
      zoom: 7.52,
    },
    maxErrorKm: 84,
  },
  "chl": {
    initialView: {
      center: [-72.0394, -35.2923],
      zoom: 4.54,
    },
    maxErrorKm: 362,
  },
  "chn": {
    initialView: {
      center: [114.1158, 31.7128],
      zoom: 4.23,
    },
    maxErrorKm: 924,
  },
  "civ": {
    initialView: {
      center: [-5.7126, 7.0079],
      zoom: 6.43,
    },
    maxErrorKm: 240,
  },
  "cmr": {
    initialView: {
      center: [12.1146, 6.075],
      zoom: 5.86,
    },
    maxErrorKm: 269,
  },
  "cod": {
    initialView: {
      center: [22.6805, -3.741],
      zoom: 4.8,
    },
    maxErrorKm: 895,
  },
  "cog": {
    initialView: {
      center: [14.658, -1.4607],
      zoom: 6,
    },
    maxErrorKm: 323,
  },
  "cok": {
    initialView: {
      center: [-159.7544, -21.216],
      zoom: 13.97,
    },
    maxErrorKm: 5,
  },
  "col": {
    initialView: {
      center: [-74.4344, 6.3113],
      zoom: 5.57,
    },
    maxErrorKm: 360,
  },
  "com": {
    initialView: {
      center: [43.9049, -12.0867],
      zoom: 9.08,
    },
    maxErrorKm: 71,
  },
  "cpv": {
    initialView: {
      center: [-23.985, 16.0269],
      zoom: 7.55,
    },
    maxErrorKm: 168,
  },
  "cri": {
    initialView: {
      center: [-84.2434, 9.9971],
      zoom: 7.74,
    },
    maxErrorKm: 71,
  },
  "cub": {
    initialView: {
      center: [-80.2067, 21.5369],
      zoom: 6.37,
    },
    maxErrorKm: 254,
  },
  "cuw": {
    initialView: {
      center: [-68.8864, 12.1225],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "cym": {
    initialView: {
      center: [-80.6372, 19.4842],
      zoom: 8.8,
    },
    maxErrorKm: 85,
  },
  "cyp": {
    initialView: {
      center: [33.2412, 34.9979],
      zoom: 8.69,
    },
    maxErrorKm: 56,
  },
  "cze": {
    initialView: {
      center: [15.3561, 49.8452],
      zoom: 6.95,
    },
    maxErrorKm: 141,
  },
  "deu": {
    initialView: {
      center: [9.5745, 51.1586],
      zoom: 5.48,
    },
    maxErrorKm: 233,
  },
  "dji": {
    initialView: {
      center: [42.829, 11.6274],
      zoom: 8.72,
    },
    maxErrorKm: 60,
  },
  "dma": {
    initialView: {
      center: [-61.3894, 15.4081],
      zoom: 10.28,
    },
    maxErrorKm: 17,
  },
  "dnk": {
    initialView: {
      center: [10.562, 55.9139],
      zoom: 6.78,
    },
    maxErrorKm: 130,
  },
  "dom": {
    initialView: {
      center: [-70.62, 18.8746],
      zoom: 7.71,
    },
    maxErrorKm: 111,
  },
  "dza": {
    initialView: {
      center: [3.9037, 34.6362],
      zoom: 6.22,
    },
    maxErrorKm: 287,
  },
  "ecu": {
    initialView: {
      center: [-79.3796, -1.8588],
      zoom: 6.51,
    },
    maxErrorKm: 190,
  },
  "egy": {
    initialView: {
      center: [31.0665, 28.8159],
      zoom: 6.15,
    },
    maxErrorKm: 235,
  },
  "eri": {
    initialView: {
      center: [38.6388, 15.4579],
      zoom: 8.21,
    },
    maxErrorKm: 106,
  },
  "esh": {
    initialView: {
      center: [-12.7674, 24.3627],
      zoom: 6.2,
    },
    maxErrorKm: 458,
  },
  "esp": {
    initialView: {
      center: [-3.0195, 39.722],
      zoom: 5.49,
    },
    maxErrorKm: 435,
  },
  "est": {
    initialView: {
      center: [25.6523, 58.6771],
      zoom: 7.02,
    },
    maxErrorKm: 110,
  },
  "eth": {
    initialView: {
      center: [39.0453, 8.9997],
      zoom: 5.49,
    },
    maxErrorKm: 358,
  },
  "fin": {
    initialView: {
      center: [25.7456, 62.299],
      zoom: 5.4,
    },
    maxErrorKm: 217,
  },
  "fji": {
    initialView: {
      center: [178.3759, -17.5011],
      zoom: 8.22,
    },
    maxErrorKm: 94,
  },
  "flk": {
    initialView: {
      center: [-57.857, -51.6938],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "fra": {
    initialView: {
      center: [1.6521, 47.1092],
      zoom: 5.28,
    },
    maxErrorKm: 339,
  },
  "fro": {
    initialView: {
      center: [-6.7015, 61.8998],
      zoom: 8.27,
    },
    maxErrorKm: 38,
  },
  "fsm": {
    initialView: {
      center: [148.1639, 6.6763],
      zoom: 5.07,
    },
    maxErrorKm: 1232,
  },
  "gab": {
    initialView: {
      center: [11.7604, -0.6402],
      zoom: 6.33,
    },
    maxErrorKm: 291,
  },
  "gbr": {
    initialView: {
      center: [-1.0958, 52.7176],
      zoom: 5.92,
    },
    maxErrorKm: 175,
  },
  "geo": {
    initialView: {
      center: [43.4599, 42.1554],
      zoom: 7.16,
    },
    maxErrorKm: 121,
  },
  "ggy": {
    initialView: {
      center: [-2.5353, 49.4598],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "gha": {
    initialView: {
      center: [-0.8417, 7.1336],
      zoom: 6.62,
    },
    maxErrorKm: 207,
  },
  "gib": {
    initialView: {
      center: [-5.3526, 36.1447],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "gin": {
    initialView: {
      center: [-11.6167, 10.5134],
      zoom: 6.81,
    },
    maxErrorKm: 250,
  },
  "glp": {
    initialView: {
      center: [-61.5705, 16.2242],
      zoom: 9.77,
    },
    maxErrorKm: 27,
  },
  "gmb": {
    initialView: {
      center: [-15.4061, 13.3928],
      zoom: 7.96,
    },
    maxErrorKm: 105,
  },
  "gnb": {
    initialView: {
      center: [-15.2125, 11.8003],
      zoom: 8.33,
    },
    maxErrorKm: 86,
  },
  "gnq": {
    initialView: {
      center: [9.9424, 2.3745],
      zoom: 7.39,
    },
    maxErrorKm: 122,
  },
  "grc": {
    initialView: {
      center: [23.3125, 38.3611],
      zoom: 5.94,
    },
    maxErrorKm: 232,
  },
  "grd": {
    initialView: {
      center: [-61.6041, 12.2679],
      zoom: 10,
    },
    maxErrorKm: 16,
  },
  "grl": {
    initialView: {
      center: [-39.0558, 66.4626],
      zoom: 3.79,
    },
    maxErrorKm: 584,
  },
  "gtm": {
    initialView: {
      center: [-90.8339, 14.8771],
      zoom: 7.83,
    },
    maxErrorKm: 97,
  },
  "guf": {
    initialView: {
      center: [-53.3049, 4.6553],
      zoom: 7.79,
    },
    maxErrorKm: 182,
  },
  "gum": {
    initialView: {
      center: [144.794, 13.4365],
      zoom: 11.39,
    },
    maxErrorKm: 13,
  },
  "guy": {
    initialView: {
      center: [-58.4653, 6.7443],
      zoom: 7.26,
    },
    maxErrorKm: 100,
  },
  "hkg": {
    initialView: {
      center: [114.1046, 22.4073],
      zoom: 10.55,
    },
    maxErrorKm: 16,
  },
  "hnd": {
    initialView: {
      center: [-87.643, 14.4904],
      zoom: 7.4,
    },
    maxErrorKm: 127,
  },
  "hrv": {
    initialView: {
      center: [16.2631, 44.9481],
      zoom: 6.67,
    },
    maxErrorKm: 175,
  },
  "hti": {
    initialView: {
      center: [-72.8071, 18.9949],
      zoom: 7.81,
    },
    maxErrorKm: 106,
  },
  "hun": {
    initialView: {
      center: [19.4738, 47.0928],
      zoom: 6.95,
    },
    maxErrorKm: 132,
  },
  "idn": {
    initialView: {
      center: [110.6106, -3.0162],
      zoom: 4.7,
    },
    maxErrorKm: 710,
  },
  "imn": {
    initialView: {
      center: [-4.5381, 54.1986],
      zoom: 10.05,
    },
    maxErrorKm: 18,
  },
  "ind": {
    initialView: {
      center: [79.2744, 20.8638],
      zoom: 4.38,
    },
    maxErrorKm: 970,
  },
  "irl": {
    initialView: {
      center: [-8.0343, 53.3412],
      zoom: 6.49,
    },
    maxErrorKm: 124,
  },
  "irn": {
    initialView: {
      center: [51.7805, 34.0741],
      zoom: 5.06,
    },
    maxErrorKm: 471,
  },
  "irq": {
    initialView: {
      center: [43.7897, 34.0129],
      zoom: 5.94,
    },
    maxErrorKm: 272,
  },
  "isl": {
    initialView: {
      center: [-19.1071, 64.801],
      zoom: 6.11,
    },
    maxErrorKm: 196,
  },
  "isr": {
    initialView: {
      center: [35.0582, 32.1996],
      zoom: 7.77,
    },
    maxErrorKm: 58,
  },
  "ita": {
    initialView: {
      center: [12.7254, 42.323],
      zoom: 5.26,
    },
    maxErrorKm: 352,
  },
  "jam": {
    initialView: {
      center: [-77.4908, 18.1814],
      zoom: 8.86,
    },
    maxErrorKm: 67,
  },
  "jey": {
    initialView: {
      center: [-2.1049, 49.188],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "jor": {
    initialView: {
      center: [35.9903, 31.4987],
      zoom: 7.35,
    },
    maxErrorKm: 54,
  },
  "jpn": {
    initialView: {
      center: [136.2186, 37.5046],
      zoom: 5.38,
    },
    maxErrorKm: 271,
  },
  "kaz": {
    initialView: {
      center: [69.4456, 47.7847],
      zoom: 4.4,
    },
    maxErrorKm: 865,
  },
  "ken": {
    initialView: {
      center: [37.2101, -0.3374],
      zoom: 6.02,
    },
    maxErrorKm: 238,
  },
  "kgz": {
    initialView: {
      center: [72.8573, 41.365],
      zoom: 6.66,
    },
    maxErrorKm: 214,
  },
  "khm": {
    initialView: {
      center: [105.0809, 12.3576],
      zoom: 6.87,
    },
    maxErrorKm: 222,
  },
  "kir": {
    initialView: {
      center: [173.0226, 2.3468],
      zoom: 7.79,
    },
    maxErrorKm: 20,
  },
  "kna": {
    initialView: {
      center: [-62.7256, 17.2705],
      zoom: 10.54,
    },
    maxErrorKm: 10,
  },
  "kor": {
    initialView: {
      center: [127.9085, 36.4849],
      zoom: 6.71,
    },
    maxErrorKm: 158,
  },
  "kwt": {
    initialView: {
      center: [47.8858, 29.2789],
      zoom: 10.53,
    },
    maxErrorKm: 31,
  },
  "lao": {
    initialView: {
      center: [103.3339, 18.2864],
      zoom: 5.97,
    },
    maxErrorKm: 310,
  },
  "lbn": {
    initialView: {
      center: [35.8949, 33.9608],
      zoom: 8.32,
    },
    maxErrorKm: 52,
  },
  "lbr": {
    initialView: {
      center: [-9.5196, 6.5057],
      zoom: 6.87,
    },
    maxErrorKm: 221,
  },
  "lby": {
    initialView: {
      center: [16.1321, 29.3641],
      zoom: 5.67,
    },
    maxErrorKm: 588,
  },
  "lca": {
    initialView: {
      center: [-60.978, 13.8562],
      zoom: 10.61,
    },
    maxErrorKm: 17,
  },
  "lie": {
    initialView: {
      center: [9.5151, 47.1532],
      zoom: 13.67,
    },
    maxErrorKm: 3,
  },
  "lka": {
    initialView: {
      center: [80.815, 7.3398],
      zoom: 7.3,
    },
    maxErrorKm: 119,
  },
  "lso": {
    initialView: {
      center: [28.0527, -29.5198],
      zoom: 8.02,
    },
    maxErrorKm: 83,
  },
  "ltu": {
    initialView: {
      center: [24.0123, 55.1994],
      zoom: 6.75,
    },
    maxErrorKm: 123,
  },
  "lux": {
    initialView: {
      center: [6.1604, 49.7676],
      zoom: 8.98,
    },
    maxErrorKm: 35,
  },
  "lva": {
    initialView: {
      center: [24.639, 56.8904],
      zoom: 6.79,
    },
    maxErrorKm: 130,
  },
  "mac": {
    initialView: {
      center: [113.5461, 22.2006],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "maf": {
    initialView: {
      center: [-63.083, 18.0682],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "mar": {
    initialView: {
      center: [-5.8393, 32.9685],
      zoom: 6.03,
    },
    maxErrorKm: 263,
  },
  "mco": {
    initialView: {
      center: [7.4215, 43.7372],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "mda": {
    initialView: {
      center: [28.7396, 47.0299],
      zoom: 7.09,
    },
    maxErrorKm: 93,
  },
  "mdg": {
    initialView: {
      center: [46.8197, -19.65],
      zoom: 5.3,
    },
    maxErrorKm: 387,
  },
  "mdv": {
    initialView: {
      center: [73.2735, 3.709],
      zoom: 6.14,
    },
    maxErrorKm: 216,
  },
  "mex": {
    initialView: {
      center: [-99.9357, 22.1143],
      zoom: 4.85,
    },
    maxErrorKm: 544,
  },
  "mhl": {
    initialView: {
      center: [171.3803, 7.0897],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "mkd": {
    initialView: {
      center: [21.8989, 41.6171],
      zoom: 8.17,
    },
    maxErrorKm: 79,
  },
  "mli": {
    initialView: {
      center: [-5.7443, 13.6308],
      zoom: 5.89,
    },
    maxErrorKm: 321,
  },
  "mlt": {
    initialView: {
      center: [14.4829, 35.8799],
      zoom: 11.82,
    },
    maxErrorKm: 5,
  },
  "mmr": {
    initialView: {
      center: [96.4438, 19.7495],
      zoom: 5.55,
    },
    maxErrorKm: 380,
  },
  "mne": {
    initialView: {
      center: [19.2253, 42.624],
      zoom: 8.29,
    },
    maxErrorKm: 51,
  },
  "mng": {
    initialView: {
      center: [103.0873, 47.3286],
      zoom: 4.88,
    },
    maxErrorKm: 504,
  },
  "mnp": {
    initialView: {
      center: [145.4307, 14.6754],
      zoom: 8.67,
    },
    maxErrorKm: 67,
  },
  "moz": {
    initialView: {
      center: [36.2065, -18.6999],
      zoom: 4.92,
    },
    maxErrorKm: 604,
  },
  "mrt": {
    initialView: {
      center: [-12.0309, 18.0348],
      zoom: 6.03,
    },
    maxErrorKm: 378,
  },
  "msr": {
    initialView: {
      center: [-62.215, 16.7677],
      zoom: 13.65,
    },
    maxErrorKm: 4,
  },
  "mtq": {
    initialView: {
      center: [-60.9562, 14.6033],
      zoom: 10.66,
    },
    maxErrorKm: 14,
  },
  "mus": {
    initialView: {
      center: [57.5779, -20.2639],
      zoom: 9.75,
    },
    maxErrorKm: 24,
  },
  "mwi": {
    initialView: {
      center: [34.2654, -13.9693],
      zoom: 6.21,
    },
    maxErrorKm: 211,
  },
  "mys": {
    initialView: {
      center: [107.0799, 3.734],
      zoom: 5.54,
    },
    maxErrorKm: 309,
  },
  "myt": {
    initialView: {
      center: [45.1576, -12.829],
      zoom: 10.78,
    },
    maxErrorKm: 14,
  },
  "nam": {
    initialView: {
      center: [17.0613, -22.0206],
      zoom: 5.49,
    },
    maxErrorKm: 392,
  },
  "ncl": {
    initialView: {
      center: [165.4248, -21.333],
      zoom: 7.8,
    },
    maxErrorKm: 122,
  },
  "ner": {
    initialView: {
      center: [5.7118, 15.4734],
      zoom: 5.92,
    },
    maxErrorKm: 389,
  },
  "nfk": {
    initialView: {
      center: [167.9464, -29.0322],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "nga": {
    initialView: {
      center: [7.4662, 8.9049],
      zoom: 5.64,
    },
    maxErrorKm: 424,
  },
  "nic": {
    initialView: {
      center: [-85.8146, 12.5593],
      zoom: 7.33,
    },
    maxErrorKm: 123,
  },
  "niu": {
    initialView: {
      center: [-169.9196, -19.0529],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "nld": {
    initialView: {
      center: [5.4465, 52.1845],
      zoom: 7.12,
    },
    maxErrorKm: 77,
  },
  "nor": {
    initialView: {
      center: [11.7742, 63.5465],
      zoom: 4.16,
    },
    maxErrorKm: 325,
  },
  "npl": {
    initialView: {
      center: [84.5172, 28.2132],
      zoom: 6.56,
    },
    maxErrorKm: 216,
  },
  "nzl": {
    initialView: {
      center: [173.6321, -40.1318],
      zoom: 5.11,
    },
    maxErrorKm: 338,
  },
  "omn": {
    initialView: {
      center: [57.661, 24.2796],
      zoom: 6.75,
    },
    maxErrorKm: 168,
  },
  "pak": {
    initialView: {
      center: [71.0432, 30.8183],
      zoom: 5.14,
    },
    maxErrorKm: 333,
  },
  "pan": {
    initialView: {
      center: [-80.7244, 8.4801],
      zoom: 7.3,
    },
    maxErrorKm: 157,
  },
  "per": {
    initialView: {
      center: [-75.8526, -9.5369],
      zoom: 4.96,
    },
    maxErrorKm: 493,
  },
  "phl": {
    initialView: {
      center: [122.0767, 12.5303],
      zoom: 5.23,
    },
    maxErrorKm: 358,
  },
  "plw": {
    initialView: {
      center: [134.555, 7.4177],
      zoom: 11.48,
    },
    maxErrorKm: 25,
  },
  "png": {
    initialView: {
      center: [146.9638, -6.3222],
      zoom: 5.7,
    },
    maxErrorKm: 527,
  },
  "pol": {
    initialView: {
      center: [19.24, 51.8256],
      zoom: 5.78,
    },
    maxErrorKm: 247,
  },
  "pri": {
    initialView: {
      center: [-66.3941, 18.2333],
      zoom: 8.82,
    },
    maxErrorKm: 53,
  },
  "prk": {
    initialView: {
      center: [126.9588, 39.9078],
      zoom: 6.43,
    },
    maxErrorKm: 196,
  },
  "prt": {
    initialView: {
      center: [-8.2921, 39.3813],
      zoom: 6.23,
    },
    maxErrorKm: 173,
  },
  "pry": {
    initialView: {
      center: [-56.49, -25.3637],
      zoom: 6.65,
    },
    maxErrorKm: 160,
  },
  "pse": {
    initialView: {
      center: [35.1997, 31.9496],
      zoom: 8.43,
    },
    maxErrorKm: 40,
  },
  "pyf": {
    initialView: {
      center: [-145.9244, -13.2971],
      zoom: 5.64,
    },
    maxErrorKm: 183,
  },
  "qat": {
    initialView: {
      center: [51.1928, 25.3381],
      zoom: 9.2,
    },
    maxErrorKm: 33,
  },
  "reu": {
    initialView: {
      center: [55.4934, -21.13],
      zoom: 9.73,
    },
    maxErrorKm: 33,
  },
  "rou": {
    initialView: {
      center: [24.8178, 45.8032],
      zoom: 6.19,
    },
    maxErrorKm: 222,
  },
  "rus": {
    initialView: {
      center: [57.0212, 55.7099],
      zoom: 3.14,
    },
    maxErrorKm: 1188,
  },
  "rwa": {
    initialView: {
      center: [29.7251, -1.9459],
      zoom: 8.43,
    },
    maxErrorKm: 91,
  },
  "sau": {
    initialView: {
      center: [43.2894, 24.0398],
      zoom: 4.88,
    },
    maxErrorKm: 634,
  },
  "sdn": {
    initialView: {
      center: [31.0071, 15.6955],
      zoom: 5.15,
    },
    maxErrorKm: 574,
  },
  "sen": {
    initialView: {
      center: [-15.2894, 14.4995],
      zoom: 6.66,
    },
    maxErrorKm: 215,
  },
  "sgp": {
    initialView: {
      center: [103.8501, 1.2897],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "shn": {
    initialView: {
      center: [-10.065, -11.9267],
      zoom: 5.78,
    },
    maxErrorKm: 1297,
  },
  "sjm": {
    initialView: {
      center: [14.9293, 78.1438],
      zoom: 8.88,
    },
    maxErrorKm: 37,
  },
  "slb": {
    initialView: {
      center: [161.0972, -8.7181],
      zoom: 6.17,
    },
    maxErrorKm: 335,
  },
  "sle": {
    initialView: {
      center: [-11.9649, 8.4052],
      zoom: 7.67,
    },
    maxErrorKm: 126,
  },
  "slv": {
    initialView: {
      center: [-89.0162, 13.7768],
      zoom: 8.4,
    },
    maxErrorKm: 70,
  },
  "smr": {
    initialView: {
      center: [12.464, 43.9528],
      zoom: 13.29,
    },
    maxErrorKm: 5,
  },
  "som": {
    initialView: {
      center: [44.7684, 5.4979],
      zoom: 5.25,
    },
    maxErrorKm: 485,
  },
  "srb": {
    initialView: {
      center: [20.5648, 44.6216],
      zoom: 6.75,
    },
    maxErrorKm: 119,
  },
  "ssd": {
    initialView: {
      center: [29.1244, 6.877],
      zoom: 6.21,
    },
    maxErrorKm: 394,
  },
  "stp": {
    initialView: {
      center: [6.9842, 0.9705],
      zoom: 8.39,
    },
    maxErrorKm: 92,
  },
  "sur": {
    initialView: {
      center: [-55.5141, 5.491],
      zoom: 7.85,
    },
    maxErrorKm: 117,
  },
  "svk": {
    initialView: {
      center: [19.3415, 48.5993],
      zoom: 7.18,
    },
    maxErrorKm: 115,
  },
  "svn": {
    initialView: {
      center: [14.7113, 46.0625],
      zoom: 8.19,
    },
    maxErrorKm: 68,
  },
  "swe": {
    initialView: {
      center: [14.9381, 58.3617],
      zoom: 5.3,
    },
    maxErrorKm: 244,
  },
  "swz": {
    initialView: {
      center: [31.4795, -26.5365],
      zoom: 8.45,
    },
    maxErrorKm: 65,
  },
  "sxm": {
    initialView: {
      center: [-63.0552, 18.0262],
      zoom: 15.13,
    },
    maxErrorKm: 2,
  },
  "syc": {
    initialView: {
      center: [55.455, -4.62],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "syr": {
    initialView: {
      center: [37.9659, 34.6915],
      zoom: 6.39,
    },
    maxErrorKm: 178,
  },
  "tca": {
    initialView: {
      center: [-71.697, 21.6219],
      zoom: 9.25,
    },
    maxErrorKm: 81,
  },
  "tcd": {
    initialView: {
      center: [18.2325, 12.834],
      zoom: 5.43,
    },
    maxErrorKm: 414,
  },
  "tgo": {
    initialView: {
      center: [1.0437, 8.4894],
      zoom: 6.56,
    },
    maxErrorKm: 175,
  },
  "tha": {
    initialView: {
      center: [101.7865, 14.1056],
      zoom: 5.1,
    },
    maxErrorKm: 364,
  },
  "tjk": {
    initialView: {
      center: [69.5813, 38.9064],
      zoom: 6.71,
    },
    maxErrorKm: 170,
  },
  "tkm": {
    initialView: {
      center: [60.0878, 38.8299],
      zoom: 5.62,
    },
    maxErrorKm: 437,
  },
  "tls": {
    initialView: {
      center: [125.7846, -8.8033],
      zoom: 8.69,
    },
    maxErrorKm: 58,
  },
  "ton": {
    initialView: {
      center: [-174.8282, -20.5956],
      zoom: 8.08,
    },
    maxErrorKm: 13,
  },
  "tto": {
    initialView: {
      center: [-61.4071, 10.433],
      zoom: 9.59,
    },
    maxErrorKm: 34,
  },
  "tun": {
    initialView: {
      center: [9.6851, 35.3892],
      zoom: 6.6,
    },
    maxErrorKm: 171,
  },
  "tur": {
    initialView: {
      center: [33.8448, 38.9051],
      zoom: 5.5,
    },
    maxErrorKm: 477,
  },
  "tuv": {
    initialView: {
      center: [179.1942, -8.5243],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "twn": {
    initialView: {
      center: [120.6696, 23.798],
      zoom: 7.27,
    },
    maxErrorKm: 103,
  },
  "tza": {
    initialView: {
      center: [34.6966, -6.0333],
      zoom: 5.51,
    },
    maxErrorKm: 495,
  },
  "uga": {
    initialView: {
      center: [32.5073, 1.2492],
      zoom: 6.72,
    },
    maxErrorKm: 209,
  },
  "ukr": {
    initialView: {
      center: [32.0526, 48.1833],
      zoom: 5.35,
    },
    maxErrorKm: 423,
  },
  "ury": {
    initialView: {
      center: [-55.8988, -33.2606],
      zoom: 6.8,
    },
    maxErrorKm: 192,
  },
  "usa": {
    initialView: {
      center: [-96.0283, 36.717],
      zoom: 3.76,
    },
    maxErrorKm: 1665,
  },
  "uzb": {
    initialView: {
      center: [66.804, 39.8453],
      zoom: 5.77,
    },
    maxErrorKm: 283,
  },
  "vct": {
    initialView: {
      center: [-61.1956, 13.1509],
      zoom: 10.61,
    },
    maxErrorKm: 13,
  },
  "ven": {
    initialView: {
      center: [-68.1726, 8.8042],
      zoom: 6.14,
    },
    maxErrorKm: 324,
  },
  "vgb": {
    initialView: {
      center: [-64.5278, 18.4375],
      zoom: 11.82,
    },
    maxErrorKm: 20,
  },
  "vir": {
    initialView: {
      center: [-64.8181, 18.0302],
      zoom: 9.39,
    },
    maxErrorKm: 66,
  },
  "vnm": {
    initialView: {
      center: [106.172, 16.3912],
      zoom: 5.06,
    },
    maxErrorKm: 574,
  },
  "vut": {
    initialView: {
      center: [168.222, -16.7089],
      zoom: 6.25,
    },
    maxErrorKm: 356,
  },
  "wlf": {
    initialView: {
      center: [-176.1745, -13.2816],
      zoom: 52.32,
    },
    maxErrorKm: 25,
  },
  "wsm": {
    initialView: {
      center: [-172.0385, -13.7467],
      zoom: 9.14,
    },
    maxErrorKm: 45,
  },
  "xkx": {
    initialView: {
      center: [20.8789, 42.6589],
      zoom: 8.54,
    },
    maxErrorKm: 47,
  },
  "yem": {
    initialView: {
      center: [45.725, 15.0337],
      zoom: 6.59,
    },
    maxErrorKm: 203,
  },
  "zaf": {
    initialView: {
      center: [26.7205, -28.2659],
      zoom: 5.06,
    },
    maxErrorKm: 426,
  },
  "zmb": {
    initialView: {
      center: [28.1414, -13.1554],
      zoom: 5.55,
    },
    maxErrorKm: 464,
  },
  "zwe": {
    initialView: {
      center: [29.8667, -18.4848],
      zoom: 6.44,
    },
    maxErrorKm: 245,
  },
};

/**
 * Returns the generated town quiz configuration for a country.
 */
export function getTownCountryConfig(
  countryId: string,
): TownCountryConfig | undefined {
  return townCountryConfigs[
    countryId.toLowerCase()
  ];
}

/**
 * Determines whether a generated town configuration exists for a country.
 */
export function hasTownCountryConfig(
  countryId: string,
): boolean {
  return (
    getTownCountryConfig(
      countryId,
    ) !== undefined
  );
}
