"""
Inspect Brazil's 2012 CEP database and analyze two-digit postal-code prefixes.

This script reads the brazil.db MySQL dump without importing it into a database.
It determines which two-digit CEP prefixes occur in each city and reports how
often municipal boundaries could potentially represent those prefixes without
requiring internal subdivision.

No runtime GeoJSON is generated by this script.
"""

from __future__ import annotations

import csv
import json
import re
from collections import Counter, defaultdict
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[4]

SQL_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "countries"
    / "brazil"
    / "brazil.db-master"
    / "cep2012"
    / "cep2012.sql"
)

REPORT_DIRECTORY = (
    PROJECT_ROOT
    / "data"
    / "intermediate"
    / "countries"
    / "brazil"
    / "postal"
)

SUMMARY_PATH = REPORT_DIRECTORY / "cep-2-analysis.json"
MULTI_PREFIX_CITIES_PATH = REPORT_DIRECTORY / "multi-prefix-cities.csv"


STATE_INSERT_RE = re.compile(
    r"^INSERT INTO `tend_estado` .* VALUES "
    r"\((\d+),'((?:\\'|[^'])*)','([A-Z]{2})'\);$"
)

CITY_INSERT_RE = re.compile(
    r"^INSERT INTO `tend_cidade` .* VALUES "
    r"\((\d+),(\d+),'((?:\\'|[^'])*)'\);$"
)

ADDRESS_INSERT_RE = re.compile(
    r"^INSERT INTO `tend_endereco` .* VALUES "
    r"\('([^']+)',(\d+),"
)

VALID_CEP_RE = re.compile(r"^\d{5}-\d{3}$")


def decode_mysql_string(value: str) -> str:
    """
    Decode the small subset of MySQL string escaping needed by city/state names.
    """

    return (
        value.replace(r"\'", "'")
        .replace(r"\\", "\\")
    )


def analyze_postal_codes() -> None:
    """
    Parse the SQL dump and analyze two-digit CEP-prefix membership by city.
    """

    if not SQL_PATH.exists():
        raise FileNotFoundError(
            f"Brazil CEP SQL dump was not found:\n{SQL_PATH}"
        )

    states: dict[int, dict[str, str]] = {}
    cities: dict[int, dict[str, object]] = {}

    city_prefix_counts: dict[int, Counter[str]] = defaultdict(Counter)
    state_prefix_counts: dict[int, Counter[str]] = defaultdict(Counter)

    all_prefix_counts: Counter[str] = Counter()

    total_address_rows = 0
    valid_cep_rows = 0
    invalid_cep_rows = 0

    invalid_cep_examples: list[str] = []

    print("Inspecting Brazil CEP database...")
    print(f"Source: {SQL_PATH}")
    print()

    with SQL_PATH.open(
        "r",
        encoding="utf-8",
        errors="replace",
    ) as file:
        for line_number, raw_line in enumerate(file, start=1):
            line = raw_line.rstrip("\r\n")

            if line.startswith("INSERT INTO `tend_estado`"):
                match = STATE_INSERT_RE.match(line)

                if not match:
                    raise ValueError(
                        "Could not parse tend_estado INSERT on "
                        f"line {line_number}."
                    )

                state_id = int(match.group(1))
                state_name = decode_mysql_string(match.group(2))
                abbreviation = match.group(3)

                states[state_id] = {
                    "name": state_name,
                    "abbreviation": abbreviation,
                }

                continue

            if line.startswith("INSERT INTO `tend_cidade`"):
                match = CITY_INSERT_RE.match(line)

                if not match:
                    raise ValueError(
                        "Could not parse tend_cidade INSERT on "
                        f"line {line_number}."
                    )

                city_id = int(match.group(1))
                state_id = int(match.group(2))
                city_name = decode_mysql_string(match.group(3))

                cities[city_id] = {
                    "name": city_name,
                    "state_id": state_id,
                }

                continue

            if not line.startswith("INSERT INTO `tend_endereco`"):
                continue

            total_address_rows += 1

            match = ADDRESS_INSERT_RE.match(line)

            if not match:
                raise ValueError(
                    "Could not parse tend_endereco INSERT on "
                    f"line {line_number}."
                )

            cep = match.group(1)
            city_id = int(match.group(2))

            if not VALID_CEP_RE.fullmatch(cep):
                invalid_cep_rows += 1

                if len(invalid_cep_examples) < 20:
                    invalid_cep_examples.append(cep)

                continue

            valid_cep_rows += 1

            prefix = cep[:2]

            city_prefix_counts[city_id][prefix] += 1
            all_prefix_counts[prefix] += 1

    if not states:
        raise ValueError("No states were parsed from the SQL dump.")

    if not cities:
        raise ValueError("No cities were parsed from the SQL dump.")

    if total_address_rows == 0:
        raise ValueError("No CEP/address records were parsed from the SQL dump.")

    unknown_city_ids = sorted(
        set(city_prefix_counts) - set(cities)
    )

    if unknown_city_ids:
        preview = ", ".join(
            str(city_id) for city_id in unknown_city_ids[:20]
        )

        raise ValueError(
            "CEP records reference city IDs that do not exist in tend_cidade: "
            f"{preview}"
        )

    cities_with_cep_data = sorted(city_prefix_counts)
    cities_without_cep_data = sorted(
        set(cities) - set(city_prefix_counts)
    )

    prefix_count_histogram = Counter(
        len(city_prefix_counts[city_id])
        for city_id in cities_with_cep_data
    )

    multi_prefix_city_ids = sorted(
        city_id
        for city_id in cities_with_cep_data
        if len(city_prefix_counts[city_id]) > 1
    )

    for city_id, prefix_counts in city_prefix_counts.items():
        city = cities[city_id]
        state_id = int(city["state_id"])

        for prefix, count in prefix_counts.items():
            state_prefix_counts[state_id][prefix] += count

    distinct_prefixes = sorted(all_prefix_counts)

    REPORT_DIRECTORY.mkdir(parents=True, exist_ok=True)

    multi_prefix_rows: list[dict[str, object]] = []

    for city_id in multi_prefix_city_ids:
        city = cities[city_id]
        state_id = int(city["state_id"])
        state = states.get(state_id)

        if state is None:
            raise ValueError(
                f"City {city_id} references unknown state ID {state_id}."
            )

        prefix_counts = city_prefix_counts[city_id]
        prefixes = sorted(prefix_counts)

        multi_prefix_rows.append(
            {
                "city_id": city_id,
                "city": city["name"],
                "state": state["abbreviation"],
                "state_name": state["name"],
                "prefix_count": len(prefixes),
                "prefixes": prefixes,
                "cep_records": sum(prefix_counts.values()),
                "records_by_prefix": dict(
                    sorted(prefix_counts.items())
                ),
            }
        )

    summary = {
        "source": str(SQL_PATH.relative_to(PROJECT_ROOT)),
        "address_rows": {
            "total": total_address_rows,
            "valid_cep": valid_cep_rows,
            "invalid_cep": invalid_cep_rows,
            "invalid_examples": invalid_cep_examples,
        },
        "states": {
            "total": len(states),
        },
        "cities": {
            "total": len(cities),
            "with_cep_data": len(cities_with_cep_data),
            "without_cep_data": len(cities_without_cep_data),
            "without_cep_data_details": [
                {
                    "city_id": city_id,
                    "city": cities[city_id]["name"],
                    "state": states[
                        int(cities[city_id]["state_id"])
                    ]["abbreviation"],
                }
                for city_id in cities_without_cep_data
            ],
        },
        "two_digit_prefixes": {
            "count": len(distinct_prefixes),
            "values": distinct_prefixes,
            "records_by_prefix": dict(
                sorted(all_prefix_counts.items())
            ),
        },
        "cities_by_prefix_count": {
            str(prefix_count): city_count
            for prefix_count, city_count
            in sorted(prefix_count_histogram.items())
        },
        "multi_prefix_cities": multi_prefix_rows,
        "prefixes_by_state": {
            states[state_id]["abbreviation"]: {
                "prefixes": sorted(prefix_counts),
                "records_by_prefix": dict(
                    sorted(prefix_counts.items())
                ),
            }
            for state_id, prefix_counts
            in sorted(
                state_prefix_counts.items(),
                key=lambda item: states[item[0]]["abbreviation"],
            )
        },
    }

    with SUMMARY_PATH.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            summary,
            file,
            ensure_ascii=False,
            indent=2,
        )

        file.write("\n")

    with MULTI_PREFIX_CITIES_PATH.open(
        "w",
        encoding="utf-8",
        newline="",
    ) as file:
        writer = csv.writer(file)

        writer.writerow(
            [
                "city_id",
                "city",
                "state",
                "prefix_count",
                "prefixes",
                "cep_records",
                "records_by_prefix",
            ]
        )

        for row in multi_prefix_rows:
            writer.writerow(
                [
                    row["city_id"],
                    row["city"],
                    row["state"],
                    row["prefix_count"],
                    ", ".join(row["prefixes"]),
                    row["cep_records"],
                    ", ".join(
                        f"{prefix}:{count}"
                        for prefix, count
                        in row["records_by_prefix"].items()
                    ),
                ]
            )

    print("Database summary")
    print("----------------")
    print(f"States:              {len(states):,}")
    print(f"Cities:              {len(cities):,}")
    print(f"Address rows:        {total_address_rows:,}")
    print(f"Valid CEP rows:      {valid_cep_rows:,}")
    print(f"Invalid CEP rows:    {invalid_cep_rows:,}")
    print()

    print("Two-digit CEP prefixes")
    print("-----------------------")
    print(f"Distinct prefixes:   {len(distinct_prefixes):,}")
    print(f"Values:              {', '.join(distinct_prefixes)}")
    print()

    print("City coverage")
    print("-------------")
    print(
        f"With CEP data:       "
        f"{len(cities_with_cep_data):,}"
    )
    print(
        f"Without CEP data:    "
        f"{len(cities_without_cep_data):,}"
    )
    print()

    print("Cities by number of two-digit prefixes")
    print("---------------------------------------")

    for prefix_count, city_count in sorted(
        prefix_count_histogram.items()
    ):
        print(
            f"{prefix_count:>2} prefix"
            f"{'es' if prefix_count != 1 else ' ':<2}"
            f" -> {city_count:,} cities"
        )

    print()
    print(
        f"Multi-prefix cities: {len(multi_prefix_city_ids):,}"
    )
    print()

    if multi_prefix_rows:
        print("Multi-prefix city details")
        print("-------------------------")

        for row in multi_prefix_rows:
            prefix_details = ", ".join(
                f"{prefix} ({count:,})"
                for prefix, count
                in row["records_by_prefix"].items()
            )

            print(
                f"{row['state']}  "
                f"{row['city']}  "
                f"[{prefix_details}]"
            )

        print()

    if invalid_cep_examples:
        print("Invalid CEP examples")
        print("--------------------")

        for cep in invalid_cep_examples:
            print(cep)

        print()

    print("Reports")
    print("-------")
    print(
        f"JSON: {SUMMARY_PATH.relative_to(PROJECT_ROOT)}"
    )
    print(
        "CSV:  "
        f"{MULTI_PREFIX_CITIES_PATH.relative_to(PROJECT_ROOT)}"
    )


if __name__ == "__main__":
    analyze_postal_codes()