/**
 * Generated South Korea telephone area-code questions.
 *
 * Do not edit this file manually.
 *
 * Regenerate with:
 *   python scripts/countries/south-korea/generate/area-codes.py
 */

import type { FeatureQuizQuestion } from "@/types/quiz";

export const SOUTH_KOREA_AREA_CODE_QUESTIONS: FeatureQuizQuestion[] = [
  { answer: "11", display: "02" },
  { answer: "31", display: "031" },
  { answer: "23", display: "032" },
  { answer: "32", display: "033" },
  { answer: "34", display: "041" },
  { answer: "25", display: "042" },
  { answer: "33", display: "043" },
  { answer: "29", display: "044" },
  { answer: "21", display: "051" },
  { answer: "26", display: "052" },
  { answer: "22", display: "053" },
  { answer: "37", display: "054" },
  { answer: "38", display: "055" },
  { answer: "36", display: "061" },
  { answer: "24", display: "062" },
  { answer: "35", display: "063" },
  { answer: "39", display: "064" },
];

export const SOUTH_KOREA_AREA_CODE_PREFIX_QUESTIONS: FeatureQuizQuestion[] = [
  { answer: "2", display: "02-" },
  { answer: "3", display: "03-" },
  { answer: "4", display: "04-" },
  { answer: "5", display: "05-" },
  { answer: "6", display: "06-" },
];
