/**
 * Generated Eswatini administrative quiz question data.
 *
 * Do not edit this file manually.
 *
 * Regenerate with:
 *   python scripts/countries/eswatini/generate/admin-quiz-data.py
 */

import type { FeatureQuizQuestion } from "@/types/quiz";

export const ESWATINI_REGION_QUIZ_QUESTIONS: FeatureQuizQuestion[] = [
  { answer: "75366066B25905390127614", display: "Hhohho" },
  { answer: "75366066B12234306804593", display: "Lubombo" },
  { answer: "75366066B3567364273406", display: "Manzini" },
  { answer: "75366066B21527038718027", display: "Shiselweni" },
];

export const ESWATINI_TINKHUNDLA_QUIZ_QUESTIONS: FeatureQuizQuestion[] = [
  { answer: "25544865B2448699584693", display: "Dvokodvweni" },
  { answer: "25544865B36253147760946", display: "Ekukhanyeni" },
  { answer: "25544865B4123625373150", display: "Gege" },
  { answer: "25544865B11475880596120", display: "Hhukwini" },
  { answer: "25544865B95753753422766", display: "Hlane" },
  { answer: "25544865B71505016077226", display: "Hosea" },
  { answer: "25544865B51984486124327", display: "Kubuta" },
  { answer: "25544865B87479074006038", display: "Kwaluseni" },
  { answer: "25544865B81777462131642", display: "Lamgabhi" },
  { answer: "25544865B71211064556638", display: "Lobamba" },
  { answer: "25544865B34584477207861", display: "Lobamba Lomdzala" },
  { answer: "25544865B99062950351047", display: "Lomahasha" },
  { answer: "25544865B36979951032132", display: "Lubuli" },
  { answer: "25544865B4564355932947", display: "Ludzeludze" },
  { answer: "25544865B88364100009265", display: "Lugongolweni" },
  { answer: "25544865B1439783352799", display: "Madlangempisi" },
  { answer: "25544865B4547818203338", display: "Mafutseni" },
  { answer: "25544865B64693820583012", display: "Mahlangatja" },
  { answer: "25544865B24678717441439", display: "Mangcongco" },
  { answer: "25544865B2374856354731", display: "Manzini" },
  { answer: "25544865B19615198899380", display: "Maphalaleni" },
  { answer: "25544865B74382320525051", display: "Maseyisini" },
  { answer: "25544865B33657580683918", display: "Matsanjeni" },
  { answer: "25544865B478936886015", display: "Mayiwane" },
  { answer: "25544865B94244502272687", display: "Mbabane" },
  { answer: "25544865B23697894353870", display: "Mbangweni" },
  { answer: "25544865B94915093759021", display: "Mhlambanyatsi" },
  { answer: "25544865B85200764608315", display: "Mhlangatane" },
  { answer: "25544865B37706944907644", display: "Mhlume" },
  { answer: "25544865B73094271858918", display: "Mkhiweni" },
  { answer: "25544865B62605108409281", display: "Motjane" },
  { answer: "25544865B6295441038761", display: "Mpolonjeni" },
  { answer: "25544865B27395168638163", display: "Mthongwaneni" },
  { answer: "25544865B87308763732212", display: "Mtsambama" },
  { answer: "25544865B5702357250471", display: "Ndzingeni" },
  { answer: "25544865B16433175131284", display: "Ngudzeni" },
  { answer: "25544865B616938903867", display: "Ngwempisi" },
  { answer: "25544865B62426569350432", display: "Nhlambeni" },
  { answer: "25544865B7556618042138", display: "Nkhaba" },
  { answer: "25544865B71233313163720", display: "Nkilongo" },
  { answer: "25544865B73521890891897", display: "Nkwene" },
  { answer: "25544865B10788448603865", display: "Ntfonjeni" },
  { answer: "25544865B29554005324446", display: "Ntondozi" },
  { answer: "25544865B91965971492812", display: "Piggs Peak" },
  { answer: "25544865B96981286977121", display: "Sandleni" },
  { answer: "25544865B11062726816998", display: "Shiselweni" },
  { answer: "25544865B76074174917722", display: "Sigwe" },
  { answer: "25544865B49995279620890", display: "Siphofaneni" },
  { answer: "25544865B34685739182114", display: "Sithobela" },
  { answer: "25544865B68491225088815", display: "Somntongo" },
  { answer: "25544865B99429407754877", display: "Tikhuba" },
  { answer: "25544865B14062061502324", display: "Timpisini" },
  { answer: "25544865B75252057291440", display: "Zombodze" },
];
