/**
 * AUTO-GENERATED FILE.
 *
 * Generated by:
 *
 *   scripts/countries/ecuador/generate/generate-admin-quizzes.ts
 *
 * Do not edit the question list manually. Update Ecuador's processed
 * administrative GeoJSON or the generator and regenerate this file instead.
 */

import type { FeatureQuiz } from "@/types/quiz";

/**
 * Ecuador's canton quiz questions.
 */
const ECUADOR_CANTON_QUESTIONS: FeatureQuiz["questions"] = [
  {
    answer: "EC1316",
    display: "24 de Mayo",
  },
  {
    answer: "EC2202",
    display: "Aguarico",
  },
  {
    answer: "EC0602",
    display: "Alausí",
  },
  {
    answer: "EC0902",
    display: "Alfredo Baquerizo Moreno (Juján)",
  },
  {
    answer: "EC1801",
    display: "Ambato",
  },
  {
    answer: "EC1002",
    display: "Antonio Ante",
  },
  {
    answer: "EC1604",
    display: "Arajuno",
  },
  {
    answer: "EC1503",
    display: "Archidona",
  },
  {
    answer: "EC0702",
    display: "Arenillas",
  },
  {
    answer: "EC0806",
    display: "Atacames",
  },
  {
    answer: "EC0703",
    display: "Atahualpa",
  },
  {
    answer: "EC0301",
    display: "Azogues",
  },
  {
    answer: "EC1202",
    display: "Baba",
  },
  {
    answer: "EC1201",
    display: "Babahoyo",
  },
  {
    answer: "EC0903",
    display: "Balao",
  },
  {
    answer: "EC0704",
    display: "Balsas",
  },
  {
    answer: "EC0904",
    display: "Balzar",
  },
  {
    answer: "EC1802",
    display: "Baños de Agua Santa",
  },
  {
    answer: "EC0302",
    display: "Biblián",
  },
  {
    answer: "EC0402",
    display: "Bolívar",
  },
  {
    answer: "EC1302",
    display: "Bolívar",
  },
  {
    answer: "EC1210",
    display: "Buena Fe",
  },
  {
    answer: "EC0206",
    display: "Caluma",
  },
  {
    answer: "EC1102",
    display: "Calvas",
  },
  {
    answer: "EC0115",
    display: "Camilo Ponce enríquez",
  },
  {
    answer: "EC0303",
    display: "Cañar",
  },
  {
    answer: "EC1509",
    display: "Carlos Julio Arosemena Tola",
  },
  {
    answer: "EC2106",
    display: "Cascales",
  },
  {
    answer: "EC1103",
    display: "Catamayo",
  },
  {
    answer: "EC1702",
    display: "Cayambe",
  },
  {
    answer: "EC1104",
    display: "Celica",
  },
  {
    answer: "EC1907",
    display: "Centinela del Cóndor",
  },
  {
    answer: "EC1803",
    display: "Cevallos",
  },
  {
    answer: "EC1105",
    display: "Chaguarpamba",
  },
  {
    answer: "EC0604",
    display: "Chambo",
  },
  {
    answer: "EC0705",
    display: "Chilla",
  },
  {
    answer: "EC0202",
    display: "Chillanes",
  },
  {
    answer: "EC0203",
    display: "Chimbo",
  },
  {
    answer: "EC1902",
    display: "Chinchipe",
  },
  {
    answer: "EC1303",
    display: "Chone",
  },
  {
    answer: "EC0111",
    display: "Chordeleg",
  },
  {
    answer: "EC0605",
    display: "Chunchi",
  },
  {
    answer: "EC0905",
    display: "Colimes",
  },
  {
    answer: "EC0603",
    display: "Colta",
  },
  {
    answer: "EC0923",
    display: "Coronel Marcelino Maridueña",
  },
  {
    answer: "EC1003",
    display: "Cotacachi",
  },
  {
    answer: "EC0101",
    display: "Cuenca",
  },
  {
    answer: "EC0610",
    display: "Cumandá",
  },
  {
    answer: "EC2107",
    display: "Cuyabeno",
  },
  {
    answer: "EC0906",
    display: "Daule",
  },
  {
    answer: "EC0306",
    display: "Déleg",
  },
  {
    answer: "EC1701",
    display: "Distrito Metropolitano de Quito",
  },
  {
    answer: "EC0907",
    display: "Durán",
  },
  {
    answer: "EC0204",
    display: "Echeandía",
  },
  {
    answer: "EC1304",
    display: "El Carmen",
  },
  {
    answer: "EC1504",
    display: "El Chaco",
  },
  {
    answer: "EC0908",
    display: "El Empalme",
  },
  {
    answer: "EC0706",
    display: "El Guabo",
  },
  {
    answer: "EC0112",
    display: "El Pan",
  },
  {
    answer: "EC1906",
    display: "El Pangui",
  },
  {
    answer: "EC0305",
    display: "El Tambo",
  },
  {
    answer: "EC0909",
    display: "El Triunfo",
  },
  {
    answer: "EC0802",
    display: "Eloy Alfaro",
  },
  {
    answer: "EC0801",
    display: "Esmeraldas",
  },
  {
    answer: "EC0403",
    display: "Espejo",
  },
  {
    answer: "EC1106",
    display: "Espíndola",
  },
  {
    answer: "EC1305",
    display: "Flavio Alfaro",
  },
  {
    answer: "EC2201",
    display: "Francisco de Orellana",
  },
  {
    answer: "EC0927",
    display: "General  Antonio Elizalde",
  },
  {
    answer: "EC0102",
    display: "Girón",
  },
  {
    answer: "EC2102",
    display: "Gonzalo Pizarro",
  },
  {
    answer: "EC1107",
    display: "Gonzanamá",
  },
  {
    answer: "EC0114",
    display: "Guachapala",
  },
  {
    answer: "EC0103",
    display: "Gualaceo",
  },
  {
    answer: "EC1402",
    display: "Gualaquiza",
  },
  {
    answer: "EC0606",
    display: "Guamote",
  },
  {
    answer: "EC0607",
    display: "Guano",
  },
  {
    answer: "EC0201",
    display: "Guaranda",
  },
  {
    answer: "EC0901",
    display: "Guayaquil",
  },
  {
    answer: "EC1407",
    display: "Huamboya",
  },
  {
    answer: "EC0707",
    display: "Huaquillas",
  },
  {
    answer: "EC1001",
    display: "Ibarra",
  },
  {
    answer: "EC2002",
    display: "Isabela",
  },
  {
    answer: "EC0928",
    display: "Isidro Ayora",
  },
  {
    answer: "EC1320",
    display: "Jama",
  },
  {
    answer: "EC1321",
    display: "Jaramijó",
  },
  {
    answer: "EC1306",
    display: "Jipijapa",
  },
  {
    answer: "EC1307",
    display: "Junín",
  },
  {
    answer: "EC2302",
    display: "La Concordia",
  },
  {
    answer: "EC2203",
    display: "La Joya de los Sachas",
  },
  {
    answer: "EC2402",
    display: "La Libertad",
  },
  {
    answer: "EC0502",
    display: "La Maná",
  },
  {
    answer: "EC0304",
    display: "La Troncal",
  },
  {
    answer: "EC2101",
    display: "Lago Agrio",
  },
  {
    answer: "EC0714",
    display: "Las Lajas",
  },
  {
    answer: "EC0207",
    display: "Las Naves",
  },
  {
    answer: "EC0501",
    display: "Latacunga",
  },
  {
    answer: "EC1403",
    display: "Limón Indanza",
  },
  {
    answer: "EC1410",
    display: "Logroño",
  },
  {
    answer: "EC1101",
    display: "Loja",
  },
  {
    answer: "EC0924",
    display: "Lomas de Sargentillo",
  },
  {
    answer: "EC2204",
    display: "Loreto",
  },
  {
    answer: "EC1108",
    display: "Macará",
  },
  {
    answer: "EC0701",
    display: "Machala",
  },
  {
    answer: "EC1308",
    display: "Manta",
  },
  {
    answer: "EC0708",
    display: "Marcabelí",
  },
  {
    answer: "EC1703",
    display: "Mejía",
  },
  {
    answer: "EC1602",
    display: "Mera",
  },
  {
    answer: "EC0910",
    display: "Milagro",
  },
  {
    answer: "EC0404",
    display: "Mira",
  },
  {
    answer: "EC1212",
    display: "Mocache",
  },
  {
    answer: "EC1804",
    display: "Mocha",
  },
  {
    answer: "EC1203",
    display: "Montalvo",
  },
  {
    answer: "EC1309",
    display: "Montecristi",
  },
  {
    answer: "EC0405",
    display: "Montúfar",
  },
  {
    answer: "EC1401",
    display: "Morona",
  },
  {
    answer: "EC0803",
    display: "Muisne",
  },
  {
    answer: "EC0104",
    display: "Nabón",
  },
  {
    answer: "EC1903",
    display: "Nangaritza",
  },
  {
    answer: "EC0911",
    display: "Naranjal",
  },
  {
    answer: "EC0912",
    display: "Naranjito",
  },
  {
    answer: "EC0925",
    display: "Nobol",
  },
  {
    answer: "EC1116",
    display: "Olmedo",
  },
  {
    answer: "EC1318",
    display: "Olmedo",
  },
  {
    answer: "EC0110",
    display: "Oña",
  },
  {
    answer: "EC1004",
    display: "Otavalo",
  },
  {
    answer: "EC1411",
    display: "Pablo Sexto",
  },
  {
    answer: "EC1310",
    display: "Paján",
  },
  {
    answer: "EC1908",
    display: "Palanda",
  },
  {
    answer: "EC1209",
    display: "Palenque",
  },
  {
    answer: "EC0913",
    display: "Palestina",
  },
  {
    answer: "EC0608",
    display: "Pallatanga",
  },
  {
    answer: "EC1404",
    display: "Palora",
  },
  {
    answer: "EC1109",
    display: "Paltas",
  },
  {
    answer: "EC0503",
    display: "Pangua",
  },
  {
    answer: "EC1909",
    display: "Paquisha",
  },
  {
    answer: "EC0709",
    display: "Pasaje",
  },
  {
    answer: "EC1601",
    display: "Pastaza",
  },
  {
    answer: "EC1805",
    display: "Patate",
  },
  {
    answer: "EC0105",
    display: "Paute",
  },
  {
    answer: "EC1317",
    display: "Pedernales",
  },
  {
    answer: "EC0914",
    display: "Pedro Carbo",
  },
  {
    answer: "EC1704",
    display: "Pedro Moncayo",
  },
  {
    answer: "EC1708",
    display: "Pedro Vicente Maldonado",
  },
  {
    answer: "EC0609",
    display: "Penipe",
  },
  {
    answer: "EC1311",
    display: "Pichincha",
  },
  {
    answer: "EC1005",
    display: "Pimampiro",
  },
  {
    answer: "EC1114",
    display: "Pindal",
  },
  {
    answer: "EC0710",
    display: "Piñas",
  },
  {
    answer: "EC0921",
    display: "Playas",
  },
  {
    answer: "EC0711",
    display: "Portovelo",
  },
  {
    answer: "EC1301",
    display: "Portoviejo",
  },
  {
    answer: "EC0106",
    display: "Pucará",
  },
  {
    answer: "EC1204",
    display: "Puebloviejo",
  },
  {
    answer: "EC1319",
    display: "Puerto López",
  },
  {
    answer: "EC1709",
    display: "Puerto Quito",
  },
  {
    answer: "EC0504",
    display: "Pujilí",
  },
  {
    answer: "EC2103",
    display: "Putumayo",
  },
  {
    answer: "EC1110",
    display: "Puyango",
  },
  {
    answer: "EC1806",
    display: "Quero",
  },
  {
    answer: "EC1205",
    display: "Quevedo",
  },
  {
    answer: "EC1507",
    display: "Quijos",
  },
  {
    answer: "EC1115",
    display: "Quilanga",
  },
  {
    answer: "EC0804",
    display: "Quinindé",
  },
  {
    answer: "EC1213",
    display: "Quinsaloma",
  },
  {
    answer: "EC0601",
    display: "Riobamba",
  },
  {
    answer: "EC0807",
    display: "Rioverde",
  },
  {
    answer: "EC1312",
    display: "Rocafuerte",
  },
  {
    answer: "EC1705",
    display: "Rumiñahui",
  },
  {
    answer: "EC0505",
    display: "Salcedo",
  },
  {
    answer: "EC2403",
    display: "Salinas",
  },
  {
    answer: "EC0919",
    display: "Salitre",
  },
  {
    answer: "EC0916",
    display: "Samborondón",
  },
  {
    answer: "EC2001",
    display: "San Cristóbal",
  },
  {
    answer: "EC0107",
    display: "San Fernando",
  },
  {
    answer: "EC0920",
    display: "San Jacinto de Yaguachi",
  },
  {
    answer: "EC1408",
    display: "San Juan Bosco",
  },
  {
    answer: "EC0805",
    display: "San Lorenzo",
  },
  {
    answer: "EC0205",
    display: "San Miguel",
  },
  {
    answer: "EC1707",
    display: "San Miguel de los Bancos",
  },
  {
    answer: "EC1006",
    display: "San Miguel de Urcuquí",
  },
  {
    answer: "EC0406",
    display: "San Pedro de Huaca",
  },
  {
    answer: "EC1807",
    display: "San Pedro de Pelileo",
  },
  {
    answer: "EC1322",
    display: "San Vicente",
  },
  {
    answer: "EC1313",
    display: "Santa Ana",
  },
  {
    answer: "EC1603",
    display: "Santa Clara",
  },
  {
    answer: "EC2003",
    display: "Santa Cruz",
  },
  {
    answer: "EC2401",
    display: "Santa Elena",
  },
  {
    answer: "EC0108",
    display: "Santa Isabel",
  },
  {
    answer: "EC0918",
    display: "Santa Lucía",
  },
  {
    answer: "EC0712",
    display: "Santa Rosa",
  },
  {
    answer: "EC1405",
    display: "Santiago",
  },
  {
    answer: "EC1808",
    display: "Santiago de Píllaro",
  },
  {
    answer: "EC2301",
    display: "Santo Domingo",
  },
  {
    answer: "EC0506",
    display: "Saquisilí",
  },
  {
    answer: "EC1111",
    display: "Saraguro",
  },
  {
    answer: "EC0113",
    display: "Sevilla de Oro",
  },
  {
    answer: "EC2104",
    display: "Shushufindi",
  },
  {
    answer: "EC0507",
    display: "Sigchos",
  },
  {
    answer: "EC0109",
    display: "Sígsig",
  },
  {
    answer: "EC0922",
    display: "Simón Bolívar",
  },
  {
    answer: "EC1112",
    display: "Sozoranga",
  },
  {
    answer: "EC1314",
    display: "Sucre",
  },
  {
    answer: "EC1406",
    display: "Sucúa",
  },
  {
    answer: "EC2105",
    display: "Sucumbíos",
  },
  {
    answer: "EC0307",
    display: "Suscal",
  },
  {
    answer: "EC1409",
    display: "Taisha",
  },
  {
    answer: "EC1501",
    display: "Tena",
  },
  {
    answer: "EC1809",
    display: "Tisaleo",
  },
  {
    answer: "EC1412",
    display: "Tiwintza",
  },
  {
    answer: "EC1315",
    display: "Tosagua",
  },
  {
    answer: "EC0401",
    display: "Tulcán",
  },
  {
    answer: "EC1206",
    display: "Urdaneta",
  },
  {
    answer: "EC1211",
    display: "Valencia",
  },
  {
    answer: "EC1207",
    display: "Ventanas",
  },
  {
    answer: "EC1208",
    display: "Vinces",
  },
  {
    answer: "EC1904",
    display: "Yacuambi",
  },
  {
    answer: "EC1905",
    display: "Yantzaza",
  },
  {
    answer: "EC1901",
    display: "Zamora",
  },
  {
    answer: "EC1113",
    display: "Zapotillo",
  },
  {
    answer: "EC0713",
    display: "Zaruma",
  },
];

/**
 * Description shown for Ecuador's Cantons quiz.
 */
const ECUADOR_CANTONS_DESCRIPTION =
  `Learn all ${ECUADOR_CANTON_QUESTIONS.length} cantons of Ecuador and ` +
  `where they are located across the country. Use the Province grouping to ` +
  `learn the cantons one province at a time.`;

/**
 * Quiz configuration for Ecuador's cantons.
 */
export const ecuadorCantonsQuiz: FeatureQuiz = {
  id: "ecuador-cantons",
  name: "Cantons",
  description: ECUADOR_CANTONS_DESCRIPTION,

  kind: "feature",
  mapId: "ecuador-cantons",

  answerProperty: "canton_id",
  answerType: "single",

  grouping: {
    properties: [
      {
        property: "province",
        label: "Province",
        valueType: "string",
      },
    ],
  },

  baseMapLayers: {
    subdivisionLabels: false,
  },

  questions: ECUADOR_CANTON_QUESTIONS,
};
