/**
 * Generated quiz question data for Botswana's administrative divisions.
 *
 * Do not edit this file manually. Regenerate it with:
 * python scripts/countries/botswana/generate/admin-quiz-data.py
 */

import type { FeatureQuizQuestion } from "@/types/quiz";

export const BOTSWANA_DISTRICTS_QUIZ_QUESTIONS: FeatureQuizQuestion[] = [
  { answer: "BWCE", display: "Central" },
  { answer: "BWCH", display: "Chobe" },
  { answer: "BWFR", display: "Francistown" },
  { answer: "BWGA", display: "Gaborone" },
  { answer: "BWGH", display: "Ghanzi" },
  { answer: "BWJW", display: "Jwaneng" },
  { answer: "BWKG", display: "Kgalagadi" },
  { answer: "BWKL", display: "Kgatleng" },
  { answer: "BWKW", display: "Kweneng" },
  { answer: "BWLO", display: "Lobatse" },
  { answer: "BWNE", display: "North East" },
  { answer: "BWNW", display: "North West" },
  { answer: "BWSP", display: "Selibe Phikwe" },
  { answer: "BWSE", display: "South East" },
  { answer: "BWSO", display: "Southern" },
  { answer: "BWST", display: "Sowa Town" },
];

export const BOTSWANA_SUB_DISTRICTS_QUIZ_QUESTIONS: FeatureQuizQuestion[] = [
  { answer: "55941954B82526344478572", display: "Barolong" },
  { answer: "55941954B50535260459809", display: "Bobonong" },
  { answer: "55941954B34591946516146", display: "Chobe" },
  { answer: "55941954B98371115502172", display: "Gaborone" },
  { answer: "55941954B31216508800768", display: "Gemsbok" },
  { answer: "55941954B82416766201839", display: "Ghanzi" },
  { answer: "55941954B76527564067138", display: "Hukunsti" },
  { answer: "55941954B56458887922680", display: "Kgatleng" },
  { answer: "55941954B84762067272179", display: "Kweneng North" },
  { answer: "55941954B98579419812372", display: "Kweneng South" },
  { answer: "55941954B49792364057910", display: "Lethlakane" },
  { answer: "55941954B28903282369970", display: "Machaneng" },
  { answer: "55941954B87089695796057", display: "Mahalapye" },
  { answer: "55941954B39393851070434", display: "Masungu" },
  { answer: "55941954B40687665076650", display: "Ngamiland East" },
  { answer: "55941954B78250687153975", display: "Ngamiland West" },
  { answer: "55941954B20262478145890", display: "Ngwaketse Central" },
  { answer: "55941954B26927140411587", display: "Ngwaketse North" },
  { answer: "55941954B49613130605683", display: "Ngwaketse South" },
  { answer: "55941954B44678367556360", display: "Palapye" },
  { answer: "55941954B86221332842775", display: "Serowe" },
  { answer: "55941954B89738474745599", display: "South East" },
  { answer: "55941954B45615354641166", display: "Tshabong" },
  { answer: "55941954B92705944270684", display: "Tuli" },
  { answer: "55941954B61152089533455", display: "Tutume" },
];
