"""
Generate Indonesia geographic-region and administrative quiz data for GeoPedia.

Purpose
-------
This script reads GeoPedia's canonical intermediate Indonesia GeoJSON files and
generates TypeScript question arrays for the five Indonesia boundary quizzes:

    Regions
    Provinces
    Regencies
    Sub-Districts
    Villages

The geographic regions are generated separately by:

    scripts/countries/indonesia/process/regions.py

The four administrative datasets are generated by:

    scripts/countries/indonesia/process/admin.py

Inputs
------
    data/intermediate/countries/indonesia/
        regions.geojson
        provinces.geojson
        regencies.geojson
        sub-districts.geojson
        villages.geojson

Outputs
-------
    src/quiz/quizzes/countries/asia/indonesia/data/
        admin.ts
        sub-districts.ts
        villages.ts

Output organization
-------------------
admin.ts:
    INDONESIA_REGION_QUESTIONS
    INDONESIA_PROVINCE_QUESTIONS
    INDONESIA_REGENCY_QUESTIONS

sub-districts.ts:
    INDONESIA_SUB_DISTRICT_QUESTIONS

villages.ts:
    INDONESIA_VILLAGE_QUESTIONS

Question answers
----------------
Every question uses the stable canonical ID stored in its GeoJSON as its answer:

    region_id
    province_id
    regency_id
    sub_district_id
    village_id

The human-readable geographic or administrative name is stored as display.

Region labels
-------------
The Regions quiz uses the Indonesian/native region name first and appends the
English name when it differs:

    Sumatera (Sumatra)
    Jawa (Java)
    Nusa Tenggara (Lesser Sunda Islands)
    Kalimantan
    Sulawesi
    Maluku (Maluku Islands)
    Papua (Western New Guinea)

The English name comes from region_english in regions.geojson.

region_english is intentionally needed only for the standalone Regions quiz.
It is not duplicated across the four lower administrative GeoJSON datasets.

Duplicate-name disambiguation
-----------------------------
Names that are globally unique are emitted normally:

    { answer: "ID...", display: "Name" }

When a name occurs more than once in an administrative dataset, its immediate
parent is appended to display:

    Regency:
        Name (Province)

    Sub-District:
        Name (Regency)

    Village:
        Name (Sub-District)

Only names that are actually duplicated receive the parent suffix.

Duplicate displays are explicitly allowed to remain for Sub-Districts and
Villages after immediate-parent disambiguation. The script does not append
additional hierarchy levels merely to force every display to be globally
unique.

Stable canonical IDs remain the actual unique quiz answers.

Requirements
------------
    pip install ijson

Run from the GeoPedia project root:

    python scripts/countries/indonesia/generate/admin-quiz-data.py

The generated TypeScript files should not be edited manually. Regenerate them
from the canonical intermediate GeoJSON whenever the source data changes.
"""

from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

import ijson


# ---------------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[4]

INPUT_DIRECTORY = (
    PROJECT_ROOT
    / "data"
    / "intermediate"
    / "countries"
    / "indonesia"
)

OUTPUT_DIRECTORY = (
    PROJECT_ROOT
    / "src"
    / "quiz"
    / "quizzes"
    / "countries"
    / "asia"
    / "indonesia"
    / "data"
)


# ---------------------------------------------------------------------------
# Dataset model
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class QuizDataset:
    """Configuration for one generated question array."""

    label: str
    input_path: Path
    output_path: Path
    constant_name: str
    id_property: str
    name_property: str
    parent_property: str | None
    expected_count: int
    use_region_english: bool = False
    allow_duplicate_displays: bool = False


ADMIN_OUTPUT = (
    OUTPUT_DIRECTORY
    / "admin.ts"
)

SUB_DISTRICT_OUTPUT = (
    OUTPUT_DIRECTORY
    / "sub-districts.ts"
)

VILLAGE_OUTPUT = (
    OUTPUT_DIRECTORY
    / "villages.ts"
)


REGIONS_DATASET = QuizDataset(
    label="Regions",
    input_path=INPUT_DIRECTORY / "regions.geojson",
    output_path=ADMIN_OUTPUT,
    constant_name="INDONESIA_REGION_QUESTIONS",
    id_property="region_id",
    name_property="region",
    parent_property=None,
    expected_count=7,
    use_region_english=True,
)

PROVINCES_DATASET = QuizDataset(
    label="Provinces",
    input_path=INPUT_DIRECTORY / "provinces.geojson",
    output_path=ADMIN_OUTPUT,
    constant_name="INDONESIA_PROVINCE_QUESTIONS",
    id_property="province_id",
    name_property="province",
    parent_property=None,
    expected_count=34,
)

REGENCIES_DATASET = QuizDataset(
    label="Regencies",
    input_path=INPUT_DIRECTORY / "regencies.geojson",
    output_path=ADMIN_OUTPUT,
    constant_name="INDONESIA_REGENCY_QUESTIONS",
    id_property="regency_id",
    name_property="regency",
    parent_property="province",
    expected_count=522,
)

SUB_DISTRICTS_DATASET = QuizDataset(
    label="Sub-Districts",
    input_path=INPUT_DIRECTORY / "sub-districts.geojson",
    output_path=SUB_DISTRICT_OUTPUT,
    constant_name="INDONESIA_SUB_DISTRICT_QUESTIONS",
    id_property="sub_district_id",
    name_property="sub_district",
    parent_property="regency",
    expected_count=7_069,
    allow_duplicate_displays=True,
)

VILLAGES_DATASET = QuizDataset(
    label="Villages",
    input_path=INPUT_DIRECTORY / "villages.geojson",
    output_path=VILLAGE_OUTPUT,
    constant_name="INDONESIA_VILLAGE_QUESTIONS",
    id_property="village_id",
    name_property="village",
    parent_property="sub_district",
    expected_count=81_912,
    allow_duplicate_displays=True,
)


DATASETS = (
    REGIONS_DATASET,
    PROVINCES_DATASET,
    REGENCIES_DATASET,
    SUB_DISTRICTS_DATASET,
    VILLAGES_DATASET,
)


# ---------------------------------------------------------------------------
# GeoJSON streaming
# ---------------------------------------------------------------------------

def stream_properties(
    path: Path,
) -> Iterator[dict[str, object]]:
    """Stream feature property objects from a GeoJSON FeatureCollection."""

    if not path.exists():
        raise FileNotFoundError(
            f"Required canonical GeoJSON not found:\n{path}"
        )

    with path.open(
        "rb",
    ) as file:
        for feature in ijson.items(
            file,
            "features.item",
        ):
            properties = feature.get(
                "properties"
            )

            if not isinstance(
                properties,
                dict,
            ):
                raise ValueError(
                    f"Feature in {path.name} has missing or malformed "
                    "properties."
                )

            yield properties


def require_string(
    properties: dict[str, object],
    property_name: str,
    *,
    dataset: QuizDataset,
) -> str:
    """Read a required non-empty canonical string property."""

    value = properties.get(
        property_name
    )

    if not isinstance(
        value,
        str,
    ):
        raise ValueError(
            f"{dataset.label} contains non-string "
            f"{property_name!r}: {value!r}"
        )

    value = value.strip()

    if not value:
        raise ValueError(
            f"{dataset.label} contains blank {property_name!r}."
        )

    return value


# ---------------------------------------------------------------------------
# Question generation
# ---------------------------------------------------------------------------

def count_names(
    dataset: QuizDataset,
) -> tuple[Counter[str], int]:
    """Count names so globally duplicated names can be disambiguated."""

    names: Counter[str] = Counter()
    count = 0

    for properties in stream_properties(
        dataset.input_path
    ):
        name = require_string(
            properties,
            dataset.name_property,
            dataset=dataset,
        )

        names[
            name
        ] += 1

        count += 1

    if count != dataset.expected_count:
        raise ValueError(
            f"{dataset.label} feature-count mismatch: "
            f"expected {dataset.expected_count:,}, got {count:,}."
        )

    return (
        names,
        count,
    )


def make_display(
    properties: dict[str, object],
    dataset: QuizDataset,
    name_counts: Counter[str],
) -> str:
    """Create the display string for one quiz question."""

    name = require_string(
        properties,
        dataset.name_property,
        dataset=dataset,
    )

    if dataset.use_region_english:
        english_name = require_string(
            properties,
            "region_english",
            dataset=dataset,
        )

        if english_name == name:
            return name

        return (
            f"{name} ({english_name})"
        )

    if (
        name_counts[name] == 1
        or dataset.parent_property is None
    ):
        return name

    parent = require_string(
        properties,
        dataset.parent_property,
        dataset=dataset,
    )

    return (
        f"{name} ({parent})"
    )


def typescript_string(
    value: str,
) -> str:
    """Encode a Python string as a valid TypeScript string literal."""

    return json.dumps(
        value,
        ensure_ascii=False,
    )


def build_questions(
    dataset: QuizDataset,
) -> tuple[list[tuple[str, str]], int, int]:
    """
    Build one dataset's question records.

    Returns:
        questions
        number of globally duplicated source names
        number of duplicate displays remaining after disambiguation
    """

    (
        name_counts,
        count,
    ) = count_names(
        dataset
    )

    duplicate_source_names = sum(
        1
        for occurrence_count in name_counts.values()
        if occurrence_count > 1
    )

    questions: list[
        tuple[
            str,
            str,
        ]
    ] = []

    answer_ids: set[str] = set()
    display_counts: Counter[str] = Counter()

    for properties in stream_properties(
        dataset.input_path
    ):
        answer = require_string(
            properties,
            dataset.id_property,
            dataset=dataset,
        )

        if answer in answer_ids:
            raise ValueError(
                f"{dataset.label} contains duplicate answer ID "
                f"{answer!r}."
            )

        answer_ids.add(
            answer
        )

        display = make_display(
            properties,
            dataset,
            name_counts,
        )

        questions.append(
            (
                answer,
                display,
            )
        )

        display_counts[
            display
        ] += 1

    if len(
        questions
    ) != count:
        raise ValueError(
            f"{dataset.label} changed between generation passes."
        )

    duplicate_displays = sum(
        1
        for occurrence_count in display_counts.values()
        if occurrence_count > 1
    )

    if (
        duplicate_displays > 0
        and not dataset.allow_duplicate_displays
    ):
        examples = [
            display
            for (
                display,
                occurrence_count,
            ) in display_counts.items()
            if occurrence_count > 1
        ][:10]

        raise ValueError(
            f"{dataset.label} still contains "
            f"{duplicate_displays:,} duplicate display value(s) after "
            f"parent disambiguation.\n"
            f"Examples: {examples}"
        )

    return (
        questions,
        duplicate_source_names,
        duplicate_displays,
    )


# ---------------------------------------------------------------------------
# TypeScript writing
# ---------------------------------------------------------------------------

def question_array_source(
    constant_name: str,
    questions: list[tuple[str, str]],
) -> str:
    """Create one FeatureQuizQuestion[] TypeScript constant."""

    lines = [
        f"export const {constant_name}: FeatureQuizQuestion[] = ["
    ]

    for (
        answer,
        display,
    ) in questions:
        lines.append(
            "  { "
            f"answer: {typescript_string(answer)}, "
            f"display: {typescript_string(display)} "
            "},"
        )

    lines.append(
        "];"
    )

    return "\n".join(
        lines
    )


def file_header(
    *,
    description: str,
    generator_path: str,
) -> str:
    """Create the standard generated TypeScript file header."""

    return (
        "/**\n"
        f" * {description}\n"
        " *\n"
        " * AUTO-GENERATED FILE.\n"
        " * Do not edit manually. Regenerate with:\n"
        f" *   python {generator_path}\n"
        " */\n"
        "\n"
        'import { FeatureQuizQuestion } from "@/types/quiz";\n'
    )


def write_typescript_file(
    path: Path,
    *,
    description: str,
    datasets: tuple[QuizDataset, ...],
    generated: dict[str, list[tuple[str, str]]],
) -> None:
    """Write generated question arrays for the supplied datasets."""

    generator_path = (
        "scripts/countries/indonesia/generate/"
        "admin-quiz-data.py"
    )

    sections = [
        file_header(
            description=description,
            generator_path=generator_path,
        )
    ]

    for dataset in datasets:
        sections.append(
            question_array_source(
                dataset.constant_name,
                generated[
                    dataset.constant_name
                ],
            )
        )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_text(
        "\n\n".join(
            sections
        )
        + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    """Generate all Indonesia geographic and administrative quiz data."""

    print(
        "Generating Indonesia geographic and administrative quiz data..."
    )
    print()

    generated: dict[
        str,
        list[tuple[str, str]]
    ] = {}

    for dataset in DATASETS:
        print(
            f"Processing {dataset.label}..."
        )

        (
            questions,
            duplicate_source_names,
            duplicate_displays,
        ) = build_questions(
            dataset
        )

        generated[
            dataset.constant_name
        ] = questions

        print(
            f"  Questions:              {len(questions):,}"
        )
        print(
            f"  Duplicate source names: {duplicate_source_names:,}"
        )
        print(
            f"  Duplicate displays:     {duplicate_displays:,}"
        )

        if (
            duplicate_displays
            and dataset.allow_duplicate_displays
        ):
            print(
                "  Duplicate displays are allowed for this dataset."
            )

        print()

    write_typescript_file(
        ADMIN_OUTPUT,
        description=(
            "Indonesia region, province, and regency quiz-question data."
        ),
        datasets=(
            REGIONS_DATASET,
            PROVINCES_DATASET,
            REGENCIES_DATASET,
        ),
        generated=generated,
    )

    write_typescript_file(
        SUB_DISTRICT_OUTPUT,
        description=(
            "Indonesia sub-district quiz-question data."
        ),
        datasets=(
            SUB_DISTRICTS_DATASET,
        ),
        generated=generated,
    )

    write_typescript_file(
        VILLAGE_OUTPUT,
        description=(
            "Indonesia village quiz-question data."
        ),
        datasets=(
            VILLAGES_DATASET,
        ),
        generated=generated,
    )

    print(
        "=" * 78
    )
    print(
        "Indonesia geographic and administrative quiz-data generation complete."
    )
    print(
        "=" * 78
    )
    print()

    for path in (
        ADMIN_OUTPUT,
        SUB_DISTRICT_OUTPUT,
        VILLAGE_OUTPUT,
    ):
        print(
            f"  {path.relative_to(PROJECT_ROOT)}"
        )


if __name__ == "__main__":
    main()