"""
Simplify Indonesia geographic and administrative boundaries for GeoPedia.

Purpose
-------
This script uses Mapshaper to simplify the canonical intermediate Indonesia
geographic-region and administrative-boundary datasets into the public GeoJSON
files used by GeoPedia's maps.

The region layer is generated by:

    scripts/countries/indonesia/process/regions.py

The four administrative layers are generated by:

    scripts/countries/indonesia/process/admin.py

Run this script after both processing scripts have completed successfully.

Inputs
------
    data/intermediate/countries/indonesia/
        regions.geojson
        provinces.geojson
        regencies.geojson
        sub-districts.geojson
        villages.geojson

Outputs
-------
    public/data/countries/indonesia/geojson/
        regions.geojson
        provinces.geojson
        regencies.geojson
        sub-districts.geojson
        villages.geojson

Simplification
--------------
Mapshaper's weighted simplification is used with keep-shapes so small
administrative areas and islands are not intentionally removed.

Current retained-detail percentages:

    Regions:          2.0%
    Provinces:        2.0%
    Regencies:        1.0%
    Sub-Districts:    1.5%
    Villages:         3.7%

The Province, Regency, Sub-District, and Village percentages were tuned against
GeoPedia's Indonesia datasets and should not be changed without inspecting the
resulting map geometry.

The Region percentage begins at 2.0%. Because the region layer contains only
seven large dissolved features but retains Indonesia's complicated island and
coastline geometry, its final public size and visual quality should be
inspected before deciding whether further simplification is useful.

The public villages.geojson should remain below GitHub's 50 MB warning
threshold. GeoPedia's current target is approximately 48-50 MB while
preserving as much useful boundary detail as possible.

Feature counts are validated after simplification:

    Regions:             7
    Provinces:          34
    Regencies:         522
    Sub-Districts:   7,069
    Villages:       81,912

Geometry types are also checked after simplification. Every output feature must
remain Polygon or MultiPolygon.

Pipeline
--------
Run the Indonesia processing pipeline from the GeoPedia project root:

    python scripts/countries/indonesia/process/regions.py
    python scripts/countries/indonesia/process/admin.py
    python scripts/countries/indonesia/process/simplify-admin.py
    python scripts/countries/indonesia/generate/admin-quiz-data.py

Requirements
------------
Mapshaper must be available through npx.

On Windows the script automatically uses npx.cmd.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path
from typing import Any

import ijson


# ---------------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[4]

INPUT_DIRECTORY = (
    PROJECT_ROOT
    / "data"
    / "intermediate"
    / "countries"
    / "indonesia"
)

OUTPUT_DIRECTORY = (
    PROJECT_ROOT
    / "public"
    / "data"
    / "countries"
    / "indonesia"
    / "geojson"
)


# ---------------------------------------------------------------------------
# Dataset configuration
# ---------------------------------------------------------------------------

DATASETS = (
    {
        "label": "Regions",
        "input": INPUT_DIRECTORY / "regions.geojson",
        "output": OUTPUT_DIRECTORY / "regions.geojson",
        "percentage": "2%",
        "expected_count": 7,
    },
    {
        "label": "Provinces",
        "input": INPUT_DIRECTORY / "provinces.geojson",
        "output": OUTPUT_DIRECTORY / "provinces.geojson",
        "percentage": "2%",
        "expected_count": 34,
    },
    {
        "label": "Regencies",
        "input": INPUT_DIRECTORY / "regencies.geojson",
        "output": OUTPUT_DIRECTORY / "regencies.geojson",
        "percentage": "1%",
        "expected_count": 522,
    },
    {
        "label": "Sub-Districts",
        "input": INPUT_DIRECTORY / "sub-districts.geojson",
        "output": OUTPUT_DIRECTORY / "sub-districts.geojson",
        "percentage": "1.5%",
        "expected_count": 7_069,
    },
    {
        "label": "Villages",
        "input": INPUT_DIRECTORY / "villages.geojson",
        "output": OUTPUT_DIRECTORY / "villages.geojson",
        "percentage": "3.7%",
        "expected_count": 81_912,
    },
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def find_npx() -> str:
    """Find the platform-appropriate npx executable."""

    executable = (
        "npx.cmd"
        if os.name == "nt"
        else "npx"
    )

    resolved = shutil.which(
        executable
    )

    if resolved is None:
        raise RuntimeError(
            f"Could not find {executable!r}. "
            "Install Node.js/npm or make sure npx is available on PATH."
        )

    return resolved


def file_size_mb(
    path: Path,
) -> float:
    """Return a file's size in MiB."""

    return (
        path.stat().st_size
        / (1024 * 1024)
    )


def count_features(
    path: Path,
) -> int:
    """Count GeoJSON features without loading the entire file into memory."""

    count = 0

    with path.open(
        "rb",
    ) as file:
        for _ in ijson.items(
            file,
            "features.item",
        ):
            count += 1

    return count


def read_geometry_type_counts(
    path: Path,
) -> dict[str, int]:
    """Count geometry types in a GeoJSON file by streaming its features."""

    counts: dict[str, int] = {}

    with path.open(
        "rb",
    ) as file:
        for feature in ijson.items(
            file,
            "features.item",
        ):
            geometry = feature.get(
                "geometry"
            )

            if not isinstance(
                geometry,
                dict,
            ):
                geometry_type = "Missing"

            else:
                geometry_type = geometry.get(
                    "type",
                    "Unknown",
                )

            geometry_type_string = str(
                geometry_type
            )

            counts[
                geometry_type_string
            ] = (
                counts.get(
                    geometry_type_string,
                    0,
                )
                + 1
            )

    return counts


def validate_geojson(
    path: Path,
    *,
    expected_count: int,
    label: str,
) -> tuple[int, dict[str, int]]:
    """Validate the basic structure and feature count of a public GeoJSON."""

    if not path.exists():
        raise RuntimeError(
            f"{label} output was not created:\n{path}"
        )

    if path.stat().st_size == 0:
        raise RuntimeError(
            f"{label} output is empty:\n{path}"
        )

    with path.open(
        "r",
        encoding="utf-8",
    ) as file:
        prefix = file.read(
            1
        )

    if prefix != "{":
        raise RuntimeError(
            f"{label} output does not appear to be a GeoJSON object."
        )

    count = count_features(
        path
    )

    if count != expected_count:
        raise RuntimeError(
            f"{label} feature-count mismatch after simplification: "
            f"expected {expected_count:,}, got {count:,}."
        )

    geometry_types = read_geometry_type_counts(
        path
    )

    if (
        "Missing" in geometry_types
        or "Unknown" in geometry_types
    ):
        raise RuntimeError(
            f"{label} contains missing or unknown geometry."
        )

    unexpected_geometry_types = set(
        geometry_types
    ) - {
        "Polygon",
        "MultiPolygon",
    }

    if unexpected_geometry_types:
        raise RuntimeError(
            f"{label} contains unexpected geometry types: "
            f"{sorted(unexpected_geometry_types)}"
        )

    return (
        count,
        geometry_types,
    )


def find_dataset(
    label: str,
) -> dict[str, Any]:
    """Return a configured dataset by its label."""

    for dataset in DATASETS:
        if dataset["label"] == label:
            return dataset

    raise RuntimeError(
        f"Dataset configuration not found for {label!r}."
    )


# ---------------------------------------------------------------------------
# Mapshaper
# ---------------------------------------------------------------------------

def simplify_dataset(
    npx: str,
    dataset: dict[str, Any],
) -> None:
    """Simplify one canonical geographic or administrative dataset."""

    input_path: Path = dataset[
        "input"
    ]

    output_path: Path = dataset[
        "output"
    ]

    if not input_path.exists():
        raise FileNotFoundError(
            f"Required intermediate file not found:\n{input_path}"
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # Remove a previous output before invoking Mapshaper so a failed command
    # cannot accidentally leave us validating an older public file.
    if output_path.exists():
        output_path.unlink()

    command = [
        npx,
        "mapshaper",
        str(
            input_path
        ),
        "-simplify",
        "weighted",
        dataset["percentage"],
        "keep-shapes",
        "-o",
        "format=geojson",
        "precision=0.000001",
        str(
            output_path
        ),
    ]

    print(
        f"Simplifying {dataset['label']}..."
    )
    print(
        f"  Detail retained: {dataset['percentage']}"
    )
    print(
        f"  Input size:      {file_size_mb(input_path):,.2f} MB"
    )

    subprocess.run(
        command,
        cwd=PROJECT_ROOT,
        check=True,
    )

    (
        count,
        geometry_types,
    ) = validate_geojson(
        output_path,
        expected_count=dataset["expected_count"],
        label=dataset["label"],
    )

    print(
        f"  Features:        {count:,}"
    )

    geometry_summary = ", ".join(
        f"{geometry_type}: {geometry_count:,}"
        for (
            geometry_type,
            geometry_count,
        ) in sorted(
            geometry_types.items()
        )
    )

    print(
        f"  Geometry:        {geometry_summary}"
    )
    print(
        f"  Output size:     {file_size_mb(output_path):,.2f} MB"
    )
    print(
        f"  Output:          {output_path.relative_to(PROJECT_ROOT)}"
    )
    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    """Simplify all Indonesia geographic and administrative datasets."""

    print(
        "Simplifying Indonesia geographic and administrative boundaries..."
    )
    print()

    npx = find_npx()

    OUTPUT_DIRECTORY.mkdir(
        parents=True,
        exist_ok=True,
    )

    for dataset in DATASETS:
        simplify_dataset(
            npx,
            dataset,
        )

    print(
        "=" * 78
    )
    print(
        "Indonesia boundary simplification complete."
    )
    print(
        "=" * 78
    )
    print()

    print(
        "Final public file sizes:"
    )

    for dataset in DATASETS:
        print(
            f"  {dataset['label']:<15} "
            f"{file_size_mb(dataset['output']):>8.2f} MB"
        )

    village_dataset = find_dataset(
        "Villages"
    )

    village_size = file_size_mb(
        village_dataset["output"]
    )

    print()

    if village_size < 48:
        print(
            "Villages are below the 48-50 MB target. "
            "The simplification percentage can likely be increased."
        )

    elif village_size < 50:
        print(
            "Villages are within the desired 48-50 MB range."
        )

    else:
        print(
            "Villages are at or above 50 MB. "
            "The simplification percentage should be decreased."
        )


if __name__ == "__main__":
    main()