/**
 * AUTO-GENERATED FILE.
 *
 * Generated by:
 *
 *   scripts/countries/usa/generate/generate-state-flags-quiz.ts
 *
 * Do not edit the question list manually. Update the canonical U.S.
 * subdivision-name mapping, state flag assets, or generator and rerun the
 * script instead.
 */

import type { FeatureQuiz } from "@/types/quiz";

/**
 * Description shown for the U.S. State Flags quiz.
 */
const US_STATES_FLAGS_DESCRIPTION =
  "Learn the flags of all 50 U.S. states by identifying each state on the map.";

/**
 * Questions used by the U.S. State Flags quiz.
 *
 * Each answer is the full state name because the shared U.S. states map
 * identifies features through its `name` property. Postal abbreviations are
 * used only to resolve the corresponding flag SVG.
 */
const US_STATE_FLAG_QUESTIONS: FeatureQuiz["questions"] = [
  {
    answer: "Alabama",
    display: "Alabama",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/al.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Alaska",
    display: "Alaska",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ak.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Arizona",
    display: "Arizona",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/az.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Arkansas",
    display: "Arkansas",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ar.svg",
      alt: "State flag",
    },
  },
  {
    answer: "California",
    display: "California",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ca.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Colorado",
    display: "Colorado",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/co.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Connecticut",
    display: "Connecticut",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ct.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Delaware",
    display: "Delaware",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/de.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Florida",
    display: "Florida",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/fl.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Georgia",
    display: "Georgia",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ga.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Hawaii",
    display: "Hawaii",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/hi.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Idaho",
    display: "Idaho",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/id.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Illinois",
    display: "Illinois",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/il.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Indiana",
    display: "Indiana",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/in.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Iowa",
    display: "Iowa",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ia.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Kansas",
    display: "Kansas",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ks.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Kentucky",
    display: "Kentucky",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ky.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Louisiana",
    display: "Louisiana",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/la.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Maine",
    display: "Maine",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/me.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Maryland",
    display: "Maryland",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/md.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Massachusetts",
    display: "Massachusetts",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ma.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Michigan",
    display: "Michigan",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/mi.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Minnesota",
    display: "Minnesota",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/mn.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Mississippi",
    display: "Mississippi",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ms.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Missouri",
    display: "Missouri",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/mo.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Montana",
    display: "Montana",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/mt.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Nebraska",
    display: "Nebraska",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ne.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Nevada",
    display: "Nevada",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/nv.svg",
      alt: "State flag",
    },
  },
  {
    answer: "New Hampshire",
    display: "New Hampshire",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/nh.svg",
      alt: "State flag",
    },
  },
  {
    answer: "New Jersey",
    display: "New Jersey",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/nj.svg",
      alt: "State flag",
    },
  },
  {
    answer: "New Mexico",
    display: "New Mexico",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/nm.svg",
      alt: "State flag",
    },
  },
  {
    answer: "New York",
    display: "New York",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ny.svg",
      alt: "State flag",
    },
  },
  {
    answer: "North Carolina",
    display: "North Carolina",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/nc.svg",
      alt: "State flag",
    },
  },
  {
    answer: "North Dakota",
    display: "North Dakota",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/nd.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Ohio",
    display: "Ohio",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/oh.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Oklahoma",
    display: "Oklahoma",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ok.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Oregon",
    display: "Oregon",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/or.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Pennsylvania",
    display: "Pennsylvania",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/pa.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Rhode Island",
    display: "Rhode Island",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ri.svg",
      alt: "State flag",
    },
  },
  {
    answer: "South Carolina",
    display: "South Carolina",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/sc.svg",
      alt: "State flag",
    },
  },
  {
    answer: "South Dakota",
    display: "South Dakota",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/sd.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Tennessee",
    display: "Tennessee",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/tn.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Texas",
    display: "Texas",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/tx.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Utah",
    display: "Utah",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/ut.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Vermont",
    display: "Vermont",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/vt.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Virginia",
    display: "Virginia",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/va.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Washington",
    display: "Washington",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/wa.svg",
      alt: "State flag",
    },
  },
  {
    answer: "West Virginia",
    display: "West Virginia",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/wv.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Wisconsin",
    display: "Wisconsin",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/wi.svg",
      alt: "State flag",
    },
  },
  {
    answer: "Wyoming",
    display: "Wyoming",
    prompt: {
      type: "image",
      imageUrl: "/data/countries/usa/flags/wy.svg",
      alt: "State flag",
    },
  },
];

/**
 * Tests recognition of the flags of all 50 U.S. states.
 */
export const usStateFlagsQuiz: FeatureQuiz = {
  id: "us-state-flags",
  name: "State Flags",
  description: US_STATES_FLAGS_DESCRIPTION,

  kind: "feature",
  mapId: "us-states",

  answerProperty: "name",
  answerType: "single",

  grouping: {
    properties: [
      {
        property: "region",
        label: "Region",
        valueType: "string",
      },
    ],
  },

  questions: US_STATE_FLAG_QUESTIONS,
};
