"""
Simplify Malaysia's canonical administrative GeoJSON for public map use.

This script takes the unsimplified administrative hierarchy generated by
process/admin.py and creates smaller GeoJSON files suitable for GeoPedia's
MapLibre maps and quizzes.

Each administrative level has an independent coordinate-retention percentage
so visual quality and file size can be tuned separately.

Simplification uses Shapely's topology-preserving simplify operation. A
tolerance is estimated for each dataset by searching for a value that produces
approximately the requested percentage of the original coordinates.

The script validates that simplification:
- Preserves every feature
- Preserves feature IDs, names, and hierarchy properties
- Produces no missing or empty geometries
- Produces no invalid geometries

It reports original and simplified coordinate counts and actual file sizes.

Inputs
------
data/intermediate/countries/malaysia/states.geojson
data/intermediate/countries/malaysia/districts.geojson
data/intermediate/countries/malaysia/sub-districts.geojson

Outputs
-------
public/data/countries/malaysia/geojson/states.geojson
public/data/countries/malaysia/geojson/districts.geojson
public/data/countries/malaysia/geojson/sub-districts.geojson

Run from the GeoPedia project root:

    python scripts/countries/asia/malaysia/process/simplify-admin.py
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import geopandas as gpd
from shapely.geometry.base import BaseGeometry


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[5]

INTERMEDIATE_DIR = (
    PROJECT_ROOT
    / "data"
    / "intermediate"
    / "countries"
    / "malaysia"
)

PUBLIC_DIR = (
    PROJECT_ROOT
    / "public"
    / "data"
    / "countries"
    / "malaysia"
    / "geojson"
)

STATES_INPUT_PATH = INTERMEDIATE_DIR / "states.geojson"
DISTRICTS_INPUT_PATH = INTERMEDIATE_DIR / "districts.geojson"
SUB_DISTRICTS_INPUT_PATH = INTERMEDIATE_DIR / "sub-districts.geojson"

STATES_OUTPUT_PATH = PUBLIC_DIR / "states.geojson"
DISTRICTS_OUTPUT_PATH = PUBLIC_DIR / "districts.geojson"
SUB_DISTRICTS_OUTPUT_PATH = PUBLIC_DIR / "sub-districts.geojson"


# ---------------------------------------------------------------------------
# Simplification settings
# ---------------------------------------------------------------------------

STATE_RETAIN_PERCENT = 5.0
DISTRICT_RETAIN_PERCENT = 20.0
SUB_DISTRICT_RETAIN_PERCENT = 10.0

# Number of binary-search iterations used to find a simplification tolerance
# close to each requested coordinate-retention percentage.
TOLERANCE_SEARCH_ITERATIONS = 24


# ---------------------------------------------------------------------------
# Dataset configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class DatasetConfig:
    """Defines one administrative dataset to simplify."""

    label: str
    input_path: Path
    output_path: Path
    retain_percent: float
    id_property: str
    expected_properties: tuple[str, ...]


DATASETS = (
    DatasetConfig(
        label="States",
        input_path=STATES_INPUT_PATH,
        output_path=STATES_OUTPUT_PATH,
        retain_percent=STATE_RETAIN_PERCENT,
        id_property="state_id",
        expected_properties=(
            "state_id",
            "state",
        ),
    ),
    DatasetConfig(
        label="Districts",
        input_path=DISTRICTS_INPUT_PATH,
        output_path=DISTRICTS_OUTPUT_PATH,
        retain_percent=DISTRICT_RETAIN_PERCENT,
        id_property="district_id",
        expected_properties=(
            "district_id",
            "district",
            "state_id",
            "state",
        ),
    ),
    DatasetConfig(
        label="Sub-Districts",
        input_path=SUB_DISTRICTS_INPUT_PATH,
        output_path=SUB_DISTRICTS_OUTPUT_PATH,
        retain_percent=SUB_DISTRICT_RETAIN_PERCENT,
        id_property="sub_district_id",
        expected_properties=(
            "sub_district_id",
            "sub_district",
            "district_id",
            "district",
            "state_id",
            "state",
        ),
    ),
)


# ---------------------------------------------------------------------------
# Coordinate helpers
# ---------------------------------------------------------------------------


def count_geometry_coordinates(
    geometry: BaseGeometry,
) -> int:
    """Count coordinate positions contained in a Shapely geometry."""

    if geometry.is_empty:
        return 0

    geometry_type = geometry.geom_type

    if geometry_type == "Polygon":
        count = len(geometry.exterior.coords)

        for interior in geometry.interiors:
            count += len(interior.coords)

        return count

    if geometry_type == "MultiPolygon":
        return sum(
            count_geometry_coordinates(polygon)
            for polygon in geometry.geoms
        )

    if geometry_type == "GeometryCollection":
        return sum(
            count_geometry_coordinates(part)
            for part in geometry.geoms
        )

    if hasattr(geometry, "coords"):
        return len(geometry.coords)

    return 0


def count_frame_coordinates(
    frame: gpd.GeoDataFrame,
) -> int:
    """Count all coordinate positions in a GeoDataFrame."""

    return sum(
        count_geometry_coordinates(geometry)
        for geometry in frame.geometry
    )


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def load_dataset(
    config: DatasetConfig,
) -> gpd.GeoDataFrame:
    """Load and validate one canonical intermediate GeoJSON dataset."""

    if not config.input_path.exists():
        raise FileNotFoundError(
            f"Missing intermediate file: {config.input_path}"
        )

    frame = gpd.read_file(
        config.input_path
    )

    actual_properties = tuple(
        column
        for column in frame.columns
        if column != "geometry"
    )

    if actual_properties != config.expected_properties:
        raise ValueError(
            f"{config.label} properties do not match the expected schema.\n"
            f"Expected: {config.expected_properties}\n"
            f"Actual:   {actual_properties}"
        )

    if frame[config.id_property].isna().any():
        raise ValueError(
            f"{config.label} contains missing {config.id_property} values."
        )

    if frame[config.id_property].duplicated().any():
        raise ValueError(
            f"{config.label} contains duplicate {config.id_property} values."
        )

    if frame.geometry.isna().any():
        raise ValueError(
            f"{config.label} contains missing geometries."
        )

    if frame.geometry.is_empty.any():
        raise ValueError(
            f"{config.label} contains empty geometries."
        )

    invalid_count = int(
        (~frame.geometry.is_valid).sum()
    )

    if invalid_count:
        raise ValueError(
            f"{config.label} contains {invalid_count:,} invalid "
            f"intermediate geometries."
        )

    return frame


# ---------------------------------------------------------------------------
# Simplification
# ---------------------------------------------------------------------------


def simplify_frame(
    frame: gpd.GeoDataFrame,
    tolerance: float,
) -> gpd.GeoDataFrame:
    """Simplify every geometry using a topology-preserving tolerance."""

    simplified = frame.copy()

    simplified["geometry"] = simplified.geometry.simplify(
        tolerance,
        preserve_topology=True,
    )

    return simplified


def find_simplification_tolerance(
    frame: gpd.GeoDataFrame,
    retain_percent: float,
) -> tuple[float, gpd.GeoDataFrame]:
    """
    Find a tolerance that approximately reaches a coordinate-retention target.

    A binary search is performed over a tolerance derived from the dataset's
    geographic extent. The closest valid result encountered during the search
    is returned.
    """

    if not 0.0 < retain_percent <= 100.0:
        raise ValueError(
            f"Retention percentage must be > 0 and <= 100; "
            f"received {retain_percent}."
        )

    original_coordinate_count = count_frame_coordinates(
        frame
    )

    target_coordinate_count = (
        original_coordinate_count
        * retain_percent
        / 100.0
    )

    if retain_percent == 100.0:
        return 0.0, frame.copy()

    min_x, min_y, max_x, max_y = frame.total_bounds

    extent = max(
        max_x - min_x,
        max_y - min_y,
    )

    if extent <= 0:
        raise ValueError(
            "Cannot determine simplification tolerance from a zero-size "
            "dataset extent."
        )

    low = 0.0
    high = extent

    best_tolerance = 0.0
    best_frame = frame.copy()
    best_difference = abs(
        original_coordinate_count
        - target_coordinate_count
    )

    for _ in range(
        TOLERANCE_SEARCH_ITERATIONS
    ):
        tolerance = (
            low + high
        ) / 2.0

        candidate = simplify_frame(
            frame,
            tolerance,
        )

        if (
            candidate.geometry.isna().any()
            or candidate.geometry.is_empty.any()
            or (~candidate.geometry.is_valid).any()
        ):
            high = tolerance
            continue

        coordinate_count = count_frame_coordinates(
            candidate
        )

        difference = abs(
            coordinate_count
            - target_coordinate_count
        )

        if difference < best_difference:
            best_difference = difference
            best_tolerance = tolerance
            best_frame = candidate

        # More coordinates than desired means simplification is not yet
        # aggressive enough, so increase the tolerance.
        if coordinate_count > target_coordinate_count:
            low = tolerance
        else:
            high = tolerance

    return (
        best_tolerance,
        best_frame,
    )


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate_simplified_dataset(
    original: gpd.GeoDataFrame,
    simplified: gpd.GeoDataFrame,
    config: DatasetConfig,
) -> None:
    """
    Ensure simplification changed geometry only.

    Feature count, feature ordering, IDs, names, and hierarchy properties must
    remain exactly the same as the canonical intermediate dataset.
    """

    if len(simplified) != len(original):
        raise ValueError(
            f"{config.label} feature count changed during simplification: "
            f"{len(original):,} -> {len(simplified):,}."
        )

    for property_name in config.expected_properties:
        original_values = (
            original[property_name]
            .astype(str)
            .tolist()
        )

        simplified_values = (
            simplified[property_name]
            .astype(str)
            .tolist()
        )

        if original_values != simplified_values:
            raise ValueError(
                f"{config.label} property {property_name!r} changed during "
                f"simplification."
            )

    if simplified.geometry.isna().any():
        raise ValueError(
            f"{config.label} contains missing simplified geometries."
        )

    if simplified.geometry.is_empty.any():
        raise ValueError(
            f"{config.label} contains empty simplified geometries."
        )

    invalid_count = int(
        (~simplified.geometry.is_valid).sum()
    )

    if invalid_count:
        raise ValueError(
            f"{config.label} contains {invalid_count:,} invalid simplified "
            f"geometries."
        )


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------


def write_geojson(
    frame: gpd.GeoDataFrame,
    path: Path,
) -> None:
    """Write a compact UTF-8 GeoJSON file."""

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    geojson: dict[str, Any] = json.loads(
        frame.to_json(
            drop_id=True,
        )
    )

    path.write_text(
        json.dumps(
            geojson,
            ensure_ascii=False,
            separators=(",", ":"),
        ),
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------


def format_bytes(
    size: int,
) -> str:
    """Format a byte count using readable binary units."""

    if size < 1024:
        return f"{size:,} B"

    if size < 1024**2:
        return f"{size / 1024:.2f} KiB"

    return f"{size / 1024**2:.2f} MiB"


def print_report(
    config: DatasetConfig,
    original: gpd.GeoDataFrame,
    simplified: gpd.GeoDataFrame,
    tolerance: float,
    original_size: int,
    simplified_size: int,
) -> None:
    """Print simplification statistics for one administrative level."""

    original_coordinates = count_frame_coordinates(
        original
    )

    simplified_coordinates = count_frame_coordinates(
        simplified
    )

    actual_retention = (
        simplified_coordinates
        / original_coordinates
        * 100.0
    )

    coordinates_removed = (
        100.0
        - actual_retention
    )

    size_retention = (
        simplified_size
        / original_size
        * 100.0
    )

    size_reduction = (
        100.0
        - size_retention
    )

    print()
    print(config.label)
    print("-" * len(config.label))
    print(
        f"  Features: {len(original):,}"
    )
    print(
        f"  Target coordinate retention: "
        f"{config.retain_percent:.1f}%"
    )
    print(
        f"  Simplification tolerance: "
        f"{tolerance:.10f}"
    )
    print(
        f"  Coordinates: "
        f"{original_coordinates:,} -> "
        f"{simplified_coordinates:,}"
    )
    print(
        f"  Actual coordinate retention: "
        f"{actual_retention:.2f}%"
    )
    print(
        f"  Coordinates removed: "
        f"{coordinates_removed:.2f}%"
    )
    print(
        f"  File size: "
        f"{format_bytes(original_size)} -> "
        f"{format_bytes(simplified_size)}"
    )
    print(
        f"  File-size reduction: "
        f"{size_reduction:.2f}%"
    )
    print(
        "  Invalid geometries: 0 -> 0"
    )


# ---------------------------------------------------------------------------
# Processing
# ---------------------------------------------------------------------------


def process_dataset(
    config: DatasetConfig,
) -> None:
    """Simplify, validate, write, and report one administrative dataset."""

    original = load_dataset(
        config
    )

    original_size = config.input_path.stat().st_size

    tolerance, simplified = find_simplification_tolerance(
        original,
        config.retain_percent,
    )

    validate_simplified_dataset(
        original,
        simplified,
        config,
    )

    write_geojson(
        simplified,
        config.output_path,
    )

    simplified_size = config.output_path.stat().st_size

    print_report(
        config=config,
        original=original,
        simplified=simplified,
        tolerance=tolerance,
        original_size=original_size,
        simplified_size=simplified_size,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    """Simplify all Malaysian administrative boundary datasets."""

    print()
    print("Simplifying Malaysia administrative boundaries...")

    for config in DATASETS:
        process_dataset(
            config
        )

    print()
    print("Public GeoJSON:")
    print(
        "  "
        + str(
            STATES_OUTPUT_PATH.relative_to(
                PROJECT_ROOT
            )
        )
    )
    print(
        "  "
        + str(
            DISTRICTS_OUTPUT_PATH.relative_to(
                PROJECT_ROOT
            )
        )
    )
    print(
        "  "
        + str(
            SUB_DISTRICTS_OUTPUT_PATH.relative_to(
                PROJECT_ROOT
            )
        )
    )

    print()
    print("Malaysia administrative simplification complete.")


if __name__ == "__main__":
    main()