import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Aruba.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const abw: CountryData = {
  id: "abw",
  name: "Aruba",
  officialName: "Aruba",
  continent: "North America",
  region: "Caribbean",
  callingCode: "297",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/abw.svg",
  imageUrl: "/data/global/countries/silhouettes/abw.svg",
  capital: "Oranjestad",
  population: 110625,
};
