import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Angola.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ago: CountryData = {
  id: "ago",
  name: "Angola",
  officialName: "Republic of Angola",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "244",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/ago.svg",
  imageUrl: "/data/global/countries/silhouettes/ago.svg",
  capital: "Luanda",
  population: 38778554,
};
