import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Anguilla.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const aia: CountryData = {
  id: "aia",
  name: "Anguilla",
  officialName: "Anguilla",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/country-flags/aia.svg",
  imageUrl: "/data/country-images/aia.svg",
  capital: "The Valley",
  population: 16010,
};
