import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Åland Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ala: CountryData = {
  id: "ala",
  name: "Åland Islands",
  officialName: "Åland Islands",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "358",
  drivingSide: "right",
  flagUrl: "/data/country-flags/ala.svg",
  imageUrl: "/data/country-images/ala.svg",
  capital: "Mariehamn",
  population: 30654,
};
