import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Andorra.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const and: CountryData = {
  id: "and",
  name: "Andorra",
  officialName: "Principality of Andorra",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "376",
  drivingSide: "right",
  flagUrl: "/data/country-flags/and.svg",
  imageUrl: "/data/country-images/and.svg",
  capital: "Andorra la Vella",
  population: 89752,
};
