import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Argentina.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const arg: CountryData = {
  id: "arg",
  name: "Argentina",
  officialName: "Argentine Republic",
  continent: "South America",
  region: "South America",
  callingCode: "54",
  drivingSide: "right",
  flagUrl: "/data/country-flags/arg.svg",
  imageUrl: "/data/country-images/arg.svg",
  capital: "Buenos Aires",
  population: 46466688,
};
