import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Armenia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const arm: CountryData = {
  id: "arm",
  name: "Armenia",
  officialName: "Republic of Armenia",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "374",
  drivingSide: "right",
  flagUrl: "/data/country-flags/arm.svg",
  imageUrl: "/data/country-images/arm.svg",
  capital: "Yerevan",
  population: 3096900,
};
