import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for American Samoa.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const asm: CountryData = {
  id: "asm",
  name: "American Samoa",
  officialName: "American Samoa",
  continent: "Oceania",
  region: "Polynesia",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/asm.svg",
  imageUrl: "/data/global/countries/silhouettes/asm.svg",
  capital: "Pago Pago",
  population: 43268,
};
