import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Antarctica.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ata: CountryData = {
  id: "ata",
  name: "Antarctica",
  officialName: "Antarctica",
  continent: "Antarctica",
  region: "",
  callingCode: "672",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/ata.svg",
  imageUrl: "/data/global/countries/silhouettes/ata.svg",
  capital: "",
  population: 1300,
};
