import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for French Southern and Antarctic Lands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const atf: CountryData = {
  id: "atf",
  name: "French Southern and Antarctic Lands",
  officialName: "Territory of the French Southern and Antarctic Lands",
  continent: "Antarctica",
  region: "",
  callingCode: "262",
  drivingSide: "right",
  flagUrl: "/data/country-flags/atf.svg",
  imageUrl: "/data/country-images/atf.svg",
  capital: "Port-aux-Français",
  population: 400,
};
