import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Antigua and Barbuda.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const atg: CountryData = {
  id: "atg",
  name: "Antigua and Barbuda",
  officialName: "Antigua and Barbuda",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/atg.svg",
  imageUrl: "/data/global/countries/silhouettes/atg.svg",
  capital: "Saint John's",
  population: 106365,
};
