import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Australia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const aus: CountryData = {
  id: "aus",
  name: "Australia",
  officialName: "Commonwealth of Australia",
  continent: "Oceania",
  region: "Australia and New Zealand",
  callingCode: "61",
  drivingSide: "left",
  flagUrl: "/data/country-flags/aus.svg",
  imageUrl: "/data/country-images/aus.svg",
  capital: "Canberra",
  population: 27801023,
};
