import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Austria.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const aut: CountryData = {
  id: "aut",
  name: "Austria",
  officialName: "Republic of Austria",
  continent: "Europe",
  region: "Central Europe",
  callingCode: "43",
  drivingSide: "right",
  flagUrl: "/data/country-flags/aut.svg",
  imageUrl: "/data/country-images/aut.svg",
  capital: "Vienna",
  population: 9217573,
};
