import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Azerbaijan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const aze: CountryData = {
  id: "aze",
  name: "Azerbaijan",
  officialName: "Republic of Azerbaijan",
  continent: "Europe",
  region: "Western Asia",
  callingCode: "994",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/aze.svg",
  imageUrl: "/data/global/countries/silhouettes/aze.svg",
  capital: "Baku",
  population: 10273450,
};
