import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Burundi.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bdi: CountryData = {
  id: "bdi",
  name: "Burundi",
  officialName: "Republic of Burundi",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "257",
  drivingSide: "right",
  flagUrl: "/data/country-flags/bdi.svg",
  imageUrl: "/data/country-images/bdi.svg",
  capital: "Gitega",
  population: 12332788,
};
