import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Belgium.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bel: CountryData = {
  id: "bel",
  name: "Belgium",
  officialName: "Kingdom of Belgium",
  continent: "Europe",
  region: "Western Europe",
  callingCode: "32",
  drivingSide: "right",
  flagUrl: "/data/country-flags/bel.svg",
  imageUrl: "/data/country-images/bel.svg",
  capital: "Brussels",
  population: 11936546,
};
