import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Benin.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ben: CountryData = {
  id: "ben",
  name: "Benin",
  officialName: "Republic of Benin",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "229",
  drivingSide: "right",
  flagUrl: "/data/country-flags/ben.svg",
  imageUrl: "/data/country-images/ben.svg",
  capital: "Porto-Novo",
  population: 13551992,
};
