import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Burkina Faso.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bfa: CountryData = {
  id: "bfa",
  name: "Burkina Faso",
  officialName: "Burkina Faso",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "226",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/bfa.svg",
  imageUrl: "/data/global/countries/silhouettes/bfa.svg",
  capital: "Ouagadougou",
  population: 22489126,
};
