import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Bangladesh.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bgd: CountryData = {
  id: "bgd",
  name: "Bangladesh",
  officialName: "People's Republic of Bangladesh",
  continent: "Asia",
  region: "Southern Asia",
  callingCode: "880",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/bgd.svg",
  imageUrl: "/data/global/countries/silhouettes/bgd.svg",
  capital: "Dhaka",
  population: 169828911,
};
