import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Bulgaria.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bgr: CountryData = {
  id: "bgr",
  name: "Bulgaria",
  officialName: "Republic of Bulgaria",
  continent: "Europe",
  region: "Southeast Europe",
  callingCode: "359",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/bgr.svg",
  imageUrl: "/data/global/countries/silhouettes/bgr.svg",
  capital: "Sofia",
  population: 6423207,
};
