import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Bahrain.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bhr: CountryData = {
  id: "bhr",
  name: "Bahrain",
  officialName: "Kingdom of Bahrain",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "973",
  drivingSide: "right",
  flagUrl: "/data/country-flags/bhr.svg",
  imageUrl: "/data/country-images/bhr.svg",
  capital: "Manama",
  population: 1603260,
};
