import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Bahamas.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bhs: CountryData = {
  id: "bhs",
  name: "Bahamas",
  officialName: "Commonwealth of the Bahamas",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/bhs.svg",
  imageUrl: "/data/global/countries/silhouettes/bhs.svg",
  capital: "Nassau",
  population: 398165,
};
