import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Bosnia and Herzegovina.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bih: CountryData = {
  id: "bih",
  name: "Bosnia and Herzegovina",
  officialName: "Bosnia and Herzegovina",
  continent: "Europe",
  region: "Southeast Europe",
  callingCode: "387",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/bih.svg",
  imageUrl: "/data/global/countries/silhouettes/bih.svg",
  capital: "Sarajevo",
  population: 3412000,
};
