import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Saint Barthélemy.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const blm: CountryData = {
  id: "blm",
  name: "Saint Barthélemy",
  officialName: "Collectivity of Saint Barthélemy",
  continent: "North America",
  region: "Caribbean",
  callingCode: "590",
  drivingSide: "right",
  flagUrl: "/data/country-flags/blm.svg",
  imageUrl: "/data/country-images/blm.svg",
  capital: "Gustavia",
  population: 4255,
};
