import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Belize.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const blz: CountryData = {
  id: "blz",
  name: "Belize",
  officialName: "Belize",
  continent: "North America",
  region: "Central America",
  callingCode: "501",
  drivingSide: "right",
  flagUrl: "/data/country-flags/blz.svg",
  imageUrl: "/data/country-images/blz.svg",
  capital: "Belmopan",
  population: 418982,
};
