import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Bermuda.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bmu: CountryData = {
  id: "bmu",
  name: "Bermuda",
  officialName: "Bermuda",
  continent: "North America",
  region: "North America",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/bmu.svg",
  imageUrl: "/data/global/countries/silhouettes/bmu.svg",
  capital: "Hamilton",
  population: 64055,
};
