import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Bolivia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bol: CountryData = {
  id: "bol",
  name: "Bolivia",
  officialName: "Plurinational State of Bolivia",
  continent: "South America",
  region: "South America",
  callingCode: "591",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/bol.svg",
  imageUrl: "/data/global/countries/silhouettes/bol.svg",
  capital: "Sucre, La Paz",
  population: 11365333,
};
