import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Brazil.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bra: CountryData = {
  id: "bra",
  name: "Brazil",
  officialName: "Federative Republic of Brazil",
  continent: "South America",
  region: "South America",
  callingCode: "55",
  drivingSide: "right",
  flagUrl: "/data/country-flags/bra.svg",
  imageUrl: "/data/country-images/bra.svg",
  capital: "Brasília",
  population: 213421037,
};
