import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Barbados.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const brb: CountryData = {
  id: "brb",
  name: "Barbados",
  officialName: "Barbados",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/brb.svg",
  imageUrl: "/data/global/countries/silhouettes/brb.svg",
  capital: "Bridgetown",
  population: 261692,
};
