import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Brunei.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const brn: CountryData = {
  id: "brn",
  name: "Brunei",
  officialName: "Nation of Brunei, the Abode of Peace",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "673",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/brn.svg",
  imageUrl: "/data/global/countries/silhouettes/brn.svg",
  capital: "Bandar Seri Begawan",
  population: 458600,
};
