import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Botswana.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const bwa: CountryData = {
  id: "bwa",
  name: "Botswana",
  officialName: "Republic of Botswana",
  continent: "Africa",
  region: "Southern Africa",
  callingCode: "267",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/bwa.svg",
  imageUrl: "/data/global/countries/silhouettes/bwa.svg",
  capital: "Gaborone",
  population: 2359609,
};
