import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Central African Republic.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const caf: CountryData = {
  id: "caf",
  name: "Central African Republic",
  nativeName: "Centrafrique",
  officialName: "Central African Republic",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "236",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/caf.svg",
  imageUrl: "/data/global/countries/silhouettes/caf.svg",
  capital: "Bangui",
  population: 5513282,
};
