import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Canada.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const can: CountryData = {
  id: "can",
  name: "Canada",
  officialName: "Canada",
  continent: "North America",
  region: "North America",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/country-flags/can.svg",
  imageUrl: "/data/country-images/can.svg",
  capital: "Ottawa",
  population: 41417056,
};
