import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Switzerland.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const che: CountryData = {
  id: "che",
  name: "Switzerland",
  nativeName: "Schweiz / Suisse / Svizzera / Svizra",
  officialName: "Swiss Confederation",
  continent: "Europe",
  region: "Western Europe",
  callingCode: "41",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/che.svg",
  imageUrl: "/data/global/countries/silhouettes/che.svg",
  capital: "Bern",
  population: 9139676,
};
