import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Chile.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const chl: CountryData = {
  id: "chl",
  name: "Chile",
  officialName: "Republic of Chile",
  continent: "South America",
  region: "South America",
  callingCode: "56",
  drivingSide: "right",
  flagUrl: "/data/country-flags/chl.svg",
  imageUrl: "/data/country-images/chl.svg",
  capital: "Santiago",
  population: 20150948,
};
