import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for China.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const chn: CountryData = {
  id: "chn",
  name: "China",
  officialName: "People's Republic of China",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "86",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/chn.svg",
  imageUrl: "/data/global/countries/silhouettes/chn.svg",
  capital: "Beijing",
  population: 1404890000,
};
