import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Ivory Coast.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const civ: CountryData = {
  id: "civ",
  name: "Ivory Coast",
  officialName: "Republic of Côte d'Ivoire",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "225",
  drivingSide: "right",
  flagUrl: "/data/country-flags/civ.svg",
  imageUrl: "/data/country-images/civ.svg",
  capital: "Yamoussoukro",
  population: 31500000,
};
