import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Cameroon.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cmr: CountryData = {
  id: "cmr",
  name: "Cameroon",
  officialName: "Republic of Cameroon",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "237",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/cmr.svg",
  imageUrl: "/data/global/countries/silhouettes/cmr.svg",
  capital: "Yaoundé",
  population: 29442327,
};
