import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for DRC.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cod: CountryData = {
  id: "cod",
  name: "DRC",
  officialName: "Democratic Republic of the Congo",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "243",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/cod.svg",
  imageUrl: "/data/global/countries/silhouettes/cod.svg",
  capital: "Kinshasa",
  population: 116452000,
};
