import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Congo.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cog: CountryData = {
  id: "cog",
  name: "Congo",
  officialName: "Republic of the Congo",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "242",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/cog.svg",
  imageUrl: "/data/global/countries/silhouettes/cog.svg",
  capital: "Brazzaville",
  population: 6332961,
};
