import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Cook Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cok: CountryData = {
  id: "cok",
  name: "Cook Islands",
  officialName: "Cook Islands",
  continent: "Oceania",
  region: "Polynesia",
  callingCode: "682",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/cok.svg",
  imageUrl: "/data/global/countries/silhouettes/cok.svg",
  capital: "Avarua",
  population: 15040,
};
