import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Colombia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const col: CountryData = {
  id: "col",
  name: "Colombia",
  officialName: "Republic of Colombia",
  continent: "South America",
  region: "South America",
  callingCode: "57",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/col.svg",
  imageUrl: "/data/global/countries/silhouettes/col.svg",
  capital: "Bogotá",
  population: 53399171,
};
