import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Comoros.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const com: CountryData = {
  id: "com",
  name: "Comoros",
  officialName: "Union of the Comoros",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "269",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/com.svg",
  imageUrl: "/data/global/countries/silhouettes/com.svg",
  capital: "Moroni",
  population: 944388,
};
