import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Cabo Verde.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cpv: CountryData = {
  id: "cpv",
  name: "Cabo Verde",
  officialName: "Republic of Cabo Verde",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "238",
  drivingSide: "right",
  flagUrl: "/data/country-flags/cpv.svg",
  imageUrl: "/data/country-images/cpv.svg",
  capital: "Praia",
  population: 491233,
};
