import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Costa Rica.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cri: CountryData = {
  id: "cri",
  name: "Costa Rica",
  officialName: "Republic of Costa Rica",
  continent: "North America",
  region: "Central America",
  callingCode: "506",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/cri.svg",
  imageUrl: "/data/global/countries/silhouettes/cri.svg",
  capital: "San José",
  population: 5160700,
};
