import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Cuba.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cub: CountryData = {
  id: "cub",
  name: "Cuba",
  officialName: "Republic of Cuba",
  continent: "North America",
  region: "Caribbean",
  callingCode: "53",
  drivingSide: "right",
  flagUrl: "/data/country-flags/cub.svg",
  imageUrl: "/data/country-images/cub.svg",
  capital: "Havana",
  population: 9434593,
};
