import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Curaçao.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cuw: CountryData = {
  id: "cuw",
  name: "Curaçao",
  officialName: "Country of Curaçao",
  continent: "North America",
  region: "Caribbean",
  callingCode: "599",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/cuw.svg",
  imageUrl: "/data/global/countries/silhouettes/cuw.svg",
  capital: "Willemstad",
  population: 155826,
};
