import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Cyprus.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cyp: CountryData = {
  id: "cyp",
  name: "Cyprus",
  officialName: "Republic of Cyprus",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "357",
  drivingSide: "left",
  flagUrl: "/data/country-flags/cyp.svg",
  imageUrl: "/data/country-images/cyp.svg",
  capital: "Nicosia",
  population: 983000,
};
