import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Czechia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const cze: CountryData = {
  id: "cze",
  name: "Czechia",
  officialName: "Czech Republic",
  continent: "Europe",
  region: "Central Europe",
  callingCode: "420",
  drivingSide: "right",
  flagUrl: "/data/country-flags/cze.svg",
  imageUrl: "/data/country-images/cze.svg",
  capital: "Prague",
  population: 10896003,
};
