import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Germany.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const deu: CountryData = {
  id: "deu",
  name: "Germany",
  officialName: "Federal Republic of Germany",
  continent: "Europe",
  region: "Western Europe",
  callingCode: "49",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/deu.svg",
  imageUrl: "/data/global/countries/silhouettes/deu.svg",
  capital: "Berlin",
  population: 83467117,
};
