import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Djibouti.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const dji: CountryData = {
  id: "dji",
  name: "Djibouti",
  officialName: "Republic of Djibouti",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "253",
  drivingSide: "right",
  flagUrl: "/data/country-flags/dji.svg",
  imageUrl: "/data/country-images/dji.svg",
  capital: "Djibouti",
  population: 1066809,
};
