import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Dominica.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const dma: CountryData = {
  id: "dma",
  name: "Dominica",
  officialName: "Commonwealth of Dominica",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/dma.svg",
  imageUrl: "/data/global/countries/silhouettes/dma.svg",
  capital: "Roseau",
  population: 65514,
};
