import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Denmark.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const dnk: CountryData = {
  id: "dnk",
  name: "Denmark",
  nativeName: "Danmark",
  officialName: "Kingdom of Denmark",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "45",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/dnk.svg",
  imageUrl: "/data/global/countries/silhouettes/dnk.svg",
  capital: "Copenhagen",
  population: 6031699,
};
