import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Denmark.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const dnk: CountryData = {
  id: "dnk",
  name: "Denmark",
  officialName: "Kingdom of Denmark",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "45",
  drivingSide: "right",
  flagUrl: "/data/country-flags/dnk.svg",
  imageUrl: "/data/country-images/dnk.svg",
  capital: "Copenhagen",
  population: 6031699,
};
