import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Dominican Republic.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const dom: CountryData = {
  id: "dom",
  name: "Dominican Republic",
  officialName: "Dominican Republic",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/dom.svg",
  imageUrl: "/data/global/countries/silhouettes/dom.svg",
  capital: "Santo Domingo",
  population: 11532151,
};
