import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Algeria.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const dza: CountryData = {
  id: "dza",
  name: "Algeria",
  officialName: "People's Democratic Republic of Algeria",
  continent: "Africa",
  region: "Northern Africa",
  callingCode: "213",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/dza.svg",
  imageUrl: "/data/global/countries/silhouettes/dza.svg",
  capital: "Algiers",
  population: 47400000,
};
