import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Ecuador.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ecu: CountryData = {
  id: "ecu",
  name: "Ecuador",
  officialName: "Republic of Ecuador",
  continent: "South America",
  region: "South America",
  callingCode: "593",
  drivingSide: "right",
  flagUrl: "/data/country-flags/ecu.svg",
  imageUrl: "/data/country-images/ecu.svg",
  capital: "Quito",
  population: 18103660,
};
