import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Egypt.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const egy: CountryData = {
  id: "egy",
  name: "Egypt",
  officialName: "Arab Republic of Egypt",
  continent: "Africa",
  region: "Northern Africa",
  callingCode: "20",
  drivingSide: "right",
  flagUrl: "/data/country-flags/egy.svg",
  imageUrl: "/data/country-images/egy.svg",
  capital: "Cairo",
  population: 108613296,
};
