import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Eritrea.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const eri: CountryData = {
  id: "eri",
  name: "Eritrea",
  officialName: "State of Eritrea",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "291",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/eri.svg",
  imageUrl: "/data/global/countries/silhouettes/eri.svg",
  capital: "Asmara",
  population: 3682669,
};
