import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Western Sahara.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const esh: CountryData = {
  id: "esh",
  name: "Western Sahara",
  officialName: "Sahrawi Arab Democratic Republic",
  continent: "Africa",
  region: "Northern Africa",
  callingCode: "212",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/esh.svg",
  imageUrl: "/data/global/countries/silhouettes/esh.svg",
  capital: "El Aaiún",
  population: 510713,
};
