import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Spain.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const esp: CountryData = {
  id: "esp",
  name: "Spain",
  officialName: "Kingdom of Spain",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "34",
  drivingSide: "right",
  flagUrl: "/data/country-flags/esp.svg",
  imageUrl: "/data/country-images/esp.svg",
  capital: "Madrid",
  population: 49801559,
};
