import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Estonia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const est: CountryData = {
  id: "est",
  name: "Estonia",
  officialName: "Republic of Estonia",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "372",
  drivingSide: "right",
  flagUrl: "/data/country-flags/est.svg",
  imageUrl: "/data/country-images/est.svg",
  capital: "Tallinn",
  population: 1360745,
};
