import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Ethiopia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const eth: CountryData = {
  id: "eth",
  name: "Ethiopia",
  officialName: "Federal Democratic Republic of Ethiopia",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "251",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/eth.svg",
  imageUrl: "/data/global/countries/silhouettes/eth.svg",
  capital: "Addis Ababa",
  population: 111652998,
};
