import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Finland.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const fin: CountryData = {
  id: "fin",
  name: "Finland",
  officialName: "Republic of Finland",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "358",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/fin.svg",
  imageUrl: "/data/global/countries/silhouettes/fin.svg",
  capital: "Helsinki",
  population: 5655296,
};
