import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Fiji.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const fji: CountryData = {
  id: "fji",
  name: "Fiji",
  officialName: "Republic of Fiji",
  continent: "Oceania",
  region: "Melanesia",
  callingCode: "679",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/fji.svg",
  imageUrl: "/data/global/countries/silhouettes/fji.svg",
  capital: "Suva",
  population: 902623,
};
