import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Falkland Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const flk: CountryData = {
  id: "flk",
  name: "Falkland Islands",
  officialName: "Falkland Islands",
  continent: "South America",
  region: "South America",
  callingCode: "500",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/flk.svg",
  imageUrl: "/data/global/countries/silhouettes/flk.svg",
  capital: "Stanley",
  population: 3662,
};
