import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for France.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const fra: CountryData = {
  id: "fra",
  name: "France",
  officialName: "French Republic",
  continent: "Europe",
  region: "Western Europe",
  callingCode: "33",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/fra.svg",
  imageUrl: "/data/global/countries/silhouettes/fra.svg",
  capital: "Paris",
  population: 69081996,
};
