import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Faroe Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const fro: CountryData = {
  id: "fro",
  name: "Faroe Islands",
  officialName: "Faroe Islands",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "298",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/fro.svg",
  imageUrl: "/data/global/countries/silhouettes/fro.svg",
  capital: "Tórshavn",
  population: 56210,
};
