import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Micronesia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const fsm: CountryData = {
  id: "fsm",
  name: "Micronesia",
  officialName: "Federated States of Micronesia",
  continent: "Oceania",
  region: "Micronesia",
  callingCode: "691",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/fsm.svg",
  imageUrl: "/data/global/countries/silhouettes/fsm.svg",
  capital: "Palikir",
  population: 75817,
};
