import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Gabon.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const gab: CountryData = {
  id: "gab",
  name: "Gabon",
  officialName: "Gabonese Republic",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "241",
  drivingSide: "right",
  flagUrl: "/data/country-flags/gab.svg",
  imageUrl: "/data/country-images/gab.svg",
  capital: "Libreville",
  population: 2469296,
};
