import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for United Kingdom.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const gbr: CountryData = {
  id: "gbr",
  name: "United Kingdom",
  officialName: "United Kingdom of Great Britain and Northern Ireland",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "44",
  drivingSide: "left",
  flagUrl: "/data/country-flags/gbr.svg",
  imageUrl: "/data/country-images/gbr.svg",
  capital: "London",
  population: 66912637,
};
