import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Georgia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const geo: CountryData = {
  id: "geo",
  name: "Georgia",
  officialName: "Georgia",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "995",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/geo.svg",
  imageUrl: "/data/global/countries/silhouettes/geo.svg",
  capital: "Tbilisi",
  population: 3657000,
};
