import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Ghana.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const gha: CountryData = {
  id: "gha",
  name: "Ghana",
  officialName: "Republic of Ghana",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "233",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/gha.svg",
  imageUrl: "/data/global/countries/silhouettes/gha.svg",
  capital: "Accra",
  population: 34378768,
};
