import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Gibraltar.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const gib: CountryData = {
  id: "gib",
  name: "Gibraltar",
  officialName: "Gibraltar",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "350",
  drivingSide: "right",
  flagUrl: "/data/country-flags/gib.svg",
  imageUrl: "/data/country-images/gib.svg",
  capital: "Gibraltar",
  population: 38196,
};
