import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Guinea.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const gin: CountryData = {
  id: "gin",
  name: "Guinea",
  officialName: "Republic of Guinea",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "224",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/gin.svg",
  imageUrl: "/data/global/countries/silhouettes/gin.svg",
  capital: "Conakry",
  population: 17521167,
};
