import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Guinea-Bissau.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const gnb: CountryData = {
  id: "gnb",
  name: "Guinea-Bissau",
  officialName: "Republic of Guinea-Bissau",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "245",
  drivingSide: "right",
  flagUrl: "/data/country-flags/gnb.svg",
  imageUrl: "/data/country-images/gnb.svg",
  capital: "Bissau",
  population: 1890252,
};
