import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Equatorial Guinea.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const gnq: CountryData = {
  id: "gnq",
  name: "Equatorial Guinea",
  officialName: "Republic of Equatorial Guinea",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "240",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/gnq.svg",
  imageUrl: "/data/global/countries/silhouettes/gnq.svg",
  capital: "Malabo",
  population: 1795834,
};
