import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Greece.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const grc: CountryData = {
  id: "grc",
  name: "Greece",
  officialName: "Hellenic Republic",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "30",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/grc.svg",
  imageUrl: "/data/global/countries/silhouettes/grc.svg",
  capital: "Athens",
  population: 10372335,
};
