import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Grenada.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const grd: CountryData = {
  id: "grd",
  name: "Grenada",
  officialName: "Grenada",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/country-flags/grd.svg",
  imageUrl: "/data/country-images/grd.svg",
  capital: "St. George's",
  population: 109021,
};
