import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Greenland.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const grl: CountryData = {
  id: "grl",
  name: "Greenland",
  nativeName: "Kalaallit Nunaat",
  officialName: "Greenland",
  continent: "North America",
  region: "North America",
  callingCode: "299",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/grl.svg",
  imageUrl: "/data/global/countries/silhouettes/grl.svg",
  capital: "Nuuk",
  population: 56945,
};
