import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Guam.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const gum: CountryData = {
  id: "gum",
  name: "Guam",
  officialName: "Guam",
  continent: "Oceania",
  region: "Micronesia",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/country-flags/gum.svg",
  imageUrl: "/data/country-images/gum.svg",
  capital: "Hagåtña",
  population: 153836,
};
