import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Guyana.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const guy: CountryData = {
  id: "guy",
  name: "Guyana",
  officialName: "Co-operative Republic of Guyana",
  continent: "South America",
  region: "South America",
  callingCode: "592",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/guy.svg",
  imageUrl: "/data/global/countries/silhouettes/guy.svg",
  capital: "Georgetown",
  population: 956044,
};
