import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Hong Kong.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const hkg: CountryData = {
  id: "hkg",
  name: "Hong Kong",
  officialName: "Hong Kong Special Administrative Region of the People's Republic of China",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "852",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/hkg.svg",
  imageUrl: "/data/global/countries/silhouettes/hkg.svg",
  capital: "City of Victoria",
  population: 7498100,
};
