import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Heard Island and McDonald Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const hmd: CountryData = {
  id: "hmd",
  name: "Heard Island and McDonald Islands",
  officialName: "Heard Island and McDonald Islands",
  continent: "Antarctica",
  region: "",
  callingCode: "672",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/hmd.svg",
  imageUrl: "/data/global/countries/silhouettes/hmd.svg",
  capital: "",
  population: 0,
};
