import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Croatia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const hrv: CountryData = {
  id: "hrv",
  name: "Croatia",
  officialName: "Republic of Croatia",
  continent: "Europe",
  region: "Southeast Europe",
  callingCode: "385",
  drivingSide: "right",
  flagUrl: "/data/country-flags/hrv.svg",
  imageUrl: "/data/country-images/hrv.svg",
  capital: "Zagreb",
  population: 3866233,
};
