import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Haiti.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const hti: CountryData = {
  id: "hti",
  name: "Haiti",
  officialName: "Republic of Haiti",
  continent: "North America",
  region: "Caribbean",
  callingCode: "509",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/hti.svg",
  imageUrl: "/data/global/countries/silhouettes/hti.svg",
  capital: "Port-au-Prince",
  population: 11867032,
};
