import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Hungary.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const hun: CountryData = {
  id: "hun",
  name: "Hungary",
  officialName: "Hungary",
  continent: "Europe",
  region: "Central Europe",
  callingCode: "36",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/hun.svg",
  imageUrl: "/data/global/countries/silhouettes/hun.svg",
  capital: "Budapest",
  population: 9488428,
};
