import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Indonesia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const idn: CountryData = {
  id: "idn",
  name: "Indonesia",
  officialName: "Republic of Indonesia",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "62",
  drivingSide: "left",
  flagUrl: "/data/country-flags/idn.svg",
  imageUrl: "/data/country-images/idn.svg",
  capital: "Jakarta",
  population: 288315089,
};
