import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Isle of Man.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const imn: CountryData = {
  id: "imn",
  name: "Isle of Man",
  officialName: "Isle of Man",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "44",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/imn.svg",
  imageUrl: "/data/global/countries/silhouettes/imn.svg",
  capital: "Douglas",
  population: 84523,
};
