import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for British Indian Ocean Territory.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const iot: CountryData = {
  id: "iot",
  name: "British Indian Ocean Territory",
  officialName: "British Indian Ocean Territory",
  continent: "Asia",
  region: "Eastern Africa",
  callingCode: "246",
  drivingSide: "right",
  flagUrl: "/data/country-flags/iot.svg",
  imageUrl: "/data/country-images/iot.svg",
  capital: "Diego Garcia",
  population: 2000,
};
