import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Ireland.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const irl: CountryData = {
  id: "irl",
  name: "Ireland",
  officialName: "Republic of Ireland",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "353",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/irl.svg",
  imageUrl: "/data/global/countries/silhouettes/irl.svg",
  capital: "Dublin",
  population: 5458600,
};
