import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Iran.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const irn: CountryData = {
  id: "irn",
  name: "Iran",
  officialName: "Islamic Republic of Iran",
  continent: "Asia",
  region: "Southern Asia",
  callingCode: "98",
  drivingSide: "right",
  flagUrl: "/data/country-flags/irn.svg",
  imageUrl: "/data/country-images/irn.svg",
  capital: "Tehran",
  population: 87134000,
};
