import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Iraq.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const irq: CountryData = {
  id: "irq",
  name: "Iraq",
  officialName: "Republic of Iraq",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "964",
  drivingSide: "right",
  flagUrl: "/data/country-flags/irq.svg",
  imageUrl: "/data/country-images/irq.svg",
  capital: "Baghdad",
  population: 46118793,
};
