import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Iceland.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const isl: CountryData = {
  id: "isl",
  name: "Iceland",
  officialName: "Iceland",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "354",
  drivingSide: "right",
  flagUrl: "/data/country-flags/isl.svg",
  imageUrl: "/data/country-images/isl.svg",
  capital: "Reykjavik",
  population: 396500,
};
