import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Israel.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const isr: CountryData = {
  id: "isr",
  name: "Israel",
  officialName: "State of Israel",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "972",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/isr.svg",
  imageUrl: "/data/global/countries/silhouettes/isr.svg",
  capital: "Jerusalem",
  population: 10273700,
};
