import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Italy.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ita: CountryData = {
  id: "ita",
  name: "Italy",
  officialName: "Italian Republic",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "39",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/ita.svg",
  imageUrl: "/data/global/countries/silhouettes/ita.svg",
  capital: "Rome",
  population: 58940756,
};
