import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Jamaica.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const jam: CountryData = {
  id: "jam",
  name: "Jamaica",
  officialName: "Jamaica",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/jam.svg",
  imageUrl: "/data/global/countries/silhouettes/jam.svg",
  capital: "Kingston",
  population: 2774538,
};
