import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Jersey.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const jey: CountryData = {
  id: "jey",
  name: "Jersey",
  officialName: "Bailiwick of Jersey",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "44",
  drivingSide: "left",
  flagUrl: "/data/country-flags/jey.svg",
  imageUrl: "/data/country-images/jey.svg",
  capital: "Saint Helier",
  population: 103267,
};
