import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Jordan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const jor: CountryData = {
  id: "jor",
  name: "Jordan",
  officialName: "Hashemite Kingdom of Jordan",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "962",
  drivingSide: "right",
  flagUrl: "/data/country-flags/jor.svg",
  imageUrl: "/data/country-images/jor.svg",
  capital: "Amman",
  population: 11937000,
};
