import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Japan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const jpn: CountryData = {
  id: "jpn",
  name: "Japan",
  officialName: "Japan",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "81",
  drivingSide: "left",
  flagUrl: "/data/country-flags/jpn.svg",
  imageUrl: "/data/country-images/jpn.svg",
  capital: "Tokyo",
  population: 122680000,
};
