import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Kazakhstan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const kaz: CountryData = {
  id: "kaz",
  name: "Kazakhstan",
  officialName: "Republic of Kazakhstan",
  continent: "Asia",
  region: "Central Asia",
  callingCode: "7",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/kaz.svg",
  imageUrl: "/data/global/countries/silhouettes/kaz.svg",
  capital: "Astana",
  population: 20590589,
};
