import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Kenya.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ken: CountryData = {
  id: "ken",
  name: "Kenya",
  officialName: "Republic of Kenya",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "254",
  drivingSide: "left",
  flagUrl: "/data/country-flags/ken.svg",
  imageUrl: "/data/country-images/ken.svg",
  capital: "Nairobi",
  population: 54227015,
};
