import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Kyrgyzstan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const kgz: CountryData = {
  id: "kgz",
  name: "Kyrgyzstan",
  officialName: "Kyrgyz Republic",
  continent: "Asia",
  region: "Central Asia",
  callingCode: "996",
  drivingSide: "right",
  flagUrl: "/data/country-flags/kgz.svg",
  imageUrl: "/data/country-images/kgz.svg",
  capital: "Bishkek",
  population: 7404300,
};
