import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Cambodia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const khm: CountryData = {
  id: "khm",
  name: "Cambodia",
  officialName: "Kingdom of Cambodia",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "855",
  drivingSide: "right",
  flagUrl: "/data/country-flags/khm.svg",
  imageUrl: "/data/country-images/khm.svg",
  capital: "Phnom Penh",
  population: 17816143,
};
