import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Kiribati.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const kir: CountryData = {
  id: "kir",
  name: "Kiribati",
  officialName: "Independent and Sovereign Republic of Kiribati",
  continent: "Oceania",
  region: "Micronesia",
  callingCode: "686",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/kir.svg",
  imageUrl: "/data/global/countries/silhouettes/kir.svg",
  capital: "South Tarawa",
  population: 120740,
};
