import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for South Korea.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const kor: CountryData = {
  id: "kor",
  name: "South Korea",
  officialName: "Republic of Korea",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "82",
  drivingSide: "right",
  flagUrl: "/data/country-flags/kor.svg",
  imageUrl: "/data/country-images/kor.svg",
  capital: "Seoul",
  population: 51106229,
};
