import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Kuwait.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const kwt: CountryData = {
  id: "kwt",
  name: "Kuwait",
  officialName: "State of Kuwait",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "965",
  drivingSide: "right",
  flagUrl: "/data/country-flags/kwt.svg",
  imageUrl: "/data/country-images/kwt.svg",
  capital: "Kuwait City",
  population: 4881254,
};
