import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Laos.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const lao: CountryData = {
  id: "lao",
  name: "Laos",
  officialName: "Lao People's Democratic Republic",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "856",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/lao.svg",
  imageUrl: "/data/global/countries/silhouettes/lao.svg",
  capital: "Vientiane",
  population: 7745000,
};
