import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Lebanon.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const lbn: CountryData = {
  id: "lbn",
  name: "Lebanon",
  officialName: "Lebanese Republic",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "961",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/lbn.svg",
  imageUrl: "/data/global/countries/silhouettes/lbn.svg",
  capital: "Beirut",
  population: 5895466,
};
