import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Libya.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const lby: CountryData = {
  id: "lby",
  name: "Libya",
  officialName: "State of Libya",
  continent: "Africa",
  region: "Northern Africa",
  callingCode: "218",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/lby.svg",
  imageUrl: "/data/global/countries/silhouettes/lby.svg",
  capital: "Tripoli",
  population: 7539852,
};
