import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Liechtenstein.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const lie: CountryData = {
  id: "lie",
  name: "Liechtenstein",
  officialName: "Principality of Liechtenstein",
  continent: "Europe",
  region: "Western Europe",
  callingCode: "423",
  drivingSide: "right",
  flagUrl: "/data/country-flags/lie.svg",
  imageUrl: "/data/country-images/lie.svg",
  capital: "Vaduz",
  population: 41237,
};
