import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Sri Lanka.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const lka: CountryData = {
  id: "lka",
  name: "Sri Lanka",
  nativeName: "ශ්‍රී ලංකාව / இலங்கை",
  officialName: "Democratic Socialist Republic of Sri Lanka",
  continent: "Asia",
  region: "Southern Asia",
  callingCode: "94",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/lka.svg",
  imageUrl: "/data/global/countries/silhouettes/lka.svg",
  capital: "Sri Jayawardenepura Kotte",
  population: 21756000,
};
