import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Lesotho.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const lso: CountryData = {
  id: "lso",
  name: "Lesotho",
  officialName: "Kingdom of Lesotho",
  continent: "Africa",
  region: "Southern Africa",
  callingCode: "266",
  drivingSide: "left",
  flagUrl: "/data/country-flags/lso.svg",
  imageUrl: "/data/country-images/lso.svg",
  capital: "Maseru",
  population: 2116427,
};
