import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Lithuania.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const ltu: CountryData = {
  id: "ltu",
  name: "Lithuania",
  nativeName: "Lietuva",
  officialName: "Republic of Lithuania",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "370",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/ltu.svg",
  imageUrl: "/data/global/countries/silhouettes/ltu.svg",
  capital: "Vilnius",
  population: 2886179,
};
