import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Luxembourg.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const lux: CountryData = {
  id: "lux",
  name: "Luxembourg",
  officialName: "Grand Duchy of Luxembourg",
  continent: "Europe",
  region: "Western Europe",
  callingCode: "352",
  drivingSide: "right",
  flagUrl: "/data/country-flags/lux.svg",
  imageUrl: "/data/country-images/lux.svg",
  capital: "Luxembourg",
  population: 690959,
};
