import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Latvia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const lva: CountryData = {
  id: "lva",
  name: "Latvia",
  officialName: "Republic of Latvia",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "371",
  drivingSide: "right",
  flagUrl: "/data/country-flags/lva.svg",
  imageUrl: "/data/country-images/lva.svg",
  capital: "Riga",
  population: 1832100,
};
