import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Macau.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mac: CountryData = {
  id: "mac",
  name: "Macau",
  officialName: "Macao Special Administrative Region of the People's Republic of China",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "853",
  drivingSide: "left",
  flagUrl: "/data/country-flags/mac.svg",
  imageUrl: "/data/country-images/mac.svg",
  capital: "",
  population: 686500,
};
