import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Morocco.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mar: CountryData = {
  id: "mar",
  name: "Morocco",
  officialName: "Kingdom of Morocco",
  continent: "Africa",
  region: "Northern Africa",
  callingCode: "212",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mar.svg",
  imageUrl: "/data/global/countries/silhouettes/mar.svg",
  capital: "Rabat",
  population: 37254695,
};
