import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Moldova.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mda: CountryData = {
  id: "mda",
  name: "Moldova",
  officialName: "Republic of Moldova",
  continent: "Europe",
  region: "Eastern Europe",
  callingCode: "373",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mda.svg",
  imageUrl: "/data/global/countries/silhouettes/mda.svg",
  capital: "Chișinău",
  population: 2365600,
};
