import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Madagascar.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mdg: CountryData = {
  id: "mdg",
  name: "Madagascar",
  officialName: "Republic of Madagascar",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "261",
  drivingSide: "right",
  flagUrl: "/data/country-flags/mdg.svg",
  imageUrl: "/data/country-images/mdg.svg",
  capital: "Antananarivo",
  population: 32658977,
};
