import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Maldives.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mdv: CountryData = {
  id: "mdv",
  name: "Maldives",
  officialName: "Republic of Maldives",
  continent: "Asia",
  region: "Southern Asia",
  callingCode: "960",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/mdv.svg",
  imageUrl: "/data/global/countries/silhouettes/mdv.svg",
  capital: "Malé",
  population: 515132,
};
