import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Mexico.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mex: CountryData = {
  id: "mex",
  name: "Mexico",
  officialName: "United Mexican States",
  continent: "North America",
  region: "North America",
  callingCode: "52",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mex.svg",
  imageUrl: "/data/global/countries/silhouettes/mex.svg",
  capital: "Mexico City",
  population: 131231919,
};
