import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Marshall Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mhl: CountryData = {
  id: "mhl",
  name: "Marshall Islands",
  officialName: "Republic of the Marshall Islands",
  continent: "Oceania",
  region: "Micronesia",
  callingCode: "692",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mhl.svg",
  imageUrl: "/data/global/countries/silhouettes/mhl.svg",
  capital: "Majuro",
  population: 37548,
};
