import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for North Macedonia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mkd: CountryData = {
  id: "mkd",
  name: "North Macedonia",
  officialName: "Republic of North Macedonia",
  continent: "Europe",
  region: "Southeast Europe",
  callingCode: "389",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mkd.svg",
  imageUrl: "/data/global/countries/silhouettes/mkd.svg",
  capital: "Skopje",
  population: 1836713,
};
