import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Mali.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mli: CountryData = {
  id: "mli",
  name: "Mali",
  officialName: "Republic of Mali",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "223",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mli.svg",
  imageUrl: "/data/global/countries/silhouettes/mli.svg",
  capital: "Bamako",
  population: 23929000,
};
