import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Malta.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mlt: CountryData = {
  id: "mlt",
  name: "Malta",
  officialName: "Republic of Malta",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "356",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/mlt.svg",
  imageUrl: "/data/global/countries/silhouettes/mlt.svg",
  capital: "Valletta",
  population: 588254,
};
