import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Myanmar.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const mmr: CountryData = {
  id: "mmr",
  name: "Myanmar",
  nativeName: "မြန်မာ",
  officialName: "Republic of the Union of Myanmar",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "95",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mmr.svg",
  imageUrl: "/data/global/countries/silhouettes/mmr.svg",
  capital: "Naypyidaw",
  population: 51375327,
};
