import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Montenegro.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mne: CountryData = {
  id: "mne",
  name: "Montenegro",
  officialName: "Montenegro",
  continent: "Europe",
  region: "Southeast Europe",
  callingCode: "382",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mne.svg",
  imageUrl: "/data/global/countries/silhouettes/mne.svg",
  capital: "Podgorica",
  population: 622902,
};
