import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Mongolia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mng: CountryData = {
  id: "mng",
  name: "Mongolia",
  officialName: "Mongolia",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "976",
  drivingSide: "right",
  flagUrl: "/data/country-flags/mng.svg",
  imageUrl: "/data/country-images/mng.svg",
  capital: "Ulan Bator",
  population: 3591120,
};
