import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Northern Mariana Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mnp: CountryData = {
  id: "mnp",
  name: "Northern Mariana Islands",
  officialName: "Commonwealth of the Northern Mariana Islands",
  continent: "Oceania",
  region: "Micronesia",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mnp.svg",
  imageUrl: "/data/global/countries/silhouettes/mnp.svg",
  capital: "Saipan",
  population: 46078,
};
