import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Mozambique.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const moz: CountryData = {
  id: "moz",
  name: "Mozambique",
  officialName: "Republic of Mozambique",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "258",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/moz.svg",
  imageUrl: "/data/global/countries/silhouettes/moz.svg",
  capital: "Maputo",
  population: 34958973,
};
