import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Mauritania.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mrt: CountryData = {
  id: "mrt",
  name: "Mauritania",
  officialName: "Islamic Republic of Mauritania",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "222",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/mrt.svg",
  imageUrl: "/data/global/countries/silhouettes/mrt.svg",
  capital: "Nouakchott",
  population: 4927532,
};
