import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Montserrat.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const msr: CountryData = {
  id: "msr",
  name: "Montserrat",
  officialName: "Montserrat",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/msr.svg",
  imageUrl: "/data/global/countries/silhouettes/msr.svg",
  capital: "Plymouth",
  population: 4386,
};
