import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Mauritius.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mus: CountryData = {
  id: "mus",
  name: "Mauritius",
  officialName: "Republic of Mauritius",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "230",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/mus.svg",
  imageUrl: "/data/global/countries/silhouettes/mus.svg",
  capital: "Port Louis",
  population: 1241856,
};
