import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Malaysia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const mys: CountryData = {
  id: "mys",
  name: "Malaysia",
  officialName: "Malaysia",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "60",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/mys.svg",
  imageUrl: "/data/global/countries/silhouettes/mys.svg",
  capital: "Kuala Lumpur",
  population: 34389400,
};
