import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Namibia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const nam: CountryData = {
  id: "nam",
  name: "Namibia",
  officialName: "Republic of Namibia",
  continent: "Africa",
  region: "Southern Africa",
  callingCode: "264",
  drivingSide: "left",
  flagUrl: "/data/country-flags/nam.svg",
  imageUrl: "/data/country-images/nam.svg",
  capital: "Windhoek",
  population: 3022401,
};
