import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for New Caledonia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ncl: CountryData = {
  id: "ncl",
  name: "New Caledonia",
  officialName: "New Caledonia",
  continent: "Oceania",
  region: "Melanesia",
  callingCode: "687",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/ncl.svg",
  imageUrl: "/data/global/countries/silhouettes/ncl.svg",
  capital: "Nouméa",
  population: 264596,
};
