import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Niger.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ner: CountryData = {
  id: "ner",
  name: "Niger",
  officialName: "Republic of Niger",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "227",
  drivingSide: "right",
  flagUrl: "/data/country-flags/ner.svg",
  imageUrl: "/data/country-images/ner.svg",
  capital: "Niamey",
  population: 27522750,
};
