import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Norfolk Island.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const nfk: CountryData = {
  id: "nfk",
  name: "Norfolk Island",
  officialName: "Territory of Norfolk Island",
  continent: "Oceania",
  region: "Australia and New Zealand",
  callingCode: "672",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/nfk.svg",
  imageUrl: "/data/global/countries/silhouettes/nfk.svg",
  capital: "Kingston",
  population: 2188,
};
