import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Nigeria.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const nga: CountryData = {
  id: "nga",
  name: "Nigeria",
  officialName: "Federal Republic of Nigeria",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "234",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/nga.svg",
  imageUrl: "/data/global/countries/silhouettes/nga.svg",
  capital: "Abuja",
  population: 223800000,
};
