import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Nicaragua.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const nic: CountryData = {
  id: "nic",
  name: "Nicaragua",
  officialName: "Republic of Nicaragua",
  continent: "North America",
  region: "Central America",
  callingCode: "505",
  drivingSide: "right",
  flagUrl: "/data/country-flags/nic.svg",
  imageUrl: "/data/country-images/nic.svg",
  capital: "Managua",
  population: 6874748,
};
