import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Niue.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const niu: CountryData = {
  id: "niu",
  name: "Niue",
  officialName: "Niue",
  continent: "Oceania",
  region: "Polynesia",
  callingCode: "683",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/niu.svg",
  imageUrl: "/data/global/countries/silhouettes/niu.svg",
  capital: "Alofi",
  population: 1681,
};
