import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Netherlands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const nld: CountryData = {
  id: "nld",
  name: "Netherlands",
  officialName: "Kingdom of the Netherlands",
  continent: "Europe",
  region: "Western Europe",
  callingCode: "31",
  drivingSide: "right",
  flagUrl: "/data/country-flags/nld.svg",
  imageUrl: "/data/country-images/nld.svg",
  capital: "Amsterdam",
  population: 18153386,
};
