import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Norway.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const nor: CountryData = {
  id: "nor",
  name: "Norway",
  officialName: "Kingdom of Norway",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "47",
  drivingSide: "right",
  flagUrl: "/data/country-flags/nor.svg",
  imageUrl: "/data/country-images/nor.svg",
  capital: "Oslo",
  population: 5636904,
};
