import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Nauru.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const nru: CountryData = {
  id: "nru",
  name: "Nauru",
  officialName: "Republic of Nauru",
  continent: "Oceania",
  region: "Micronesia",
  callingCode: "674",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/nru.svg",
  imageUrl: "/data/global/countries/silhouettes/nru.svg",
  capital: "Yaren",
  population: 11680,
};
