import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for New Zealand.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const nzl: CountryData = {
  id: "nzl",
  name: "New Zealand",
  officialName: "New Zealand",
  continent: "Oceania",
  region: "Australia and New Zealand",
  callingCode: "64",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/nzl.svg",
  imageUrl: "/data/global/countries/silhouettes/nzl.svg",
  capital: "Wellington",
  population: 4993923,
};
