import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Oman.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const omn: CountryData = {
  id: "omn",
  name: "Oman",
  officialName: "Sultanate of Oman",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "968",
  drivingSide: "right",
  flagUrl: "/data/country-flags/omn.svg",
  imageUrl: "/data/country-images/omn.svg",
  capital: "Muscat",
  population: 5398645,
};
