import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Pakistan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const pak: CountryData = {
  id: "pak",
  name: "Pakistan",
  officialName: "Islamic Republic of Pakistan",
  continent: "Asia",
  region: "Southern Asia",
  callingCode: "92",
  drivingSide: "left",
  flagUrl: "/data/country-flags/pak.svg",
  imageUrl: "/data/country-images/pak.svg",
  capital: "Islamabad",
  population: 241499431,
};
