import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Panama.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const pan: CountryData = {
  id: "pan",
  name: "Panama",
  officialName: "Republic of Panama",
  continent: "North America",
  region: "Central America",
  callingCode: "507",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/pan.svg",
  imageUrl: "/data/global/countries/silhouettes/pan.svg",
  capital: "Panama City",
  population: 4064780,
};
