import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Pitcairn Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const pcn: CountryData = {
  id: "pcn",
  name: "Pitcairn Islands",
  officialName: "Pitcairn Group of Islands",
  continent: "Oceania",
  region: "Polynesia",
  callingCode: "64",
  drivingSide: "left",
  flagUrl: "/data/country-flags/pcn.svg",
  imageUrl: "/data/country-images/pcn.svg",
  capital: "Adamstown",
  population: 40,
};
