import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Peru.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const per: CountryData = {
  id: "per",
  name: "Peru",
  officialName: "Republic of Peru",
  continent: "South America",
  region: "South America",
  callingCode: "51",
  drivingSide: "right",
  flagUrl: "/data/country-flags/per.svg",
  imageUrl: "/data/country-images/per.svg",
  capital: "Lima",
  population: 34157732,
};
