import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Palau.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const plw: CountryData = {
  id: "plw",
  name: "Palau",
  officialName: "Republic of Palau",
  continent: "Oceania",
  region: "Micronesia",
  callingCode: "680",
  drivingSide: "right",
  flagUrl: "/data/country-flags/plw.svg",
  imageUrl: "/data/country-images/plw.svg",
  capital: "Ngerulmud",
  population: 16733,
};
