import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Papua New Guinea.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const png: CountryData = {
  id: "png",
  name: "Papua New Guinea",
  officialName: "Independent State of Papua New Guinea",
  continent: "Oceania",
  region: "Melanesia",
  callingCode: "675",
  drivingSide: "left",
  flagUrl: "/data/country-flags/png.svg",
  imageUrl: "/data/country-images/png.svg",
  capital: "Port Moresby",
  population: 11781559,
};
