import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Poland.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const pol: CountryData = {
  id: "pol",
  name: "Poland",
  officialName: "Republic of Poland",
  continent: "Europe",
  region: "Central Europe",
  callingCode: "48",
  drivingSide: "right",
  flagUrl: "/data/country-flags/pol.svg",
  imageUrl: "/data/country-images/pol.svg",
  capital: "Warsaw",
  population: 37243000,
};
