import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Puerto Rico.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const pri: CountryData = {
  id: "pri",
  name: "Puerto Rico",
  officialName: "Commonwealth of Puerto Rico",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/country-flags/pri.svg",
  imageUrl: "/data/country-images/pri.svg",
  capital: "San Juan",
  population: 3184195,
};
