import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for North Korea.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const prk: CountryData = {
  id: "prk",
  name: "North Korea",
  officialName: "Democratic People's Republic of Korea",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "850",
  drivingSide: "right",
  flagUrl: "/data/country-flags/prk.svg",
  imageUrl: "/data/country-images/prk.svg",
  capital: "Pyongyang",
  population: 25950000,
};
