import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for North Korea.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const prk: CountryData = {
  id: "prk",
  name: "North Korea",
  nativeName: "조선민주주의인민공화국",
  officialName: "Democratic People's Republic of Korea",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "850",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/prk.svg",
  imageUrl: "/data/global/countries/silhouettes/prk.svg",
  capital: "Pyongyang",
  population: 25950000,
};
