import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Portugal.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const prt: CountryData = {
  id: "prt",
  name: "Portugal",
  officialName: "Portuguese Republic",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "351",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/prt.svg",
  imageUrl: "/data/global/countries/silhouettes/prt.svg",
  capital: "Lisbon",
  population: 11424031,
};
