import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Paraguay.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const pry: CountryData = {
  id: "pry",
  name: "Paraguay",
  officialName: "Republic of Paraguay",
  continent: "South America",
  region: "South America",
  callingCode: "595",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/pry.svg",
  imageUrl: "/data/global/countries/silhouettes/pry.svg",
  capital: "Asunción",
  population: 6109644,
};
