import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Palestine.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const pse: CountryData = {
  id: "pse",
  name: "Palestine",
  officialName: "State of Palestine",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "970",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/pse.svg",
  imageUrl: "/data/global/countries/silhouettes/pse.svg",
  capital: "Ramallah, Jerusalem",
  population: 5557096,
};
