import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for French Polynesia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const pyf: CountryData = {
  id: "pyf",
  name: "French Polynesia",
  officialName: "French Polynesia",
  continent: "Oceania",
  region: "Polynesia",
  callingCode: "689",
  drivingSide: "right",
  flagUrl: "/data/country-flags/pyf.svg",
  imageUrl: "/data/country-images/pyf.svg",
  capital: "Papeetē",
  population: 278786,
};
