import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Qatar.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const qat: CountryData = {
  id: "qat",
  name: "Qatar",
  officialName: "State of Qatar",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "974",
  drivingSide: "right",
  flagUrl: "/data/country-flags/qat.svg",
  imageUrl: "/data/country-images/qat.svg",
  capital: "Doha",
  population: 3370611,
};
