import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Réunion.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const reu: CountryData = {
  id: "reu",
  name: "Réunion",
  officialName: "Réunion Island",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "262",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/reu.svg",
  imageUrl: "/data/global/countries/silhouettes/reu.svg",
  capital: "Saint-Denis",
  population: 840974,
};
