import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Romania.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const rou: CountryData = {
  id: "rou",
  name: "Romania",
  officialName: "Romania",
  continent: "Europe",
  region: "Southeast Europe",
  callingCode: "40",
  drivingSide: "right",
  flagUrl: "/data/country-flags/rou.svg",
  imageUrl: "/data/country-images/rou.svg",
  capital: "Bucharest",
  population: 19041322,
};
