import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Rwanda.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const rwa: CountryData = {
  id: "rwa",
  name: "Rwanda",
  officialName: "Republic of Rwanda",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "250",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/rwa.svg",
  imageUrl: "/data/global/countries/silhouettes/rwa.svg",
  capital: "Kigali",
  population: 14418145,
};
