import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Saudi Arabia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const sau: CountryData = {
  id: "sau",
  name: "Saudi Arabia",
  officialName: "Kingdom of Saudi Arabia",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "966",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/sau.svg",
  imageUrl: "/data/global/countries/silhouettes/sau.svg",
  capital: "Riyadh",
  population: 33702731,
};
