import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Sudan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const sdn: CountryData = {
  id: "sdn",
  name: "Sudan",
  officialName: "Republic of the Sudan",
  continent: "Africa",
  region: "Northern Africa",
  callingCode: "249",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/sdn.svg",
  imageUrl: "/data/global/countries/silhouettes/sdn.svg",
  capital: "Khartoum",
  population: 53282719,
};
