import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Senegal.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const sen: CountryData = {
  id: "sen",
  name: "Senegal",
  officialName: "Republic of Senegal",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "221",
  drivingSide: "right",
  flagUrl: "/data/country-flags/sen.svg",
  imageUrl: "/data/country-images/sen.svg",
  capital: "Dakar",
  population: 19575061,
};
