import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Singapore.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const sgp: CountryData = {
  id: "sgp",
  name: "Singapore",
  officialName: "Republic of Singapore",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "65",
  drivingSide: "left",
  flagUrl: "/data/country-flags/sgp.svg",
  imageUrl: "/data/country-images/sgp.svg",
  capital: "Singapore",
  population: 6110200,
};
