import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for South Georgia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const sgs: CountryData = {
  id: "sgs",
  name: "South Georgia",
  officialName: "South Georgia and the South Sandwich Islands",
  continent: "Antarctica",
  region: "",
  callingCode: "500",
  drivingSide: "right",
  flagUrl: "/data/country-flags/sgs.svg",
  imageUrl: "/data/country-images/sgs.svg",
  capital: "King Edward Point",
  population: 32,
};
