import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Saint Helena, Ascension and Tristan da Cunha.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const shn: CountryData = {
  id: "shn",
  name: "Saint Helena, Ascension and Tristan da Cunha",
  officialName: "Saint Helena, Ascension and Tristan da Cunha",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "290",
  drivingSide: "left",
  flagUrl: "/data/country-flags/shn.svg",
  imageUrl: "/data/country-images/shn.svg",
  capital: "Jamestown",
  population: 53192,
};
