import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Solomon Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const slb: CountryData = {
  id: "slb",
  name: "Solomon Islands",
  officialName: "Solomon Islands",
  continent: "Oceania",
  region: "Melanesia",
  callingCode: "677",
  drivingSide: "left",
  flagUrl: "/data/country-flags/slb.svg",
  imageUrl: "/data/country-images/slb.svg",
  capital: "Honiara",
  population: 828857,
};
