import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for El Salvador.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const slv: CountryData = {
  id: "slv",
  name: "El Salvador",
  officialName: "Republic of El Salvador",
  continent: "North America",
  region: "Central America",
  callingCode: "503",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/slv.svg",
  imageUrl: "/data/global/countries/silhouettes/slv.svg",
  capital: "San Salvador",
  population: 6029976,
};
