import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Somalia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const som: CountryData = {
  id: "som",
  name: "Somalia",
  officialName: "Federal Republic of Somalia",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "252",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/som.svg",
  imageUrl: "/data/global/countries/silhouettes/som.svg",
  capital: "Mogadishu",
  population: 20305907,
};
