import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Saint Pierre and Miquelon.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const spm: CountryData = {
  id: "spm",
  name: "Saint Pierre and Miquelon",
  officialName: "Saint Pierre and Miquelon",
  continent: "North America",
  region: "North America",
  callingCode: "508",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/spm.svg",
  imageUrl: "/data/global/countries/silhouettes/spm.svg",
  capital: "Saint-Pierre",
  population: 5819,
};
