import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Serbia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const srb: CountryData = {
  id: "srb",
  name: "Serbia",
  officialName: "Republic of Serbia",
  continent: "Europe",
  region: "Southeast Europe",
  callingCode: "381",
  drivingSide: "right",
  flagUrl: "/data/country-flags/srb.svg",
  imageUrl: "/data/country-images/srb.svg",
  capital: "Belgrade",
  population: 6532019,
};
