import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for South Sudan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ssd: CountryData = {
  id: "ssd",
  name: "South Sudan",
  officialName: "Republic of South Sudan",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "211",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/ssd.svg",
  imageUrl: "/data/global/countries/silhouettes/ssd.svg",
  capital: "Juba",
  population: 12703714,
};
