import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for São Tomé and Príncipe.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const stp: CountryData = {
  id: "stp",
  name: "São Tomé and Príncipe",
  officialName: "Democratic Republic of São Tomé and Príncipe",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "239",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/stp.svg",
  imageUrl: "/data/global/countries/silhouettes/stp.svg",
  capital: "São Tomé",
  population: 220372,
};
