import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Suriname.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const sur: CountryData = {
  id: "sur",
  name: "Suriname",
  officialName: "Republic of Suriname",
  continent: "South America",
  region: "South America",
  callingCode: "597",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/sur.svg",
  imageUrl: "/data/global/countries/silhouettes/sur.svg",
  capital: "Paramaribo",
  population: 616500,
};
