import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Slovakia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const svk: CountryData = {
  id: "svk",
  name: "Slovakia",
  nativeName: "Slovensko",
  officialName: "Slovak Republic",
  continent: "Europe",
  region: "Central Europe",
  callingCode: "421",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/svk.svg",
  imageUrl: "/data/global/countries/silhouettes/svk.svg",
  capital: "Bratislava",
  population: 5405368,
};
