import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Slovenia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const svn: CountryData = {
  id: "svn",
  name: "Slovenia",
  officialName: "Republic of Slovenia",
  continent: "Europe",
  region: "Central Europe",
  callingCode: "386",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/svn.svg",
  imageUrl: "/data/global/countries/silhouettes/svn.svg",
  capital: "Ljubljana",
  population: 2136385,
};
