import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Sweden.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const swe: CountryData = {
  id: "swe",
  name: "Sweden",
  officialName: "Kingdom of Sweden",
  continent: "Europe",
  region: "Northern Europe",
  callingCode: "46",
  drivingSide: "right",
  flagUrl: "/data/country-flags/swe.svg",
  imageUrl: "/data/country-images/swe.svg",
  capital: "Stockholm",
  population: 10610483,
};
