import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Eswatini.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const swz: CountryData = {
  id: "swz",
  name: "Eswatini",
  officialName: "Kingdom of Eswatini",
  continent: "Africa",
  region: "Southern Africa",
  callingCode: "268",
  drivingSide: "left",
  flagUrl: "/data/country-flags/swz.svg",
  imageUrl: "/data/country-images/swz.svg",
  capital: "Mbabane, Lobamba",
  population: 1235549,
};
