import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Sint Maarten.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const sxm: CountryData = {
  id: "sxm",
  name: "Sint Maarten",
  officialName: "Sint Maarten",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/sxm.svg",
  imageUrl: "/data/global/countries/silhouettes/sxm.svg",
  capital: "Philipsburg",
  population: 58477,
};
