import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Seychelles.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const syc: CountryData = {
  id: "syc",
  name: "Seychelles",
  officialName: "Republic of Seychelles",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "248",
  drivingSide: "left",
  flagUrl: "/data/country-flags/syc.svg",
  imageUrl: "/data/country-images/syc.svg",
  capital: "Victoria",
  population: 123097,
};
