import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Syria.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const syr: CountryData = {
  id: "syr",
  name: "Syria",
  officialName: "Syrian Arab Republic",
  continent: "Asia",
  region: "Western Asia",
  callingCode: "963",
  drivingSide: "right",
  flagUrl: "/data/country-flags/syr.svg",
  imageUrl: "/data/country-images/syr.svg",
  capital: "Damascus",
  population: 26472497,
};
