import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Chad.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const tcd: CountryData = {
  id: "tcd",
  name: "Chad",
  nativeName: "Tchad / تشاد",
  officialName: "Republic of Chad",
  continent: "Africa",
  region: "Middle Africa",
  callingCode: "235",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/tcd.svg",
  imageUrl: "/data/global/countries/silhouettes/tcd.svg",
  capital: "N'Djamena",
  population: 20031602,
};
