import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Togo.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tgo: CountryData = {
  id: "tgo",
  name: "Togo",
  officialName: "Togolese Republic",
  continent: "Africa",
  region: "Western Africa",
  callingCode: "228",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/tgo.svg",
  imageUrl: "/data/global/countries/silhouettes/tgo.svg",
  capital: "Lomé",
  population: 8095498,
};
