import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Thailand.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tha: CountryData = {
  id: "tha",
  name: "Thailand",
  officialName: "Kingdom of Thailand",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "66",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/tha.svg",
  imageUrl: "/data/global/countries/silhouettes/tha.svg",
  capital: "Bangkok",
  population: 70250751,
};
