import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Tajikistan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tjk: CountryData = {
  id: "tjk",
  name: "Tajikistan",
  officialName: "Republic of Tajikistan",
  continent: "Asia",
  region: "Central Asia",
  callingCode: "992",
  drivingSide: "right",
  flagUrl: "/data/country-flags/tjk.svg",
  imageUrl: "/data/country-images/tjk.svg",
  capital: "Dushanbe",
  population: 10721000,
};
