import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Turkmenistan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tkm: CountryData = {
  id: "tkm",
  name: "Turkmenistan",
  officialName: "Turkmenistan",
  continent: "Asia",
  region: "Central Asia",
  callingCode: "993",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/tkm.svg",
  imageUrl: "/data/global/countries/silhouettes/tkm.svg",
  capital: "Ashgabat",
  population: 7057841,
};
