import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Timor-Leste.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tls: CountryData = {
  id: "tls",
  name: "Timor-Leste",
  officialName: "Democratic Republic of Timor-Leste",
  continent: "Oceania",
  region: "South-Eastern Asia",
  callingCode: "670",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/tls.svg",
  imageUrl: "/data/global/countries/silhouettes/tls.svg",
  capital: "Dili",
  population: 1409452,
};
