import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Tonga.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ton: CountryData = {
  id: "ton",
  name: "Tonga",
  officialName: "Kingdom of Tonga",
  continent: "Oceania",
  region: "Polynesia",
  callingCode: "676",
  drivingSide: "left",
  flagUrl: "/data/country-flags/ton.svg",
  imageUrl: "/data/country-images/ton.svg",
  capital: "Nuku'alofa",
  population: 100179,
};
