import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Trinidad and Tobago.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tto: CountryData = {
  id: "tto",
  name: "Trinidad and Tobago",
  officialName: "Republic of Trinidad and Tobago",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/tto.svg",
  imageUrl: "/data/global/countries/silhouettes/tto.svg",
  capital: "Port of Spain",
  population: 1512779,
};
