import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Tunisia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tun: CountryData = {
  id: "tun",
  name: "Tunisia",
  officialName: "Republic of Tunisia",
  continent: "Africa",
  region: "Northern Africa",
  callingCode: "216",
  drivingSide: "right",
  flagUrl: "/data/country-flags/tun.svg",
  imageUrl: "/data/country-images/tun.svg",
  capital: "Tunis",
  population: 11992843,
};
