import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Turkey.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tur: CountryData = {
  id: "tur",
  name: "Turkey",
  officialName: "Republic of Türkiye",
  continent: "Europe",
  region: "Western Asia",
  callingCode: "90",
  drivingSide: "right",
  flagUrl: "/data/country-flags/tur.svg",
  imageUrl: "/data/country-images/tur.svg",
  capital: "Ankara",
  population: 86092168,
};
