import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Taiwan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const twn: CountryData = {
  id: "twn",
  name: "Taiwan",
  officialName: "Republic of China (Taiwan)",
  continent: "Asia",
  region: "Eastern Asia",
  callingCode: "886",
  drivingSide: "right",
  flagUrl: "/data/country-flags/twn.svg",
  imageUrl: "/data/country-images/twn.svg",
  capital: "Taipei",
  population: 23235002,
};
