import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Tanzania.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const tza: CountryData = {
  id: "tza",
  name: "Tanzania",
  officialName: "United Republic of Tanzania",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "255",
  drivingSide: "left",
  flagUrl: "/data/global/countries/flags/tza.svg",
  imageUrl: "/data/global/countries/silhouettes/tza.svg",
  capital: "Dodoma",
  population: 70038850,
};
