import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for United States Minor Outlying Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const umi: CountryData = {
  id: "umi",
  name: "United States Minor Outlying Islands",
  officialName: "United States Minor Outlying Islands",
  continent: "Oceania",
  region: "North America",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/country-flags/umi.svg",
  imageUrl: "/data/country-images/umi.svg",
  capital: "",
  population: 300,
};
