import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Uruguay.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ury: CountryData = {
  id: "ury",
  name: "Uruguay",
  officialName: "Oriental Republic of Uruguay",
  continent: "South America",
  region: "South America",
  callingCode: "598",
  drivingSide: "right",
  flagUrl: "/data/country-flags/ury.svg",
  imageUrl: "/data/country-images/ury.svg",
  capital: "Montevideo",
  population: 3480601,
};
