import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for United States.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const usa: CountryData = {
  id: "usa",
  name: "United States",
  officialName: "United States of America",
  continent: "North America",
  region: "North America",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/country-flags/usa.svg",
  imageUrl: "/data/country-images/usa.svg",
  capital: "Washington, D.C.",
  population: 341784857,
};
