import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Uzbekistan.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const uzb: CountryData = {
  id: "uzb",
  name: "Uzbekistan",
  officialName: "Republic of Uzbekistan",
  continent: "Asia",
  region: "Central Asia",
  callingCode: "998",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/uzb.svg",
  imageUrl: "/data/global/countries/silhouettes/uzb.svg",
  capital: "Tashkent",
  population: 39047321,
};
