import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Vatican City.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-modules.ts
 *
 * Do not edit this file manually.
 */
export const vat: CountryData = {
  id: "vat",
  name: "Vatican City",
  nativeName: "Civitas Vaticana / Città del Vaticano",
  officialName: "Vatican City State",
  continent: "Europe",
  region: "Southern Europe",
  callingCode: "379",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/vat.svg",
  imageUrl: "/data/global/countries/silhouettes/vat.svg",
  capital: "Vatican City",
  population: 882,
};
