import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Saint Vincent and the Grenadines.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const vct: CountryData = {
  id: "vct",
  name: "Saint Vincent and the Grenadines",
  officialName: "Saint Vincent and the Grenadines",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/country-flags/vct.svg",
  imageUrl: "/data/country-images/vct.svg",
  capital: "Kingstown",
  population: 109296,
};
