import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Venezuela.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const ven: CountryData = {
  id: "ven",
  name: "Venezuela",
  officialName: "Bolivarian Republic of Venezuela",
  continent: "South America",
  region: "South America",
  callingCode: "58",
  drivingSide: "right",
  flagUrl: "/data/country-flags/ven.svg",
  imageUrl: "/data/country-images/ven.svg",
  capital: "Caracas",
  population: 28633711,
};
