import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for British Virgin Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const vgb: CountryData = {
  id: "vgb",
  name: "British Virgin Islands",
  officialName: "Virgin Islands",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "left",
  flagUrl: "/data/country-flags/vgb.svg",
  imageUrl: "/data/country-images/vgb.svg",
  capital: "Road Town",
  population: 38322,
};
