import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for United States Virgin Islands.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const vir: CountryData = {
  id: "vir",
  name: "United States Virgin Islands",
  officialName: "Virgin Islands of the United States",
  continent: "North America",
  region: "Caribbean",
  callingCode: "1",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/vir.svg",
  imageUrl: "/data/global/countries/silhouettes/vir.svg",
  capital: "Charlotte Amalie",
  population: 87146,
};
