import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Vietnam.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const vnm: CountryData = {
  id: "vnm",
  name: "Vietnam",
  officialName: "Socialist Republic of Vietnam",
  continent: "Asia",
  region: "South-Eastern Asia",
  callingCode: "84",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/vnm.svg",
  imageUrl: "/data/global/countries/silhouettes/vnm.svg",
  capital: "Hanoi",
  population: 102300000,
};
