import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Vanuatu.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const vut: CountryData = {
  id: "vut",
  name: "Vanuatu",
  officialName: "Republic of Vanuatu",
  continent: "Oceania",
  region: "Melanesia",
  callingCode: "678",
  drivingSide: "right",
  flagUrl: "/data/global/countries/flags/vut.svg",
  imageUrl: "/data/global/countries/silhouettes/vut.svg",
  capital: "Port Vila",
  population: 321409,
};
