import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Wallis and Futuna.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const wlf: CountryData = {
  id: "wlf",
  name: "Wallis and Futuna",
  officialName: "Territory of the Wallis and Futuna Islands",
  continent: "Oceania",
  region: "Polynesia",
  callingCode: "681",
  drivingSide: "right",
  flagUrl: "/data/country-flags/wlf.svg",
  imageUrl: "/data/country-images/wlf.svg",
  capital: "Mata-Utu",
  population: 11151,
};
