import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Samoa.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const wsm: CountryData = {
  id: "wsm",
  name: "Samoa",
  officialName: "Independent State of Samoa",
  continent: "Oceania",
  region: "Polynesia",
  callingCode: "685",
  drivingSide: "left",
  flagUrl: "/data/country-flags/wsm.svg",
  imageUrl: "/data/country-images/wsm.svg",
  capital: "Apia",
  population: 205557,
};
