import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Kosovo.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const xkx: CountryData = {
  id: "xkx",
  name: "Kosovo",
  officialName: "Republic of Kosovo",
  continent: "Europe",
  region: "Southeast Europe",
  callingCode: "383",
  drivingSide: "right",
  flagUrl: "/data/country-flags/xkx.svg",
  imageUrl: "/data/country-images/xkx.svg",
  capital: "Pristina",
  population: 1585566,
};
