import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for South Africa.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const zaf: CountryData = {
  id: "zaf",
  name: "South Africa",
  officialName: "Republic of South Africa",
  continent: "Africa",
  region: "Southern Africa",
  callingCode: "27",
  drivingSide: "left",
  flagUrl: "/data/country-flags/zaf.svg",
  imageUrl: "/data/country-images/zaf.svg",
  capital: "Pretoria, Cape Town, Bloemfontein",
  population: 63015904,
};
