import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Zambia.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const zmb: CountryData = {
  id: "zmb",
  name: "Zambia",
  officialName: "Republic of Zambia",
  continent: "Africa",
  region: "Eastern Africa",
  callingCode: "260",
  drivingSide: "left",
  flagUrl: "/data/country-flags/zmb.svg",
  imageUrl: "/data/country-images/zmb.svg",
  capital: "Lusaka",
  population: 23003214,
};
