import type { CountryData } from "@/types/country";
  
/**
 * Static country metadata for Zimbabwe.
 *
 * This file is generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not edit this file manually.
 */
export const zwe: CountryData = {
  id: "zwe",
  name: "Zimbabwe",
  officialName: "Republic of Zimbabwe",
  continent: "Africa",
  region: "Southern Africa",
  callingCode: "263",
  drivingSide: "left",
  flagUrl: "/data/country-flags/zwe.svg",
  imageUrl: "/data/country-images/zwe.svg",
  capital: "Harare",
  population: 17073087,
};
