from __future__ import annotations

import json
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[4]

GEOJSON_DIR = (
    PROJECT_ROOT
    / "public"
    / "data"
    / "countries"
    / "argentina"
    / "geojson"
)

OUTPUT_PATH = (
    PROJECT_ROOT
    / "src"
    / "quiz"
    / "quizzes"
    / "countries"
    / "argentina"
    / "data"
    / "phoneCodes.ts"
)

DATASETS = {
    "full": {
        "path": GEOJSON_DIR / "phone-codes-full.geojson",
        "export": "ARGENTINA_PHONE_CODES_FULL",
        "expected_count": 300,
    },
    "3-digit": {
        "path": GEOJSON_DIR / "phone-codes-3-digit.geojson",
        "export": "ARGENTINA_PHONE_CODES_3_DIGIT",
        "expected_count": 82,
    },
    "2-digit": {
        "path": GEOJSON_DIR / "phone-codes-2-digit.geojson",
        "export": "ARGENTINA_PHONE_CODES_2_DIGIT",
        "expected_count": 13,
    },
    "1-digit": {
        "path": GEOJSON_DIR / "phone-codes-1-digit.geojson",
        "export": "ARGENTINA_PHONE_CODES_1_DIGIT",
        "expected_count": 3,
    },
}


def load_geojson(
    path: Path,
) -> dict[str, Any]:
    return json.loads(
        path.read_text(
            encoding="utf-8",
        )
    )


def numeric_sort_key(
    value: str,
) -> tuple[int, str]:
    try:
        return (
            int(value),
            value,
        )
    except ValueError:
        return (
            10**9,
            value,
        )


def read_codes(
    label: str,
    path: Path,
    expected_count: int,
) -> list[str]:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing runtime GeoJSON: {path}"
        )

    data = load_geojson(
        path
    )

    if data.get("type") != "FeatureCollection":
        raise RuntimeError(
            f"{label} GeoJSON is not a FeatureCollection."
        )

    features = data.get(
        "features"
    )

    if not isinstance(
        features,
        list,
    ):
        raise RuntimeError(
            f"{label} GeoJSON has no feature list."
        )

    codes: list[str] = []

    for index, feature in enumerate(
        features
    ):
        if not isinstance(
            feature,
            dict,
        ):
            raise RuntimeError(
                f"{label} feature {index} is not an object."
            )

        feature_id = feature.get(
            "id"
        )

        properties = feature.get(
            "properties"
        )

        if not isinstance(
            properties,
            dict,
        ):
            raise RuntimeError(
                f"{label} feature {index} has invalid properties."
            )

        area_code = str(
            properties.get(
                "area_code"
            )
            or ""
        ).strip()

        if not area_code:
            raise RuntimeError(
                f"{label} feature {index} has no area_code."
            )

        if not area_code.isdigit():
            raise RuntimeError(
                f"{label} feature {index} has non-numeric "
                f"area_code {area_code!r}."
            )

        if str(
            feature_id
        ) != area_code:
            raise RuntimeError(
                f"{label} feature {index} has id "
                f"{feature_id!r} but area_code {area_code!r}."
            )

        codes.append(
            area_code
        )

    duplicates = sorted(
        {
            code
            for code in codes
            if codes.count(
                code
            ) > 1
        },
        key=numeric_sort_key,
    )

    if duplicates:
        raise RuntimeError(
            f"{label} contains duplicate area codes: "
            f"{duplicates}"
        )

    if len(codes) != expected_count:
        raise RuntimeError(
            f"{label} expected {expected_count:,} features "
            f"but found {len(codes):,}."
        )

    return sorted(
        codes,
        key=numeric_sort_key,
    )


def typescript_string(
    value: str,
) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
    )


def render_array(
    export_name: str,
    codes: list[str],
) -> str:
    lines = [
        f"export const {export_name} = ["
    ]

    lines.extend(
        f"  {typescript_string(code)},"
        for code in codes
    )

    lines.append(
        "] as const;"
    )

    return "\n".join(
        lines
    )


def build_typescript(
    values_by_level: dict[
        str,
        list[str],
    ],
) -> str:
    sections = [
        """/**
 * AUTO-GENERATED FILE.
 *
 * Generated by:
 *
 *   scripts/countries/argentina/generate/phone-codes-quiz-data.py
 *
 * Do not edit these values manually. Update the Argentina phone-code
 * processing pipeline and rerun the generator instead.
 *
 * Each array contains the exact `area_code` values used by the corresponding
 * runtime GeoJSON. The full/max-depth dataset intentionally contains a mixture
 * of 2-, 3-, and 4-digit Argentine area codes because those are the actual
 * complete area codes represented by the source data.
 */"""
    ]

    for level in (
        "full",
        "3-digit",
        "2-digit",
        "1-digit",
    ):
        config = DATASETS[
            level
        ]

        sections.append(
            render_array(
                config["export"],
                values_by_level[
                    level
                ],
            )
        )

    sections.append(
        """export type ArgentinaPhoneCodeFull =
  (typeof ARGENTINA_PHONE_CODES_FULL)[number];

export type ArgentinaPhoneCode3Digit =
  (typeof ARGENTINA_PHONE_CODES_3_DIGIT)[number];

export type ArgentinaPhoneCode2Digit =
  (typeof ARGENTINA_PHONE_CODES_2_DIGIT)[number];

export type ArgentinaPhoneCode1Digit =
  (typeof ARGENTINA_PHONE_CODES_1_DIGIT)[number];"""
    )

    return (
        "\n\n".join(
            sections
        )
        + "\n"
    )


def main() -> None:
    print(
        "Generating Argentina phone-code quiz data..."
    )

    values_by_level: dict[
        str,
        list[str],
    ] = {}

    for (
        level,
        config,
    ) in DATASETS.items():
        codes = read_codes(
            level,
            config["path"],
            config["expected_count"],
        )

        values_by_level[
            level
        ] = codes

        print(
            f"  {level}: "
            f"{len(codes):,} values"
        )

    full_codes = set(
        values_by_level[
            "full"
        ]
    )

    expected_three = {
        code
        if len(code) <= 3
        else code[:3]
        for code in full_codes
    }

    expected_two = {
        code
        if len(code) <= 2
        else code[:2]
        for code in full_codes
    }

    expected_one = {
        code
        if len(code) <= 1
        else code[:1]
        for code in full_codes
    }

    derived_checks = {
        "3-digit": expected_three,
        "2-digit": expected_two,
        "1-digit": expected_one,
    }

    for (
        level,
        expected,
    ) in derived_checks.items():
        actual = set(
            values_by_level[
                level
            ]
        )

        if actual != expected:
            missing = sorted(
                expected - actual,
                key=numeric_sort_key,
            )

            extra = sorted(
                actual - expected,
                key=numeric_sort_key,
            )

            raise RuntimeError(
                f"{level} runtime codes do not match "
                "the prefixes derived from the full dataset.\n"
                f"Missing: {missing}\n"
                f"Extra: {extra}"
            )

    output = build_typescript(
        values_by_level
    )

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    OUTPUT_PATH.write_text(
        output,
        encoding="utf-8",
    )

    print()
    print(
        f"Wrote: {OUTPUT_PATH}"
    )


if __name__ == "__main__":
    main()