/**
 * Adds GeoPedia-controlled town labels and settlement markers to an existing
 * MapLibre map.
 *
 * GeoPedia's settlement labels replace the base map's city/town/village labels
 * so the two systems do not compete for collision space.
 *
 * Significant settlement markers are rendered as icons inside the same symbol
 * layer as their text. This guarantees a marker cannot remain visible when its
 * associated town name is hidden by MapLibre's collision system.
 */

import type * as maplibregl from "maplibre-gl";

import {
  TOWN_LABEL_LAYER_ID,
  TOWN_SOURCE_ID,
} from "@/maps/constants/mapLayerIds";
import type { TownLabelConfig } from "@/maps/types";

/**
 * Lowest and highest integer town-label tiers generated by the processor.
 */
const MIN_TOWN_LABEL_ZOOM = 3.5;

const MAX_TOWN_LABEL_ZOOM = 14;

/**
 * Runtime image IDs used for settlement markers.
 */
const NO_MARKER_IMAGE_ID = "town-marker-none";

const MAJOR_CITY_MARKER_IMAGE_ID = "town-marker-major-city";

const ADMIN_CAPITAL_MARKER_IMAGE_ID = "town-marker-admin-capital";

const COUNTRY_CAPITAL_MARKER_IMAGE_ID = "town-marker-country-capital";

/**
 * Returns the current map zoom rounded downward to GeoPedia's fractional
 * town-label interval.
 *
 * Quarter-zoom buckets allow labels to enter progressively without forcing
 * MapLibre to rebuild the settlement layer on every animation frame.
 *
 * @param map - MapLibre map whose zoom should be inspected.
 * @returns Current quarter-zoom label tier.
 */
function getActiveTownLabelZoom(map: maplibregl.Map): number {
  const zoom = map.getZoom();

  return Math.floor(zoom * 4) / 4;
}

/**
 * Builds the filter controlling which processed towns are currently eligible.
 *
 * @param activeZoom - Maximum currently eligible label tier.
 * @returns MapLibre expression filter.
 */
function getTownZoomFilter(
  activeZoom: number,
): maplibregl.ExpressionSpecification {
  return [
    "<=",
    ["coalesce", ["get", "labelMinZoom"], MAX_TOWN_LABEL_ZOOM],
    activeZoom,
  ];
}

/**
 * Creates a transparent marker used by ordinary town labels.
 *
 * Every town receives an icon so marker-bearing and non-marker-bearing towns
 * can share one MapLibre symbol layer. The transparent image has effectively
 * no visible footprint.
 *
 * @returns Transparent marker image.
 */
function createTransparentMarker(): ImageData {
  return new ImageData(1, 1);
}

/**
 * Creates a circular cartographic marker.
 *
 * The image is generated at double resolution and registered with
 * `pixelRatio: 2` so it renders sharply on normal and high-density displays.
 *
 * @param radius - Visible marker radius in CSS pixels.
 * @param fillColor - Interior circle color.
 * @param strokeColor - Border color.
 * @param strokeWidth - Border width in CSS pixels.
 * @param innerRadius - Optional inner ring radius.
 * @returns Marker image data.
 */
function createCircleMarker(
  radius: number,
  fillColor: string,
  strokeColor: string,
  strokeWidth: number,
  innerRadius?: number,
): ImageData {
  const pixelRatio = 2;

  const padding = 2;

  const cssSize = (radius + strokeWidth + padding) * 2;

  const size = Math.ceil(cssSize * pixelRatio);

  const canvas = document.createElement("canvas");

  canvas.width = size;

  canvas.height = size;

  const context = canvas.getContext("2d");

  if (!context) {
    throw new Error("Unable to create town marker canvas context.");
  }

  const center = size / 2;

  context.beginPath();

  context.arc(center, center, radius * pixelRatio, 0, Math.PI * 2);

  context.fillStyle = fillColor;

  context.fill();

  context.lineWidth = strokeWidth * pixelRatio;

  context.strokeStyle = strokeColor;

  context.stroke();

  /**
   * National capitals may optionally receive an additional inner ring.
   */
  if (innerRadius !== undefined) {
    context.beginPath();

    context.arc(
      center,
      center,
      innerRadius * pixelRatio,
      0,
      Math.PI * 2,
    );

    context.lineWidth = 1 * pixelRatio;

    context.strokeStyle = strokeColor;

    context.stroke();
  }

  return context.getImageData(0, 0, size, size);
}

/**
 * Registers the marker images consumed by the town symbol layer.
 *
 * Marker visual hierarchy:
 *
 * - Major city: small filled bordered circle.
 * - First-order administrative capital: hollow bordered circle.
 * - Country capital: larger emphasized circle with an inner ring.
 *
 * @param map - MapLibre map receiving marker images.
 */
function registerTownMarkerImages(map: maplibregl.Map): void {
  if (!map.hasImage(NO_MARKER_IMAGE_ID)) {
    map.addImage(NO_MARKER_IMAGE_ID, createTransparentMarker());
  }

  map.addImage(
    MAJOR_CITY_MARKER_IMAGE_ID,
    createCircleMarker(2.5, "rgba(0, 0, 0, 0)", "#303030", 1.25),
    {
      pixelRatio: 2,
    },
  );

  if (!map.hasImage(ADMIN_CAPITAL_MARKER_IMAGE_ID)) {
    map.addImage(
      ADMIN_CAPITAL_MARKER_IMAGE_ID,
      createCircleMarker(3.25, "#ffffff", "#303030", 1.25),
      {
        pixelRatio: 2,
      },
    );
  }

  if (!map.hasImage(COUNTRY_CAPITAL_MARKER_IMAGE_ID)) {
    map.addImage(
      COUNTRY_CAPITAL_MARKER_IMAGE_ID,
      createCircleMarker(4, "#ffffff", "#303030", 1.5, 1.5),
      {
        pixelRatio: 2,
      },
    );
  }
}

/**
 * Applies the current integer zoom tier to the town layer.
 *
 * @param map - MapLibre map containing GeoPedia's town label layer.
 * @param activeZoom - Maximum currently eligible label tier.
 */
function applyTownZoomFilter(
  map: maplibregl.Map,
  activeZoom: number,
): void {
  if (!map.getLayer(TOWN_LABEL_LAYER_ID)) {
    return;
  }

  map.setFilter(TOWN_LABEL_LAYER_ID, getTownZoomFilter(activeZoom));
}

/**
 * Adds GeoPedia's settlement source and combined marker/text symbol layer.
 *
 * Significant marker icons and their text are part of the same symbol. If the
 * complete symbol cannot be placed, neither its marker nor label is rendered.
 *
 * @param map - MapLibre map receiving the settlement system.
 * @param config - Town dataset configuration.
 */
export function addTownLayers(
  map: maplibregl.Map,
  config: TownLabelConfig,
): void {
  /**
   * Register marker artwork before creating a symbol layer that references it.
   */
  registerTownMarkerImages(map);

  /**
   * PMTiles-backed vector source.
   *
   * MapLibre now requests only the vector tiles needed for the current viewport
   * instead of loading the complete processed settlement GeoJSON into memory.
   */
  map.addSource(TOWN_SOURCE_ID, {
    type: "vector",

    url: config.pmtilesUrl,
  });

  const initialZoom = getActiveTownLabelZoom(map);

  /**
   * Combined settlement marker and town-name layer.
   *
   * Ordinary towns use a transparent one-pixel marker while significant
   * settlements receive their processed marker type.
   *
   * Because icon and text belong to one symbol feature, MapLibre's collision
   * engine places or rejects the complete marker-label pair together.
   */
  map.addLayer({
    id: TOWN_LABEL_LAYER_ID,

    type: "symbol",

    source: TOWN_SOURCE_ID,

    "source-layer": config.sourceLayer,

    minzoom: MIN_TOWN_LABEL_ZOOM,

    filter: getTownZoomFilter(initialZoom),

    layout: {
      /**
       * Marker image determined by the processor's `markerType`.
       */
      "icon-image": [
        "match",
        ["get", "markerType"],

        "country-capital",
        COUNTRY_CAPITAL_MARKER_IMAGE_ID,

        "admin-capital",
        ADMIN_CAPITAL_MARKER_IMAGE_ID,

        "major-city",
        MAJOR_CITY_MARKER_IMAGE_ID,

        NO_MARKER_IMAGE_ID,
      ],

      /**
       * Marker and text are treated as one placement unit.
       */
      "icon-allow-overlap": false,
      "icon-ignore-placement": false,
      "icon-optional": false,

      /**
       * Town label.
       */
      "text-field": ["get", "name"],

      "text-font": [
        "match",
        ["get", "significanceTier"],

        0,
        ["literal", ["Noto Sans Bold"]],

        1,
        ["literal", ["Noto Sans SemiBold"]],

        2,
        ["literal", ["Noto Sans SemiBold"]],

        ["literal", ["Noto Sans Regular"]],
      ],

      /**
       * Increase label size gradually as the user zooms closer.
       *
       * Place-specific font weights and colors can be layered onto this after
       * the final density behavior has been validated.
       */
      "text-size": [
        "interpolate",
        ["linear"],
        ["zoom"],

        3,
        [
          "case",

          ["==", ["get", "place"], "suburb"],
          10,

          [
            "match",
            ["get", "significanceTier"],

            0,
            14,

            1,
            13,

            2,
            12,

            3,
            11.5,

            11,
          ],
        ],

        7,
        [
          "case",

          ["==", ["get", "place"], "suburb"],
          11,

          [
            "match",
            ["get", "significanceTier"],

            0,
            15,

            1,
            14,

            2,
            13,

            3,
            12.5,

            12,
          ],
        ],

        11,
        [
          "case",

          ["==", ["get", "place"], "suburb"],
          12,

          [
            "match",
            ["get", "significanceTier"],

            0,
            16,

            1,
            15,

            2,
            14,

            3,
            13.5,

            13,
          ],
        ],

        14,
        [
          "case",

          ["==", ["get", "place"], "suburb"],
          12.5,

          [
            "match",
            ["get", "significanceTier"],

            0,
            16.5,

            1,
            15.5,

            2,
            14.5,

            3,
            14,

            13.5,
          ],
        ],
      ],

      /**
       * The geographic point belongs to the marker. Town text is shifted
       * upward so the point remains visibly centered beneath the name.
       */
      "text-anchor": "bottom",
      "text-offset": [0, -0.15],
      "text-allow-overlap": false,
      "text-ignore-placement": false,
      "text-optional": false,

      /**
       * Higher GeoPedia importance values receive lower sort keys and therefore
       * stronger placement priority when symbols compete.
       */
      "symbol-sort-key": [
        "-",
        0,
        ["coalesce", ["get", "importance"], 0],
      ],
    },

    paint: {
      "text-color": [
        "case",

        ["==", ["get", "place"], "suburb"],

        "#505050",
        "#303030",
      ],

      "text-halo-color": "rgba(255, 255, 255, 0.5)",
      "text-halo-width": 1,
      "text-halo-blur": 0.5,
    },
  });

  /**
   * Update town eligibility only when the map crosses a quarter-zoom boundary.
   *
   * Fractional label tiers remain gradual while avoiding expensive MapLibre
   * relayouts on every animated zoom frame.
   */
  let previousZoomTier = initialZoom;

  map.on("zoomend", () => {
    const activeZoom = getActiveTownLabelZoom(map);

    if (activeZoom === previousZoomTier) {
      return;
    }

    previousZoomTier = activeZoom;

    applyTownZoomFilter(map, activeZoom);
  });
}
