/**
 * Generated Ghana administrative quiz-support data.
 *
 * Do not edit this file manually. Regenerate it with:
 * python scripts/countries/ghana/generate/admin-quiz-data.py
 */

export const GHANA_REGIONS_BY_ID = {
  "GH-AF": {
    name: "Ahafo Region",
  },
  "GH-AH": {
    name: "Ashanti Region",
  },
  "GH-BE": {
    name: "Bono East Region",
  },
  "GH-BO": {
    name: "Bono Region",
  },
  "GH-CP": {
    name: "Central Region",
  },
  "GH-EP": {
    name: "Eastern Region",
  },
  "GH-AA": {
    name: "Greater Accra Region",
  },
  "GH-NE": {
    name: "North East Region",
  },
  "GH-NP": {
    name: "Northern Region",
  },
  "GH-OT": {
    name: "Oti Region",
  },
  "GH-SV": {
    name: "Savannah Region",
  },
  "GH-UE": {
    name: "Upper East Region",
  },
  "GH-UW": {
    name: "Upper West Region",
  },
  "GH-TV": {
    name: "Volta Region",
  },
  "GH-WN": {
    name: "Western North Region",
  },
  "GH-WP": {
    name: "Western Region",
  },
} as const;

export const GHANA_DISTRICTS_BY_ID = {
  "2480657B96138797401471": {
    name: "Asunafo North Municipal",
    regionId: "GH-AF",
    region: "Ahafo Region",
  },
  "2480657B2337940648547": {
    name: "Asunafo South",
    regionId: "GH-AF",
    region: "Ahafo Region",
  },
  "2480657B98266466330064": {
    name: "Asutifi North",
    regionId: "GH-AF",
    region: "Ahafo Region",
  },
  "2480657B57037677938762": {
    name: "Asutifi South",
    regionId: "GH-AF",
    region: "Ahafo Region",
  },
  "2480657B68079094729511": {
    name: "Tano North Municipal",
    regionId: "GH-AF",
    region: "Ahafo Region",
  },
  "2480657B7981851544250": {
    name: "Tano South Municipal",
    regionId: "GH-AF",
    region: "Ahafo Region",
  },
  "2480657B88279606337785": {
    name: "Adansi Akrofuom",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B45906044715427": {
    name: "Adansi Asokwa",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B92670413622569": {
    name: "Adansi North",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B97463209696641": {
    name: "Adansi South",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B47912218033723": {
    name: "Afigya Kwabre North",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B27047738560833": {
    name: "Afigya Kwabre South",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B6504340506710": {
    name: "Ahafo Ano North",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B91945870955547": {
    name: "Ahafo Ano South East",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B58897854519282": {
    name: "Ahafo Ano South West",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B25462964367622": {
    name: "Amansie Central",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B37143689168174": {
    name: "Amansie South",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B59515552665793": {
    name: "Amansie West",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B1767599566587": {
    name: "Asante Akim Central Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B62831767110058": {
    name: "Asante Akim North",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B39079904074923": {
    name: "Asante Akim South",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B67032672358324": {
    name: "Asokore Mampong Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B91188187265148": {
    name: "Asokwa  Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B14749544754301": {
    name: "Atwima Kwanwoma",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B25907117051030": {
    name: "Atwima Mponua",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B14484334363928": {
    name: "Atwima Nwabiagya North",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B44972771575405": {
    name: "Atwima Nwabiagya South",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B55478680834493": {
    name: "Bekwai Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B30283206314404": {
    name: "Bosome Freho",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B90441463194933": {
    name: "Bosomtwe",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B74771824828795": {
    name: "Ejisu Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B28564915274944": {
    name: "Ejura-sekyedumase",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B53382680619634": {
    name: "Juaben Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B53854728613413": {
    name: "Kumasi Metropolitan",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B60556198830817": {
    name: "Kwabre East",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B94630675221037": {
    name: "Kwadaso Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B66784074859314": {
    name: "Mampong Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B26017273678273": {
    name: "Obuasi East",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B43720081643569": {
    name: "Obuasi Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B80894926360364": {
    name: "Offinso Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B15542052325310": {
    name: "Offinso North",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B70835976798974": {
    name: "Oforikrom Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B10806173713075": {
    name: "Old Tafo Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B37542209080123": {
    name: "Sekyere Afram Plains North",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B47319682331963": {
    name: "Sekyere Central",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B61321065662810": {
    name: "Sekyere East",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B32008532681061": {
    name: "Sekyere Kumawu",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B66267254954762": {
    name: "Sekyere South",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B48966175900279": {
    name: "Suame Municipal",
    regionId: "GH-AH",
    region: "Ashanti Region",
  },
  "2480657B7685147466351": {
    name: "Atebubu Amantin",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B78031413348906": {
    name: "Kintampo North Municipal",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B51466124780551": {
    name: "Kintampo South",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B63998169387071": {
    name: "Nkoranza North",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B38880944597072": {
    name: "Nkoranza South",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B24672710685383": {
    name: "Pru East",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B32965552352903": {
    name: "Pru West",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B21050367867823": {
    name: "Sene East",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B37380438315906": {
    name: "Sene West",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B78695952433486": {
    name: "Techiman Municipal",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B75157144819377": {
    name: "Techiman North",
    regionId: "GH-BE",
    region: "Bono East Region",
  },
  "2480657B21856882152043": {
    name: "Banda",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B78254100433505": {
    name: "Berekum East Municipal",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B54527757245703": {
    name: "Berekum West",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B16380673722667": {
    name: "Dormaa East",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B85939384202988": {
    name: "Dormaa Municipal",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B11503231198633": {
    name: "Dormaa West",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B44306962794399": {
    name: "Jaman North",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B92052873943163": {
    name: "Jaman South Municipal",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B55840347650819": {
    name: "Sunyani Municipal",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B93462158202754": {
    name: "Sunyani West",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B14065489870616": {
    name: "Tain",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B27014820297576": {
    name: "Wenchi Municipal",
    regionId: "GH-BO",
    region: "Bono Region",
  },
  "2480657B30493820921": {
    name: "Abura-asebu-kwamankese",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B54607197552612": {
    name: "Agona East",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B39435178884870": {
    name: "Agona West Municipal",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B3117094904377": {
    name: "Ajumako-enyan-essiam",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B2595733520620": {
    name: "Asikuma-odoben-brakwa",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B24956698199939": {
    name: "Assin Fosu",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B44214183650816": {
    name: "Assin North",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B73071492710762": {
    name: "Assin South",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B19246099956301": {
    name: "Awutu Senya",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B20036139360918": {
    name: "Awutu Senya East",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B31989943834082": {
    name: "Cape Coast Metropolitan",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B83789922051105": {
    name: "Effutu Municipal",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B22323593180175": {
    name: "Ekumfi",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B15531990631346": {
    name: "Gomoa Central",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B26264719340764": {
    name: "Gomoa East",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B81635079362570": {
    name: "Gomoa West",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B89828953333594": {
    name: "Komenda-edina-eguafo-abirem Municipal",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B5340678211162": {
    name: "Mfantseman Municipal",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B2289284937660": {
    name: "Twifo Atti-morkwa",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B44541331554905": {
    name: "Twifo Hemang Lower Denkyira",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B45731574572143": {
    name: "Upper Denkyira East Municipal",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B72362309510067": {
    name: "Upper Denkyira West",
    regionId: "GH-CP",
    region: "Central Region",
  },
  "2480657B42374646075926": {
    name: "Abuakwa North",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B6434141016984": {
    name: "Abuakwa South",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B77450065295387": {
    name: "Achiase",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B16553972090858": {
    name: "Akwapem North",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B26354408705676": {
    name: "Akwapem South",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B32538733435540": {
    name: "Akyem Mansa",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B68278489034036": {
    name: "Asene Akroso Manso",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B37277876999120": {
    name: "Asuogyaman",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B7526405183619": {
    name: "Atiwa East",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B65169023596143": {
    name: "Atiwa West",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B11085167902059": {
    name: "Ayensuano",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B80684943588404": {
    name: "Birim Central Municipal",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B81401264659986": {
    name: "Birim North",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B71012260699376": {
    name: "Birim South",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B53762921220630": {
    name: "Denkyembour",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B42231307300111": {
    name: "Fanteakwa North",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B5172435396617": {
    name: "Fanteakwa South",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B54074930978119": {
    name: "Kwaebibirem",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B6837938265733": {
    name: "Kwahu Afram Plains North",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B87039075961323": {
    name: "Kwahu Afram Plains South",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B54162505201867": {
    name: "Kwahu East",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B68408124911047": {
    name: "Kwahu South",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B50723205918173": {
    name: "Kwahu West",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B54302337253194": {
    name: "Lower Manya",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B95199515281033": {
    name: "New Juaben North Municipal",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B86034404720136": {
    name: "New Juaben South Municipal",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B74727980909537": {
    name: "Nsawam Adoagyiri",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B59311092791004": {
    name: "Okere",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B2570339807900": {
    name: "Suhum Municipal",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B72113427832631": {
    name: "Upper Manya",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B98999442599484": {
    name: "Upper West Akim",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B57614018833162": {
    name: "West Akim",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B63323125119927": {
    name: "Yilo Krobo",
    regionId: "GH-EP",
    region: "Eastern Region",
  },
  "2480657B99533750399286": {
    name: "Ablekuma Central Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B23952932171735": {
    name: "Ablekuma North Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B12570528382412": {
    name: "Ablekuma West Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B11720749290533": {
    name: "Accra Metropolis",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B57636315193797": {
    name: "Ada East",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B39710750100206": {
    name: "Ada West",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B26321648161032": {
    name: "Adenta Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B85535261310615": {
    name: "Ashaiman Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B92273702685271": {
    name: "Ayawaso Central Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B29980074443403": {
    name: "Ayawaso East Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B42813544323317": {
    name: "Ayawaso North Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B22724340600972": {
    name: "Ayawaso West",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B96936068561499": {
    name: "Ga Central Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B24635332146555": {
    name: "Ga East",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B39319620746428": {
    name: "Ga North Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B41485746076017": {
    name: "Ga South Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B90617621807510": {
    name: "Ga West Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B35357833911053": {
    name: "Korle Klottey Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B63581433334614": {
    name: "Kpone Katamanso",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B96734395613726": {
    name: "Krowor Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B88791559733000": {
    name: "La Dade-kotopon",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B60779202001283": {
    name: "La-nkwantanang-madina",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B94892111901595": {
    name: "Ledzokuku Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B81968156308620": {
    name: "Ningo/prampram",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B77934780741907": {
    name: "Okaikwei North Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B66464396810782": {
    name: "Shai Osudoku",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B34044169329977": {
    name: "Tema Metropolitan",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B69717792501029": {
    name: "Tema West Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B6669757606157": {
    name: "Weija Gbawe Municipal",
    regionId: "GH-AA",
    region: "Greater Accra Region",
  },
  "2480657B78318361422462": {
    name: "Bunkpurugu Nakpanduri",
    regionId: "GH-NE",
    region: "North East Region",
  },
  "2480657B14989848452061": {
    name: "Chereponi",
    regionId: "GH-NE",
    region: "North East Region",
  },
  "2480657B84792930556748": {
    name: "East Mamprusi",
    regionId: "GH-NE",
    region: "North East Region",
  },
  "2480657B18075285363234": {
    name: "Mamprugu Moagduri",
    regionId: "GH-NE",
    region: "North East Region",
  },
  "2480657B90334619080238": {
    name: "West Mamprusi Municipal",
    regionId: "GH-NE",
    region: "North East Region",
  },
  "2480657B16330149254954": {
    name: "Yunyoo-nasuan",
    regionId: "GH-NE",
    region: "North East Region",
  },
  "2480657B56494255769768": {
    name: "Gushegu",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B76285553918092": {
    name: "Karaga",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B93484130612637": {
    name: "Kpandai",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B99246651758289": {
    name: "Kumbungu",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B42193515445029": {
    name: "Mion",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B96271436146347": {
    name: "Nanton",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B57712569843933": {
    name: "Nanumba North",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B24752518727633": {
    name: "Nanumba South",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B56307698722921": {
    name: "Saboba",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B87566941811639": {
    name: "Sagnerigu",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B27215926841583": {
    name: "Savelugu",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B1027184338147": {
    name: "Tamale Metropolitan",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B76540044095481": {
    name: "Tatale Sanguli",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B36155100412367": {
    name: "Tolon",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B94460481801793": {
    name: "Yendi Municipal",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B72410528378772": {
    name: "Zabzugu",
    regionId: "GH-NP",
    region: "Northern Region",
  },
  "2480657B27736636353654": {
    name: "Biakoye",
    regionId: "GH-OT",
    region: "Oti Region",
  },
  "2480657B79217814678772": {
    name: "Jasikan",
    regionId: "GH-OT",
    region: "Oti Region",
  },
  "2480657B29295475961782": {
    name: "Kadjebi",
    regionId: "GH-OT",
    region: "Oti Region",
  },
  "2480657B4921606442052": {
    name: "Krachi East Municipal",
    regionId: "GH-OT",
    region: "Oti Region",
  },
  "2480657B73751367479109": {
    name: "Krachi Nchumuru",
    regionId: "GH-OT",
    region: "Oti Region",
  },
  "2480657B78422611914106": {
    name: "Krachi West",
    regionId: "GH-OT",
    region: "Oti Region",
  },
  "2480657B6503151283934": {
    name: "Nkwanta North",
    regionId: "GH-OT",
    region: "Oti Region",
  },
  "2480657B13680530894334": {
    name: "Nkwanta South Municipal",
    regionId: "GH-OT",
    region: "Oti Region",
  },
  "2480657B39398526932747": {
    name: "Bole",
    regionId: "GH-SV",
    region: "Savannah Region",
  },
  "2480657B60919857809422": {
    name: "Central Gonja",
    regionId: "GH-SV",
    region: "Savannah Region",
  },
  "2480657B20562210440652": {
    name: "East Gonja Municipal",
    regionId: "GH-SV",
    region: "Savannah Region",
  },
  "2480657B30922977157044": {
    name: "North East Gonja",
    regionId: "GH-SV",
    region: "Savannah Region",
  },
  "2480657B69696031481498": {
    name: "North Gonja",
    regionId: "GH-SV",
    region: "Savannah Region",
  },
  "2480657B66384530229883": {
    name: "Sawla-tuna-kalba",
    regionId: "GH-SV",
    region: "Savannah Region",
  },
  "2480657B54445116346139": {
    name: "West Gonja",
    regionId: "GH-SV",
    region: "Savannah Region",
  },
  "2480657B67017614982997": {
    name: "Bawku Municipal",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B35637781657714": {
    name: "Bawku West",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B66646573774103": {
    name: "Binduri",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B19171272300465": {
    name: "Bolga  East",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B19364380807593": {
    name: "Bolgatanga Municipal",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B66034837272834": {
    name: "Bongo",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B79468660523811": {
    name: "Builsa North",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B50810028950834": {
    name: "Builsa South",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B97498759939018": {
    name: "Garu",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B68256913631937": {
    name: "Kasena Nankana East",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B70680953475259": {
    name: "Kasena Nankana West",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B74414618551217": {
    name: "Nabdam",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B9973692574538": {
    name: "Pusiga",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B26285365473669": {
    name: "Talensi",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B5704764806917": {
    name: "Tempane",
    regionId: "GH-UE",
    region: "Upper East Region",
  },
  "2480657B92911606303429": {
    name: "Daffiama Bussie Issa",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B21686152565613": {
    name: "Jirapa",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B9523556036154": {
    name: "Lambussie-karni",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B49975124320145": {
    name: "Lawra",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B27045720373273": {
    name: "Nadowli-kaleo",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B7958262081913": {
    name: "Nandom",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B88326891244380": {
    name: "Sissala East",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B76140913943028": {
    name: "Sissala West",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B52594370214383": {
    name: "Wa East",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B26357719954092": {
    name: "Wa Municipal",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B35206472883168": {
    name: "Wa West",
    regionId: "GH-UW",
    region: "Upper West Region",
  },
  "2480657B20696154785284": {
    name: "Adaklu",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B45105521184723": {
    name: "Afadzato South",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B11620193732867": {
    name: "Agotime Ziope",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B78562505377679": {
    name: "Akatsi North",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B79730913179219": {
    name: "Akatsi South",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B74011824532465": {
    name: "Anloga",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B36678414015123": {
    name: "Central Tongu",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B35240131522033": {
    name: "Ho Municipal",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B47242267083805": {
    name: "Ho West",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B20464126159243": {
    name: "Hohoe Municipal",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B20833842549797": {
    name: "Keta Municipal",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B52907018957478": {
    name: "Ketu North",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B7709388821831": {
    name: "Ketu South",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B39800519073464": {
    name: "Kpando Municipal",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B8553529614763": {
    name: "North Dayi",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B35012095074914": {
    name: "North Tongu",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B27395942809935": {
    name: "South Dayi",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B92948775681515": {
    name: "South Tongu",
    regionId: "GH-TV",
    region: "Volta Region",
  },
  "2480657B72501418673064": {
    name: "Aowin",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B75704309897075": {
    name: "Bia East",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B58435284570364": {
    name: "Bia West",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B81329004729189": {
    name: "Bibiani-anhwiaso-bekwai Municipal",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B1960270363323": {
    name: "Bodi",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B56579001772859": {
    name: "Juaboso",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B96818528094138": {
    name: "Sefwi Akontombra",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B7942392054994": {
    name: "Sefwi-wiawso",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B41275879010095": {
    name: "Suaman",
    regionId: "GH-WN",
    region: "Western North Region",
  },
  "2480657B81057694902297": {
    name: "Ahanta West Municipal",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B49181902253284": {
    name: "Effia Kwesimintsim Municipal",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B39512912083476": {
    name: "Ellembelle",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B70421803893954": {
    name: "Jomoro",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B89256099008264": {
    name: "Mpohor",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B37092877755739": {
    name: "Nzema East",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B71205229821948": {
    name: "Prestea/huni Valley",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B3368374944964": {
    name: "Sekondi Takoradi Metropolis",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B99130964172058": {
    name: "Shama",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B19905724513669": {
    name: "Tarkwa Nsuaem",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B10255028610816": {
    name: "Wassa Amenfi Central",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B15365927336493": {
    name: "Wassa Amenfi East",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B13145859726554": {
    name: "Wassa Amenfi West",
    regionId: "GH-WP",
    region: "Western Region",
  },
  "2480657B7921909152770": {
    name: "Wassa East",
    regionId: "GH-WP",
    region: "Western Region",
  },
} as const;
