/**
 * Registry and lookup helpers for GeoPedia country metadata.
 *
 * The country imports and registry entries in this file are generated by:
 *
 *   scripts/generate/generate-country-data-objects.ts
 *
 * Do not add generated country imports manually.
 */

import { CountryData } from "@/types/country";

import { abw } from "./data/abw";
import { afg } from "./data/afg";
import { ago } from "./data/ago";
import { aia } from "./data/aia";
import { ala } from "./data/ala";
import { alb } from "./data/alb";
import { and } from "./data/and";
import { are } from "./data/are";
import { arg } from "./data/arg";
import { arm } from "./data/arm";
import { asm } from "./data/asm";
import { ata } from "./data/ata";
import { atf } from "./data/atf";
import { atg } from "./data/atg";
import { aus } from "./data/aus";
import { aut } from "./data/aut";
import { aze } from "./data/aze";
import { bdi } from "./data/bdi";
import { bel } from "./data/bel";
import { ben } from "./data/ben";
import { bfa } from "./data/bfa";
import { bgd } from "./data/bgd";
import { bgr } from "./data/bgr";
import { bhr } from "./data/bhr";
import { bhs } from "./data/bhs";
import { bih } from "./data/bih";
import { blm } from "./data/blm";
import { blr } from "./data/blr";
import { blz } from "./data/blz";
import { bmu } from "./data/bmu";
import { bol } from "./data/bol";
import { bra } from "./data/bra";
import { brb } from "./data/brb";
import { brn } from "./data/brn";
import { btn } from "./data/btn";
import { bwa } from "./data/bwa";
import { caf } from "./data/caf";
import { can } from "./data/can";
import { che } from "./data/che";
import { chl } from "./data/chl";
import { chn } from "./data/chn";
import { civ } from "./data/civ";
import { cmr } from "./data/cmr";
import { cod } from "./data/cod";
import { cog } from "./data/cog";
import { cok } from "./data/cok";
import { col } from "./data/col";
import { com } from "./data/com";
import { cpv } from "./data/cpv";
import { cri } from "./data/cri";
import { cub } from "./data/cub";
import { cuw } from "./data/cuw";
import { cym } from "./data/cym";
import { cyp } from "./data/cyp";
import { cze } from "./data/cze";
import { deu } from "./data/deu";
import { dji } from "./data/dji";
import { dma } from "./data/dma";
import { dnk } from "./data/dnk";
import { dom } from "./data/dom";
import { dza } from "./data/dza";
import { ecu } from "./data/ecu";
import { egy } from "./data/egy";
import { eri } from "./data/eri";
import { esh } from "./data/esh";
import { esp } from "./data/esp";
import { est } from "./data/est";
import { eth } from "./data/eth";
import { fin } from "./data/fin";
import { fji } from "./data/fji";
import { flk } from "./data/flk";
import { fra } from "./data/fra";
import { fro } from "./data/fro";
import { fsm } from "./data/fsm";
import { gab } from "./data/gab";
import { gbr } from "./data/gbr";
import { geo } from "./data/geo";
import { ggy } from "./data/ggy";
import { gha } from "./data/gha";
import { gib } from "./data/gib";
import { gin } from "./data/gin";
import { gmb } from "./data/gmb";
import { gnb } from "./data/gnb";
import { gnq } from "./data/gnq";
import { grc } from "./data/grc";
import { grd } from "./data/grd";
import { grl } from "./data/grl";
import { gtm } from "./data/gtm";
import { gum } from "./data/gum";
import { guy } from "./data/guy";
import { hkg } from "./data/hkg";
import { hmd } from "./data/hmd";
import { hnd } from "./data/hnd";
import { hrv } from "./data/hrv";
import { hti } from "./data/hti";
import { hun } from "./data/hun";
import { idn } from "./data/idn";
import { imn } from "./data/imn";
import { ind } from "./data/ind";
import { iot } from "./data/iot";
import { irl } from "./data/irl";
import { irn } from "./data/irn";
import { irq } from "./data/irq";
import { isl } from "./data/isl";
import { isr } from "./data/isr";
import { ita } from "./data/ita";
import { jam } from "./data/jam";
import { jey } from "./data/jey";
import { jor } from "./data/jor";
import { jpn } from "./data/jpn";
import { kaz } from "./data/kaz";
import { ken } from "./data/ken";
import { kgz } from "./data/kgz";
import { khm } from "./data/khm";
import { kir } from "./data/kir";
import { kna } from "./data/kna";
import { kor } from "./data/kor";
import { kwt } from "./data/kwt";
import { lao } from "./data/lao";
import { lbn } from "./data/lbn";
import { lbr } from "./data/lbr";
import { lby } from "./data/lby";
import { lca } from "./data/lca";
import { lie } from "./data/lie";
import { lka } from "./data/lka";
import { lso } from "./data/lso";
import { ltu } from "./data/ltu";
import { lux } from "./data/lux";
import { lva } from "./data/lva";
import { mac } from "./data/mac";
import { maf } from "./data/maf";
import { mar } from "./data/mar";
import { mco } from "./data/mco";
import { mda } from "./data/mda";
import { mdg } from "./data/mdg";
import { mdv } from "./data/mdv";
import { mex } from "./data/mex";
import { mhl } from "./data/mhl";
import { mkd } from "./data/mkd";
import { mli } from "./data/mli";
import { mlt } from "./data/mlt";
import { mmr } from "./data/mmr";
import { mne } from "./data/mne";
import { mng } from "./data/mng";
import { mnp } from "./data/mnp";
import { moz } from "./data/moz";
import { mrt } from "./data/mrt";
import { msr } from "./data/msr";
import { mus } from "./data/mus";
import { mwi } from "./data/mwi";
import { mys } from "./data/mys";
import { nam } from "./data/nam";
import { ncl } from "./data/ncl";
import { ner } from "./data/ner";
import { nfk } from "./data/nfk";
import { nga } from "./data/nga";
import { nic } from "./data/nic";
import { niu } from "./data/niu";
import { nld } from "./data/nld";
import { nor } from "./data/nor";
import { npl } from "./data/npl";
import { nru } from "./data/nru";
import { nzl } from "./data/nzl";
import { omn } from "./data/omn";
import { pak } from "./data/pak";
import { pan } from "./data/pan";
import { pcn } from "./data/pcn";
import { per } from "./data/per";
import { phl } from "./data/phl";
import { plw } from "./data/plw";
import { png } from "./data/png";
import { pol } from "./data/pol";
import { pri } from "./data/pri";
import { prk } from "./data/prk";
import { prt } from "./data/prt";
import { pry } from "./data/pry";
import { pse } from "./data/pse";
import { pyf } from "./data/pyf";
import { qat } from "./data/qat";
import { reu } from "./data/reu";
import { rou } from "./data/rou";
import { rus } from "./data/rus";
import { rwa } from "./data/rwa";
import { sau } from "./data/sau";
import { sdn } from "./data/sdn";
import { sen } from "./data/sen";
import { sgp } from "./data/sgp";
import { sgs } from "./data/sgs";
import { shn } from "./data/shn";
import { slb } from "./data/slb";
import { sle } from "./data/sle";
import { slv } from "./data/slv";
import { smr } from "./data/smr";
import { som } from "./data/som";
import { spm } from "./data/spm";
import { srb } from "./data/srb";
import { ssd } from "./data/ssd";
import { stp } from "./data/stp";
import { sur } from "./data/sur";
import { svk } from "./data/svk";
import { svn } from "./data/svn";
import { swe } from "./data/swe";
import { swz } from "./data/swz";
import { sxm } from "./data/sxm";
import { syc } from "./data/syc";
import { syr } from "./data/syr";
import { tca } from "./data/tca";
import { tcd } from "./data/tcd";
import { tgo } from "./data/tgo";
import { tha } from "./data/tha";
import { tjk } from "./data/tjk";
import { tkm } from "./data/tkm";
import { tls } from "./data/tls";
import { ton } from "./data/ton";
import { tto } from "./data/tto";
import { tun } from "./data/tun";
import { tur } from "./data/tur";
import { tuv } from "./data/tuv";
import { twn } from "./data/twn";
import { tza } from "./data/tza";
import { uga } from "./data/uga";
import { ukr } from "./data/ukr";
import { umi } from "./data/umi";
import { ury } from "./data/ury";
import { usa } from "./data/usa";
import { uzb } from "./data/uzb";
import { vat } from "./data/vat";
import { vct } from "./data/vct";
import { ven } from "./data/ven";
import { vgb } from "./data/vgb";
import { vir } from "./data/vir";
import { vnm } from "./data/vnm";
import { vut } from "./data/vut";
import { wlf } from "./data/wlf";
import { wsm } from "./data/wsm";
import { xkx } from "./data/xkx";
import { yem } from "./data/yem";
import { zaf } from "./data/zaf";
import { zmb } from "./data/zmb";
import { zwe } from "./data/zwe";

/**
 * Static country metadata keyed by lowercase ISO-A3 country ID.
 */
const countries: Partial<Record<string, CountryData>> = {
  abw,
  afg,
  ago,
  aia,
  ala,
  alb,
  and,
  are,
  arg,
  arm,
  asm,
  ata,
  atf,
  atg,
  aus,
  aut,
  aze,
  bdi,
  bel,
  ben,
  bfa,
  bgd,
  bgr,
  bhr,
  bhs,
  bih,
  blm,
  blr,
  blz,
  bmu,
  bol,
  bra,
  brb,
  brn,
  btn,
  bwa,
  caf,
  can,
  che,
  chl,
  chn,
  civ,
  cmr,
  cod,
  cog,
  cok,
  col,
  com,
  cpv,
  cri,
  cub,
  cuw,
  cym,
  cyp,
  cze,
  deu,
  dji,
  dma,
  dnk,
  dom,
  dza,
  ecu,
  egy,
  eri,
  esh,
  esp,
  est,
  eth,
  fin,
  fji,
  flk,
  fra,
  fro,
  fsm,
  gab,
  gbr,
  geo,
  ggy,
  gha,
  gib,
  gin,
  gmb,
  gnb,
  gnq,
  grc,
  grd,
  grl,
  gtm,
  gum,
  guy,
  hkg,
  hmd,
  hnd,
  hrv,
  hti,
  hun,
  idn,
  imn,
  ind,
  iot,
  irl,
  irn,
  irq,
  isl,
  isr,
  ita,
  jam,
  jey,
  jor,
  jpn,
  kaz,
  ken,
  kgz,
  khm,
  kir,
  kna,
  kor,
  kwt,
  lao,
  lbn,
  lbr,
  lby,
  lca,
  lie,
  lka,
  lso,
  ltu,
  lux,
  lva,
  mac,
  maf,
  mar,
  mco,
  mda,
  mdg,
  mdv,
  mex,
  mhl,
  mkd,
  mli,
  mlt,
  mmr,
  mne,
  mng,
  mnp,
  moz,
  mrt,
  msr,
  mus,
  mwi,
  mys,
  nam,
  ncl,
  ner,
  nfk,
  nga,
  nic,
  niu,
  nld,
  nor,
  npl,
  nru,
  nzl,
  omn,
  pak,
  pan,
  pcn,
  per,
  phl,
  plw,
  png,
  pol,
  pri,
  prk,
  prt,
  pry,
  pse,
  pyf,
  qat,
  reu,
  rou,
  rus,
  rwa,
  sau,
  sdn,
  sen,
  sgp,
  sgs,
  shn,
  slb,
  sle,
  slv,
  smr,
  som,
  spm,
  srb,
  ssd,
  stp,
  sur,
  svk,
  svn,
  swe,
  swz,
  sxm,
  syc,
  syr,
  tca,
  tcd,
  tgo,
  tha,
  tjk,
  tkm,
  tls,
  ton,
  tto,
  tun,
  tur,
  tuv,
  twn,
  tza,
  uga,
  ukr,
  umi,
  ury,
  usa,
  uzb,
  vat,
  vct,
  ven,
  vgb,
  vir,
  vnm,
  vut,
  wlf,
  wsm,
  xkx,
  yem,
  zaf,
  zmb,
  zwe,
};

/**
 * Returns country metadata for an ISO-A3 country ID.
 *
 * Country IDs are normalized to lowercase so callers may safely provide IDs
 * from routes, map features, or other external sources without duplicating
 * normalization logic.
 */
export function getCountry(
  countryId: string,
): CountryData | undefined {
  return countries[countryId.toLowerCase()];
}

/**
 * Returns every country represented by a GeoPedia country page.
 */
export function getCountries(): CountryData[] {
  return Object.values(countries).filter(
    (country): country is CountryData =>
      country !== undefined,
  );
}
