/**
 * Full Mexican state/entity names keyed by their two-digit INEGI ID.
 */
export const MEXICO_STATE_NAMES_BY_ID = {
  "01": "Aguascalientes",
  "02": "Baja California",
  "03": "Baja California Sur",
  "04": "Campeche",
  "05": "Coahuila de Zaragoza",
  "06": "Colima",
  "07": "Chiapas",
  "08": "Chihuahua",
  "09": "Ciudad de México",
  "10": "Durango",
  "11": "Guanajuato",
  "12": "Guerrero",
  "13": "Hidalgo",
  "14": "Jalisco",
  "15": "México",
  "16": "Michoacán de Ocampo",
  "17": "Morelos",
  "18": "Nayarit",
  "19": "Nuevo León",
  "20": "Oaxaca",
  "21": "Puebla",
  "22": "Querétaro",
  "23": "Quintana Roo",
  "24": "San Luis Potosí",
  "25": "Sinaloa",
  "26": "Sonora",
  "27": "Tabasco",
  "28": "Tamaulipas",
  "29": "Tlaxcala",
  "30": "Veracruz de Ignacio de la Llave",
  "31": "Yucatán",
  "32": "Zacatecas",
} as const;

/**
 * Conventional Mexican state/entity abbreviations keyed by INEGI ID.
 */
export const MEXICO_STATE_ABBREVIATIONS_BY_ID = {
  "01": "Ags.",
  "02": "B.C.",
  "03": "B.C.S.",
  "04": "Camp.",
  "05": "Coah.",
  "06": "Col.",
  "07": "Chis.",
  "08": "Chih.",
  "09": "CDMX",
  "10": "Dgo.",
  "11": "Gto.",
  "12": "Gro.",
  "13": "Hgo.",
  "14": "Jal.",
  "15": "Méx.",
  "16": "Mich.",
  "17": "Mor.",
  "18": "Nay.",
  "19": "N.L.",
  "20": "Oax.",
  "21": "Pue.",
  "22": "Qro.",
  "23": "Q. Roo",
  "24": "S.L.P.",
  "25": "Sin.",
  "26": "Son.",
  "27": "Tab.",
  "28": "Tamps.",
  "29": "Tlax.",
  "30": "Ver.",
  "31": "Yuc.",
  "32": "Zac.",
} as const;
