/**
 * Generated question data for Malaysia's area-code-prefix quizzes.
 *
 * Source:
 * public/data/countries/malaysia/geojson/area-code-prefixes-1.geojson
 * public/data/countries/malaysia/geojson/area-code-prefixes-2.geojson
 *
 * Regenerate with:
 * python scripts/countries/asia/malaysia/generate/area-code-quiz-data.py
 *
 * Do not edit this file manually.
 */

import { FeatureQuizQuestion } from "@/types/quiz";

export const MALAYSIA_AREA_CODE_PREFIX_1_QUESTIONS: FeatureQuizQuestion[] = [
  { answer: "03", display: "03-" },
  { answer: "04", display: "04-" },
  { answer: "05", display: "05-" },
  { answer: "06", display: "06-" },
  { answer: "07", display: "07-" },
  { answer: "08", display: "08-" },
  { answer: "09", display: "09-" },
];

export const MALAYSIA_AREA_CODE_PREFIX_2_QUESTIONS: FeatureQuizQuestion[] = [
  { answer: "032" },
  { answer: "033" },
  { answer: "034" },
  { answer: "035" },
  { answer: "036" },
  { answer: "037" },
  { answer: "038" },
  { answer: "039" },
  { answer: "042" },
  { answer: "044" },
  { answer: "045" },
  { answer: "046" },
  { answer: "047" },
  { answer: "048" },
  { answer: "049" },
  { answer: "052" },
  { answer: "053" },
  { answer: "054" },
  { answer: "055" },
  { answer: "056" },
  { answer: "057" },
  { answer: "058" },
  { answer: "062" },
  { answer: "063" },
  { answer: "064" },
  { answer: "065" },
  { answer: "066" },
  { answer: "067" },
  { answer: "069" },
  { answer: "072" },
  { answer: "074" },
  { answer: "075" },
  { answer: "076" },
  { answer: "077" },
  { answer: "078" },
  { answer: "079" },
  { answer: "082" },
  { answer: "083" },
  { answer: "084" },
  { answer: "085" },
  { answer: "086" },
  { answer: "087" },
  { answer: "088" },
  { answer: "089" },
  { answer: "092" },
  { answer: "093" },
  { answer: "094" },
  { answer: "095" },
  { answer: "096" },
  { answer: "097" },
  { answer: "098" },
  { answer: "099" },
];
