/**
 * Defines the Canada Census Divisions quiz.
 *
 * Statistics Canada CDUIDs are used as answer values so every census
 * division remains uniquely identifiable. Visible questions include both
 * the census division name and its province or territory.
 *
 * Questions are generated from the processed census division GeoJSON and
 * can be grouped by province or territory.
 */
import type { FeatureQuiz } from "@/types/quiz";

const CANADA_CENSUS_DIVISION_QUESTIONS = [
    { answer: "2488", display: "Abitibi" },
    { answer: "2487", display: "Abitibi-Ouest" },
    { answer: "2448", display: "Acton" },
    { answer: "5923", display: "Alberni-Clayoquot" },
    { answer: "1306", display: "Albert" },
    { answer: "3557", display: "Algoma" },
    { answer: "1205", display: "Annapolis" },
    { answer: "1214", display: "Antigonish" },
    { answer: "2479", display: "Antoine-Labelle" },
    { answer: "2476", display: "Argenteuil" },
    { answer: "2439", display: "Arthabaska" },
    { answer: "2406", display: "Avignon" },
    { answer: "2429", display: "Beauce-Sartigan" },
    { answer: "2470", display: "Beauharnois-Salaberry" },
    { answer: "2419", display: "Bellechasse" },
    { answer: "2405", display: "Bonaventure" },
    { answer: "3529", display: "Brant" },
    { answer: "2446", display: "Brome-Missisquoi" },
    { answer: "3541", display: "Bruce" },
    { answer: "5951", display: "Bulkley-Nechako" },
    { answer: "2438", display: "Bécancour" },
    { answer: "1217", display: "Cape Breton" },
    { answer: "5917", display: "Capital" },
    { answer: "5941", display: "Cariboo" },
    { answer: "1311", display: "Carleton" },
    { answer: "5945", display: "Central Coast" },
    { answer: "5903", display: "Central Kootenay" },
    { answer: "5935", display: "Central Okanagan" },
    { answer: "2416", display: "Charlevoix" },
    { answer: "2415", display: "Charlevoix-Est" },
    { answer: "1302", display: "Charlotte" },
    { answer: "3536", display: "Chatham-Kent" },
    { answer: "2444", display: "Coaticook" },
    { answer: "3556", display: "Cochrane" },
    { answer: "1210", display: "Colchester" },
    { answer: "5939", display: "Columbia-Shuswap" },
    { answer: "2401", display: "Communauté maritime des Îles-de-la-Madeleine" },
    { answer: "5926", display: "Comox Valley" },
    { answer: "5919", display: "Cowichan Valley" },
    { answer: "1211", display: "Cumberland" },
    { answer: "2452", display: "D'Autray" },
    { answer: "2472", display: "Deux-Montagnes" },
    { answer: "1203", display: "Digby" },
    { answer: "4801", display: "Division No.  1, Alberta" },
    { answer: "4601", display: "Division No.  1, Manitoba" },
    { answer: "1001", display: "Division No.  1, Newfoundland and Labrador" },
    { answer: "4701", display: "Division No.  1, Saskatchewan" },
    { answer: "4802", display: "Division No.  2, Alberta" },
    { answer: "4602", display: "Division No.  2, Manitoba" },
    { answer: "1002", display: "Division No.  2, Newfoundland and Labrador" },
    { answer: "4702", display: "Division No.  2, Saskatchewan" },
    { answer: "4803", display: "Division No.  3, Alberta" },
    { answer: "4603", display: "Division No.  3, Manitoba" },
    { answer: "1003", display: "Division No.  3, Newfoundland and Labrador" },
    { answer: "4703", display: "Division No.  3, Saskatchewan" },
    { answer: "4804", display: "Division No.  4, Alberta" },
    { answer: "4604", display: "Division No.  4, Manitoba" },
    { answer: "1004", display: "Division No.  4, Newfoundland and Labrador" },
    { answer: "4704", display: "Division No.  4, Saskatchewan" },
    { answer: "4805", display: "Division No.  5, Alberta" },
    { answer: "4605", display: "Division No.  5, Manitoba" },
    { answer: "1005", display: "Division No.  5, Newfoundland and Labrador" },
    { answer: "4705", display: "Division No.  5, Saskatchewan" },
    { answer: "4806", display: "Division No.  6, Alberta" },
    { answer: "4606", display: "Division No.  6, Manitoba" },
    { answer: "1006", display: "Division No.  6, Newfoundland and Labrador" },
    { answer: "4706", display: "Division No.  6, Saskatchewan" },
    { answer: "4807", display: "Division No.  7, Alberta" },
    { answer: "4607", display: "Division No.  7, Manitoba" },
    { answer: "1007", display: "Division No.  7, Newfoundland and Labrador" },
    { answer: "4707", display: "Division No.  7, Saskatchewan" },
    { answer: "4808", display: "Division No.  8, Alberta" },
    { answer: "4608", display: "Division No.  8, Manitoba" },
    { answer: "1008", display: "Division No.  8, Newfoundland and Labrador" },
    { answer: "4708", display: "Division No.  8, Saskatchewan" },
    { answer: "4809", display: "Division No.  9, Alberta" },
    { answer: "4609", display: "Division No.  9, Manitoba" },
    { answer: "1009", display: "Division No.  9, Newfoundland and Labrador" },
    { answer: "4709", display: "Division No.  9, Saskatchewan" },
    { answer: "4810", display: "Division No. 10, Alberta" },
    { answer: "4610", display: "Division No. 10, Manitoba" },
    { answer: "1010", display: "Division No. 10, Newfoundland and Labrador" },
    { answer: "4710", display: "Division No. 10, Saskatchewan" },
    { answer: "4811", display: "Division No. 11, Alberta" },
    { answer: "4611", display: "Division No. 11, Manitoba" },
    { answer: "1011", display: "Division No. 11, Newfoundland and Labrador" },
    { answer: "4711", display: "Division No. 11, Saskatchewan" },
    { answer: "4812", display: "Division No. 12, Alberta" },
    { answer: "4612", display: "Division No. 12, Manitoba" },
    { answer: "4712", display: "Division No. 12, Saskatchewan" },
    { answer: "4813", display: "Division No. 13, Alberta" },
    { answer: "4613", display: "Division No. 13, Manitoba" },
    { answer: "4713", display: "Division No. 13, Saskatchewan" },
    { answer: "4814", display: "Division No. 14, Alberta" },
    { answer: "4614", display: "Division No. 14, Manitoba" },
    { answer: "4714", display: "Division No. 14, Saskatchewan" },
    { answer: "4815", display: "Division No. 15, Alberta" },
    { answer: "4615", display: "Division No. 15, Manitoba" },
    { answer: "4715", display: "Division No. 15, Saskatchewan" },
    { answer: "4816", display: "Division No. 16, Alberta" },
    { answer: "4616", display: "Division No. 16, Manitoba" },
    { answer: "4716", display: "Division No. 16, Saskatchewan" },
    { answer: "4817", display: "Division No. 17, Alberta" },
    { answer: "4617", display: "Division No. 17, Manitoba" },
    { answer: "4717", display: "Division No. 17, Saskatchewan" },
    { answer: "4818", display: "Division No. 18, Alberta" },
    { answer: "4618", display: "Division No. 18, Manitoba" },
    { answer: "4718", display: "Division No. 18, Saskatchewan" },
    { answer: "4819", display: "Division No. 19, Alberta" },
    { answer: "4619", display: "Division No. 19, Manitoba" },
    { answer: "4620", display: "Division No. 20, Manitoba" },
    { answer: "4621", display: "Division No. 21, Manitoba" },
    { answer: "4622", display: "Division No. 22, Manitoba" },
    { answer: "4623", display: "Division No. 23, Manitoba" },
    { answer: "2449", display: "Drummond" },
    { answer: "3522", display: "Dufferin" },
    { answer: "3518", display: "Durham" },
    { answer: "5901", display: "East Kootenay" },
    { answer: "3534", display: "Elgin" },
    { answer: "3537", display: "Essex" },
    { answer: "2437", display: "Francheville" },
    { answer: "5909", display: "Fraser Valley" },
    { answer: "5953", display: "Fraser-Fort George" },
    { answer: "3510", display: "Frontenac" },
    { answer: "2481", display: "Gatineau" },
    { answer: "1315", display: "Gloucester" },
    { answer: "3553", display: "Greater Sudbury / Grand Sudbury" },
    { answer: "5915", display: "Greater Vancouver" },
    { answer: "3542", display: "Grey" },
    { answer: "1213", display: "Guysborough" },
    { answer: "3528", display: "Haldimand-Norfolk" },
    { answer: "3546", display: "Haliburton" },
    { answer: "1209", display: "Halifax" },
    { answer: "3524", display: "Halton" },
    { answer: "3525", display: "Hamilton" },
    { answer: "1208", display: "Hants" },
    { answer: "3512", display: "Hastings" },
    { answer: "3540", display: "Huron" },
    { answer: "1215", display: "Inverness" },
    { answer: "2461", display: "Joliette" },
    { answer: "2414", display: "Kamouraska" },
    { answer: "3516", display: "Kawartha Lakes" },
    { answer: "3560", display: "Kenora" },
    { answer: "1308", display: "Kent" },
    { answer: "1101", display: "Kings" },
    { answer: "1207", display: "Kings" },
    { answer: "1305", display: "Kings" },
    { answer: "6208", display: "Kitikmeot" },
    { answer: "5949", display: "Kitimat-Stikine" },
    { answer: "6205", display: "Kivalliq" },
    { answer: "5905", display: "Kootenay Boundary" },
    { answer: "2460", display: "L'Assomption" },
    { answer: "2417", display: "L'Islet" },
    { answer: "2432", display: "L'Érable" },
    { answer: "2420", display: "L'Île-d'Orléans" },
    { answer: "2421", display: "La Côte-de-Beaupré" },
    { answer: "2403", display: "La Côte-de-Gaspé" },
    { answer: "2495", display: "La Haute-Côte-Nord" },
    { answer: "2404", display: "La Haute-Gaspésie" },
    { answer: "2447", display: "La Haute-Yamaska" },
    { answer: "2422", display: "La Jacques-Cartier" },
    { answer: "2408", display: "La Matanie" },
    { answer: "2407", display: "La Matapédia" },
    { answer: "2409", display: "La Mitis" },
    { answer: "2426", display: "La Nouvelle-Beauce" },
    { answer: "2475", display: "La Rivière-du-Nord" },
    { answer: "2490", display: "La Tuque" },
    { answer: "2489", display: "La Vallée-de-l'Or" },
    { answer: "2483", display: "La Vallée-de-la-Gatineau" },
    { answer: "2457", display: "La Vallée-du-Richelieu" },
    { answer: "2493", display: "Lac-Saint-Jean-Est" },
    { answer: "3538", display: "Lambton" },
    { answer: "3509", display: "Lanark" },
    { answer: "2465", display: "Laval" },
    { answer: "2491", display: "Le Domaine-du-Roy" },
    { answer: "2430", display: "Le Granit" },
    { answer: "2456", display: "Le Haut-Richelieu" },
    { answer: "2441", display: "Le Haut-Saint-François" },
    { answer: "2469", display: "Le Haut-Saint-Laurent" },
    { answer: "2402", display: "Le Rocher-Percé" },
    { answer: "2494", display: "Le Saguenay-et-son-Fjord" },
    { answer: "2442", display: "Le Val-Saint-François" },
    { answer: "3507", display: "Leeds and Grenville" },
    { answer: "3511", display: "Lennox and Addington" },
    { answer: "2431", display: "Les Appalaches" },
    { answer: "2411", display: "Les Basques" },
    { answer: "2482", display: "Les Collines-de-l'Outaouais" },
    { answer: "2428", display: "Les Etchemins" },
    { answer: "2468", display: "Les Jardins-de-Napierville" },
    { answer: "2478", display: "Les Laurentides" },
    { answer: "2454", display: "Les Maskoutains" },
    { answer: "2464", display: "Les Moulins" },
    { answer: "2477", display: "Les Pays-d'en-Haut" },
    { answer: "2440", display: "Les Sources" },
    { answer: "2458", display: "Longueuil" },
    { answer: "2433", display: "Lotbinière" },
    { answer: "1206", display: "Lunenburg" },
    { answer: "2425", display: "Lévis" },
    { answer: "1313", display: "Madawaska" },
    { answer: "2496", display: "Manicouagan" },
    { answer: "3551", display: "Manitoulin" },
    { answer: "2459", display: "Marguerite-D'Youville" },
    { answer: "2492", display: "Maria-Chapdelaine" },
    { answer: "2451", display: "Maskinongé" },
    { answer: "2462", display: "Matawinie" },
    { answer: "2445", display: "Memphrémagog" },
    { answer: "3539", display: "Middlesex" },
    { answer: "2498", display: "Minganie--Le Golfe-du-Saint-Laurent" },
    { answer: "2474", display: "Mirabel" },
    { answer: "2463", display: "Montcalm" },
    { answer: "2418", display: "Montmagny" },
    { answer: "2466", display: "Montréal" },
    { answer: "5943", display: "Mount Waddington" },
    { answer: "3544", display: "Muskoka" },
    { answer: "2435", display: "Mékinac" },
    { answer: "5921", display: "Nanaimo" },
    { answer: "3526", display: "Niagara" },
    { answer: "2450", display: "Nicolet-Yamaska" },
    { answer: "3548", display: "Nipissing" },
    { answer: "2499", display: "Nord-du-Québec" },
    { answer: "5937", display: "North Okanagan" },
    { answer: "5959", display: "Northern Rockies" },
    { answer: "1309", display: "Northumberland" },
    { answer: "3514", display: "Northumberland" },
    { answer: "5907", display: "Okanagan-Similkameen" },
    { answer: "3506", display: "Ottawa" },
    { answer: "3532", display: "Oxford" },
    { answer: "2480", display: "Papineau" },
    { answer: "3549", display: "Parry Sound" },
    { answer: "5955", display: "Peace River" },
    { answer: "3521", display: "Peel" },
    { answer: "3531", display: "Perth" },
    { answer: "3515", display: "Peterborough" },
    { answer: "1212", display: "Pictou" },
    { answer: "2453", display: "Pierre-De Saurel" },
    { answer: "2484", display: "Pontiac" },
    { answer: "2434", display: "Portneuf" },
    { answer: "5927", display: "Powell River" },
    { answer: "3502", display: "Prescott and Russell" },
    { answer: "1103", display: "Prince" },
    { answer: "3513", display: "Prince Edward" },
    { answer: "6204", display: "Qikiqtaaluk" },
    { answer: "1102", display: "Queens" },
    { answer: "1204", display: "Queens" },
    { answer: "1304", display: "Queens" },
    { answer: "2423", display: "Québec" },
    { answer: "3559", display: "Rainy River" },
    { answer: "6101", display: "Region 1, Northwest Territories" },
    { answer: "6102", display: "Region 2, Northwest Territories" },
    { answer: "6103", display: "Region 3, Northwest Territories" },
    { answer: "6104", display: "Region 4, Northwest Territories" },
    { answer: "6105", display: "Region 5, Northwest Territories" },
    { answer: "6106", display: "Region 6, Northwest Territories" },
    { answer: "3547", display: "Renfrew" },
    { answer: "1314", display: "Restigouche" },
    { answer: "1216", display: "Richmond" },
    { answer: "2410", display: "Rimouski-Neigette" },
    { answer: "2412", display: "Rivière-du-Loup" },
    { answer: "2427", display: "Robert-Cliche" },
    { answer: "2467", display: "Roussillon" },
    { answer: "2455", display: "Rouville" },
    { answer: "2486", display: "Rouyn-Noranda" },
    { answer: "1301", display: "Saint John" },
    { answer: "2497", display: "Sept-Rivières--Caniapiscau" },
    { answer: "2436", display: "Shawinigan" },
    { answer: "1201", display: "Shelburne" },
    { answer: "2443", display: "Sherbrooke" },
    { answer: "3543", display: "Simcoe" },
    { answer: "5947", display: "Skeena-Queen Charlotte" },
    { answer: "5931", display: "Squamish-Lillooet" },
    { answer: "5957", display: "Stikine" },
    { answer: "3501", display: "Stormont, Dundas and Glengarry" },
    { answer: "5924", display: "Strathcona" },
    { answer: "3552", display: "Sudbury" },
    { answer: "1303", display: "Sunbury" },
    { answer: "5929", display: "Sunshine Coast" },
    { answer: "5933", display: "Thompson-Nicola" },
    { answer: "3558", display: "Thunder Bay" },
    { answer: "2473", display: "Thérèse-De Blainville" },
    { answer: "3554", display: "Timiskaming" },
    { answer: "3520", display: "Toronto" },
    { answer: "2485", display: "Témiscamingue" },
    { answer: "2413", display: "Témiscouata" },
    { answer: "2471", display: "Vaudreuil-Soulanges" },
    { answer: "1218", display: "Victoria" },
    { answer: "1312", display: "Victoria" },
    { answer: "3530", display: "Waterloo" },
    { answer: "3523", display: "Wellington" },
    { answer: "1307", display: "Westmorland" },
    { answer: "1202", display: "Yarmouth" },
    { answer: "1310", display: "York" },
    { answer: "3519", display: "York" },
    { answer: "6001", display: "Yukon" },
];

const CANADA_CENSUS_DIVISIONS_DESCRIPTION =
  `Learn ${CANADA_CENSUS_DIVISION_QUESTIONS.length} census divisions across Canada, including counties, regional districts, regional county municipalities, and other county-equivalent statistical regions.`;

export const canadaCensusDivisionsQuiz: FeatureQuiz = {
  id: "canada-census-divisions",
  name: "Canada Census Divisions",
  description: CANADA_CENSUS_DIVISIONS_DESCRIPTION,
  kind: "feature",
  mapId: "canada-census-divisions",
  answerProperty: "cduid",
  answerType: "single",
  baseMapLayers: {
    subdivisionLabels: false,
  },
  grouping: {
    properties: [
      {
        property: "province",
        label: "Province / Territory",
        valueType: "string",
      },
    ],
  },
  questions: CANADA_CENSUS_DIVISION_QUESTIONS,
};
