/**
 * AUTO-GENERATED FILE.
 *
 * Generated by:
 *
 *   scripts/countries/panama/generate/admin-quizzes.ts
 *
 * Do not edit the question list manually. Update the processed Panama
 * corregimiento GeoJSON or generator and rerun the script instead.
 */

import type { FeatureQuiz } from "@/types/quiz";

import { PANAMA_DISTRICT_NAMES_BY_ID } from "./districtsQuiz";
import { PANAMA_PROVINCE_COMARCA_NAMES_BY_ID } from "./provincesComarcasQuiz";

/**
 * Questions for Panama's Corregimientos quiz.
 *
 * Repeated corregimiento names are qualified by district. If the same name
 * occurs more than once within the same district, its stable administrative
 * ID is also included in the display label.
 */
const PANAMA_CORREGIMIENTO_QUESTIONS = [
  {
    answer: "010101",
    display: "Bocas del Toro",
  },
  {
    answer: "010102",
    display: "Bastimentos",
  },
  {
    answer: "010104",
    display: "Punta Laurel",
  },
  {
    answer: "010105",
    display: "Tierra Oscura",
  },
  {
    answer: "010106",
    display: "Bocas del Drago",
  },
  {
    answer: "010107",
    display: "San Cristóbal",
  },
  {
    answer: "010201",
    display: "Changuinola",
  },
  {
    answer: "010203",
    display: "Guabito",
  },
  {
    answer: "010204",
    display: "El Teribe",
  },
  {
    answer: "010206",
    display: "El Empalme",
  },
  {
    answer: "010207",
    display: "Las Tablas (Changuinola)",
  },
  {
    answer: "010208",
    display: "Cochigró",
  },
  {
    answer: "010209",
    display: "La Gloria",
  },
  {
    answer: "010210",
    display: "Las Delicias",
  },
  {
    answer: "010213",
    display: "Barriada 4 de Abril",
  },
  {
    answer: "010214",
    display: "El Silencio",
  },
  {
    answer: "010215",
    display: "Finca 6",
  },
  {
    answer: "010216",
    display: "Finca 30",
  },
  {
    answer: "010217",
    display: "Finca 60",
  },
  {
    answer: "010218",
    display: "Barranco Adentro",
  },
  {
    answer: "010219",
    display: "Finca 4",
  },
  {
    answer: "010220",
    display: "Finca 12",
  },
  {
    answer: "010221",
    display: "Finca 51",
  },
  {
    answer: "010222",
    display: "Finca 66",
  },
  {
    answer: "010223",
    display: "La Mesa (Changuinola)",
  },
  {
    answer: "010301",
    display: "Chiriquí Grande",
  },
  {
    answer: "010302",
    display: "Miramar (Chiriquí Grande)",
  },
  {
    answer: "010303",
    display: "Punta Peña",
  },
  {
    answer: "010304",
    display: "Punta Róbalo",
  },
  {
    answer: "010305",
    display: "Rambala",
  },
  {
    answer: "010306",
    display: "Bajo Cedro",
  },
  {
    answer: "010401",
    display: "Almirante",
  },
  {
    answer: "010402",
    display: "Barrio Francés",
  },
  {
    answer: "010404",
    display: "Nance de Riscó",
  },
  {
    answer: "010405",
    display: "Valle de Agua Arriba",
  },
  {
    answer: "010406",
    display: "Valle de Riscó",
  },
  {
    answer: "010407",
    display: "Bajo Culubre",
  },
  {
    answer: "010408",
    display: "Cauchero",
  },
  {
    answer: "010409",
    display: "Ceiba",
  },
  {
    answer: "010410",
    display: "Miraflores",
  },
  {
    answer: "020101",
    display: "Aguadulce",
  },
  {
    answer: "020102",
    display: "El Cristo (Aguadulce)",
  },
  {
    answer: "020103",
    display: "El Roble",
  },
  {
    answer: "020104",
    display: "Pocrí (Aguadulce)",
  },
  {
    answer: "020105",
    display: "Barrios Unidos",
  },
  {
    answer: "020106",
    display: "Pueblos Unidos",
  },
  {
    answer: "020107",
    display: "Virgen del Carmen",
  },
  {
    answer: "020108",
    display: "El Hato de San Juan de Dios",
  },
  {
    answer: "020201",
    display: "Antón",
  },
  {
    answer: "020202",
    display: "Cabuya (Antón)",
  },
  {
    answer: "020203",
    display: "El Chirú",
  },
  {
    answer: "020204",
    display: "El Retiro",
  },
  {
    answer: "020205",
    display: "El Valle",
  },
  {
    answer: "020206",
    display: "Juan Díaz (Antón)",
  },
  {
    answer: "020207",
    display: "Río Hato",
  },
  {
    answer: "020208",
    display: "San Juan de Dios",
  },
  {
    answer: "020209",
    display: "Santa Rita (Antón)",
  },
  {
    answer: "020210",
    display: "Caballero",
  },
  {
    answer: "020301",
    display: "La Pintada",
  },
  {
    answer: "020302",
    display: "El Harino",
  },
  {
    answer: "020303",
    display: "El Potrero (La Pintada)",
  },
  {
    answer: "020304",
    display: "Llano Grande (La Pintada)",
  },
  {
    answer: "020305",
    display: "Piedras Gordas",
  },
  {
    answer: "020306",
    display: "Las Lomas (La Pintada)",
  },
  {
    answer: "020307",
    display: "Llano Norte",
  },
  {
    answer: "020401",
    display: "Natá",
  },
  {
    answer: "020402",
    display: "Capellanía",
  },
  {
    answer: "020403",
    display: "El Caño",
  },
  {
    answer: "020404",
    display: "Guzmán",
  },
  {
    answer: "020405",
    display: "Las Huacas (Natá)",
  },
  {
    answer: "020406",
    display: "Toza",
  },
  {
    answer: "020407",
    display: "Villarreal",
  },
  {
    answer: "020501",
    display: "Olá",
  },
  {
    answer: "020502",
    display: "El Copé",
  },
  {
    answer: "020503",
    display: "El Palmar (Olá)",
  },
  {
    answer: "020504",
    display: "El Picacho",
  },
  {
    answer: "020505",
    display: "La Pava",
  },
  {
    answer: "020601",
    display: "Penonomé",
  },
  {
    answer: "020602",
    display: "Cañaveral (Penonomé)",
  },
  {
    answer: "020603",
    display: "Coclé",
  },
  {
    answer: "020604",
    display: "Chiguirí Arriba",
  },
  {
    answer: "020605",
    display: "El Coco (Penonomé)",
  },
  {
    answer: "020606",
    display: "Pajonal",
  },
  {
    answer: "020607",
    display: "Río Grande (Penonomé)",
  },
  {
    answer: "020608",
    display: "Río Indio (Penonomé)",
  },
  {
    answer: "020609",
    display: "San Miguel (Penonomé)",
  },
  {
    answer: "020610",
    display: "Tulú",
  },
  {
    answer: "020611",
    display: "Candelario Ovalle",
  },
  {
    answer: "020612",
    display: "Las Minas (Penonomé)",
  },
  {
    answer: "020613",
    display: "Reicito",
  },
  {
    answer: "020614",
    display: "Toabré",
  },
  {
    answer: "020615",
    display: "Tucue",
  },
  {
    answer: "020616",
    display: "Victoriano Lorenzo (Penonomé)",
  },
  {
    answer: "030101",
    display: "Barrio Norte",
  },
  {
    answer: "030102",
    display: "Barrio Sur",
  },
  {
    answer: "030103",
    display: "Buena Vista",
  },
  {
    answer: "030104",
    display: "Cativá",
  },
  {
    answer: "030105",
    display: "Ciricito",
  },
  {
    answer: "030106",
    display: "Cristóbal",
  },
  {
    answer: "030107",
    display: "Escobal",
  },
  {
    answer: "030108",
    display: "Limón",
  },
  {
    answer: "030109",
    display: "Nueva Providencia",
  },
  {
    answer: "030110",
    display: "Puerto Pilón",
  },
  {
    answer: "030111",
    display: "Sabanitas",
  },
  {
    answer: "030112",
    display: "Salamanca",
  },
  {
    answer: "030113",
    display: "San Juan (Colón)",
  },
  {
    answer: "030114",
    display: "Santa Rosa (Colón)",
  },
  {
    answer: "030115",
    display: "Cristóbal Este",
  },
  {
    answer: "030201",
    display: "Nuevo Chagres",
  },
  {
    answer: "030202",
    display: "Achiote",
  },
  {
    answer: "030203",
    display: "El Guabo",
  },
  {
    answer: "030204",
    display: "La Encantada",
  },
  {
    answer: "030205",
    display: "Palmas Bellas",
  },
  {
    answer: "030206",
    display: "Piña",
  },
  {
    answer: "030207",
    display: "Salud",
  },
  {
    answer: "030301",
    display: "Miguel de La Borda",
  },
  {
    answer: "030302",
    display: "Coclé del Norte",
  },
  {
    answer: "030303",
    display: "El Guásimo (Donoso)",
  },
  {
    answer: "030304",
    display: "Gobea",
  },
  {
    answer: "030305",
    display: "Río Indio (Donoso)",
  },
  {
    answer: "030401",
    display: "Portobelo",
  },
  {
    answer: "030402",
    display: "Cacique",
  },
  {
    answer: "030403",
    display: "Puerto Lindo o Garrote",
  },
  {
    answer: "030404",
    display: "Isla Grande",
  },
  {
    answer: "030405",
    display: "María Chiquita",
  },
  {
    answer: "030501",
    display: "Palenque",
  },
  {
    answer: "030502",
    display: "Cuango",
  },
  {
    answer: "030503",
    display: "Miramar (Santa Isabel)",
  },
  {
    answer: "030504",
    display: "Nombre de Dios",
  },
  {
    answer: "030505",
    display: "Palmira (Santa Isabel)",
  },
  {
    answer: "030506",
    display: "Playa Chiquita",
  },
  {
    answer: "030507",
    display: "Santa Isabel",
  },
  {
    answer: "030508",
    display: "Viento Frío",
  },
  {
    answer: "030601",
    display: "San José  del General",
  },
  {
    answer: "030602",
    display: "Nueva Esperanza",
  },
  {
    answer: "030603",
    display: "San Juan de Turbe",
  },
  {
    answer: "040101",
    display: "Alanje",
  },
  {
    answer: "040102",
    display: "Divalá",
  },
  {
    answer: "040103",
    display: "El Tejar",
  },
  {
    answer: "040104",
    display: "Guarumal (Alanje)",
  },
  {
    answer: "040105",
    display: "Palo Grande",
  },
  {
    answer: "040106",
    display: "Querévalo",
  },
  {
    answer: "040107",
    display: "Santo Tomás",
  },
  {
    answer: "040108",
    display: "Canta Gallo",
  },
  {
    answer: "040109",
    display: "Nuevo México",
  },
  {
    answer: "040201",
    display: "Puerto Armuelles",
  },
  {
    answer: "040202",
    display: "Limones",
  },
  {
    answer: "040203",
    display: "Progreso",
  },
  {
    answer: "040204",
    display: "Baco",
  },
  {
    answer: "040205",
    display: "Rodolfo Aguilar Delgado",
  },
  {
    answer: "040206",
    display: "El Palmar (Barú)",
  },
  {
    answer: "040207",
    display: "Manaca",
  },
  {
    answer: "040301",
    display: "Boquerón",
  },
  {
    answer: "040302",
    display: "Bágala",
  },
  {
    answer: "040303",
    display: "Cordillera",
  },
  {
    answer: "040304",
    display: "Guabal",
  },
  {
    answer: "040305",
    display: "Guayabal",
  },
  {
    answer: "040306",
    display: "Paraíso (Boquerón)",
  },
  {
    answer: "040307",
    display: "Pedregal (Boquerón)",
  },
  {
    answer: "040308",
    display: "Tijeras",
  },
  {
    answer: "040401",
    display: "Bajo Boquete o Boquete",
  },
  {
    answer: "040402",
    display: "Caldera",
  },
  {
    answer: "040403",
    display: "Palmira (Boquete)",
  },
  {
    answer: "040404",
    display: "Alto Boquete",
  },
  {
    answer: "040405",
    display: "Jaramillo",
  },
  {
    answer: "040406",
    display: "Los Naranjos",
  },
  {
    answer: "040501",
    display: "La Concepción",
  },
  {
    answer: "040502",
    display: "Aserrío de Gariché",
  },
  {
    answer: "040503",
    display: "Bugaba",
  },
  {
    answer: "040505",
    display: "Gómez",
  },
  {
    answer: "040506",
    display: "La Estrella",
  },
  {
    answer: "040507",
    display: "San Andrés",
  },
  {
    answer: "040508",
    display: "Santa Marta",
  },
  {
    answer: "040509",
    display: "Santa Rosa (Bugaba)",
  },
  {
    answer: "040510",
    display: "Santo Domingo (Bugaba)",
  },
  {
    answer: "040511",
    display: "Sortová",
  },
  {
    answer: "040513",
    display: "El Bongo",
  },
  {
    answer: "040514",
    display: "Solano",
  },
  {
    answer: "040515",
    display: "San Isidro",
  },
  {
    answer: "040601",
    display: "David",
  },
  {
    answer: "040602",
    display: "Bijagual",
  },
  {
    answer: "040603",
    display: "Cochea",
  },
  {
    answer: "040604",
    display: "Chiriquí",
  },
  {
    answer: "040605",
    display: "Guacá",
  },
  {
    answer: "040606",
    display: "Las Lomas (David)",
  },
  {
    answer: "040607",
    display: "Pedregal (David)",
  },
  {
    answer: "040608",
    display: "San Carlos (David)",
  },
  {
    answer: "040609",
    display: "San Pablo Nuevo",
  },
  {
    answer: "040610",
    display: "San Pablo Viejo",
  },
  {
    answer: "040611",
    display: "David Este",
  },
  {
    answer: "040612",
    display: "David Sur",
  },
  {
    answer: "040701",
    display: "Dolega",
  },
  {
    answer: "040702",
    display: "Dos Ríos",
  },
  {
    answer: "040703",
    display: "Los Anastacios",
  },
  {
    answer: "040704",
    display: "Potrerillos",
  },
  {
    answer: "040705",
    display: "Potrerillos Abajo",
  },
  {
    answer: "040706",
    display: "Rovira",
  },
  {
    answer: "040707",
    display: "Tinajas",
  },
  {
    answer: "040708",
    display: "Los Algarrobos (Dolega)",
  },
  {
    answer: "040801",
    display: "Gualaca",
  },
  {
    answer: "040802",
    display: "Hornito",
  },
  {
    answer: "040803",
    display: "Los Ángeles (Gualaca)",
  },
  {
    answer: "040804",
    display: "Paja de Sombrero",
  },
  {
    answer: "040805",
    display: "Rincón",
  },
  {
    answer: "040901",
    display: "Remedios",
  },
  {
    answer: "040902",
    display: "El Nancito",
  },
  {
    answer: "040903",
    display: "El Porvenir",
  },
  {
    answer: "040904",
    display: "El Puerto",
  },
  {
    answer: "040905",
    display: "Santa Lucía",
  },
  {
    answer: "041002",
    display: "Breñón",
  },
  {
    answer: "041003",
    display: "Cañas Gordas",
  },
  {
    answer: "041004",
    display: "Monte Lirio",
  },
  {
    answer: "041005",
    display: "Plaza Caisán",
  },
  {
    answer: "041006",
    display: "Santa Cruz (Renacimiento)",
  },
  {
    answer: "041007",
    display: "Dominical",
  },
  {
    answer: "041008",
    display: "Santa Clara (Renacimiento)",
  },
  {
    answer: "041101",
    display: "Las Lajas (San Félix)",
  },
  {
    answer: "041102",
    display: "Juay o Las Mareas",
  },
  {
    answer: "041103",
    display: "Lajas Adentro",
  },
  {
    answer: "041104",
    display: "San Félix",
  },
  {
    answer: "041105",
    display: "Santa Cruz (San Félix)",
  },
  {
    answer: "041201",
    display: "Horconcitos",
  },
  {
    answer: "041202",
    display: "Boca Chica",
  },
  {
    answer: "041203",
    display: "Boca del Monte",
  },
  {
    answer: "041204",
    display: "San Juan (San Lorenzo)",
  },
  {
    answer: "041205",
    display: "San Lorenzo",
  },
  {
    answer: "041301",
    display: "Tolé",
  },
  {
    answer: "041302",
    display: "Bella Vista (Tolé)",
  },
  {
    answer: "041303",
    display: "Cerro Viejo",
  },
  {
    answer: "041304",
    display: "El Cristo (Tolé)",
  },
  {
    answer: "041305",
    display: "Justo Fidel Palacios",
  },
  {
    answer: "041306",
    display: "Lajas de Tolé",
  },
  {
    answer: "041307",
    display: "Potrero de Caña",
  },
  {
    answer: "041308",
    display: "Quebrada de Piedra",
  },
  {
    answer: "041309",
    display: "Veladero",
  },
  {
    answer: "041401",
    display: "Volcán",
  },
  {
    answer: "041402",
    display: "Cerro Punta",
  },
  {
    answer: "041403",
    display: "Cuesta de Piedra",
  },
  {
    answer: "041404",
    display: "Nueva California",
  },
  {
    answer: "041405",
    display: "Paso Ancho",
  },
  {
    answer: "050101",
    display: "La Palma (Chepigana)",
  },
  {
    answer: "050102",
    display: "Camogantí",
  },
  {
    answer: "050103",
    display: "Chepigana",
  },
  {
    answer: "050104",
    display: "Garachiné",
  },
  {
    answer: "050105",
    display: "Jaqué",
  },
  {
    answer: "050106",
    display: "Puerto Piña",
  },
  {
    answer: "050109",
    display: "Sambú",
  },
  {
    answer: "050110",
    display: "Setegantí",
  },
  {
    answer: "050111",
    display: "Taimatí",
  },
  {
    answer: "050112",
    display: "Tucutí",
  },
  {
    answer: "050201",
    display: "El Real de Santa María",
  },
  {
    answer: "050202",
    display: "Boca de Cupe",
  },
  {
    answer: "050203",
    display: "Paya",
  },
  {
    answer: "050204",
    display: "Pinogana",
  },
  {
    answer: "050205",
    display: "Púcuro",
  },
  {
    answer: "050206",
    display: "Yape",
  },
  {
    answer: "050207",
    display: "Yaviza",
  },
  {
    answer: "050208",
    display: "Metetí",
  },
  {
    answer: "050209",
    display: "Comarca Kuna de Wargandí",
  },
  {
    answer: "050300",
    display: "Santa Fe (Santa Fe, 050300)",
  },
  {
    answer: "050307",
    display: "Río Congo",
  },
  {
    answer: "050308",
    display: "Río Iglesias",
  },
  {
    answer: "050313",
    display: "Agua Fría",
  },
  {
    answer: "050314",
    display: "Cucunatí",
  },
  {
    answer: "050315",
    display: "Río Congo Arriba",
  },
  {
    answer: "050316",
    display: "Santa Fe (Santa Fe, 050316)",
  },
  {
    answer: "050317",
    display: "Zapallal",
  },
  {
    answer: "060101",
    display: "Chitré",
  },
  {
    answer: "060102",
    display: "La Arena (Chitré)",
  },
  {
    answer: "060103",
    display: "Monagrillo",
  },
  {
    answer: "060104",
    display: "Llano Bonito",
  },
  {
    answer: "060105",
    display: "San Juan Bautista",
  },
  {
    answer: "060201",
    display: "Las Minas (Las Minas)",
  },
  {
    answer: "060202",
    display: "Chepo (Las Minas)",
  },
  {
    answer: "060203",
    display: "Chumical",
  },
  {
    answer: "060204",
    display: "El Toro",
  },
  {
    answer: "060205",
    display: "Leones (Las Minas)",
  },
  {
    answer: "060206",
    display: "Quebrada del Rosario",
  },
  {
    answer: "060207",
    display: "Quebrada El Ciprián",
  },
  {
    answer: "060301",
    display: "Los Pozos",
  },
  {
    answer: "060302",
    display: "El Capurí",
  },
  {
    answer: "060303",
    display: "El Calabacito",
  },
  {
    answer: "060304",
    display: "El Cedro (Los Pozos)",
  },
  {
    answer: "060305",
    display: "La Arena (Los Pozos)",
  },
  {
    answer: "060306",
    display: "La Pitaloza",
  },
  {
    answer: "060307",
    display: "Los Cerritos",
  },
  {
    answer: "060308",
    display: "Los Cerros de Paja",
  },
  {
    answer: "060309",
    display: "Las Llanas",
  },
  {
    answer: "060401",
    display: "Ocú",
  },
  {
    answer: "060402",
    display: "Cerro Largo",
  },
  {
    answer: "060403",
    display: "Los Llanos",
  },
  {
    answer: "060404",
    display: "Llano Grande (Ocú)",
  },
  {
    answer: "060405",
    display: "Peña Chatas",
  },
  {
    answer: "060406",
    display: "El Tijera",
  },
  {
    answer: "060407",
    display: "Menchaca",
  },
  {
    answer: "060408",
    display: "Entradero del Castillo",
  },
  {
    answer: "060501",
    display: "Parita",
  },
  {
    answer: "060502",
    display: "Cabuya (Parita)",
  },
  {
    answer: "060503",
    display: "Los Castillos (Parita)",
  },
  {
    answer: "060504",
    display: "Llano de La Cruz",
  },
  {
    answer: "060505",
    display: "París",
  },
  {
    answer: "060506",
    display: "Portobelillo",
  },
  {
    answer: "060507",
    display: "Potuga",
  },
  {
    answer: "060601",
    display: "Pesé",
  },
  {
    answer: "060602",
    display: "Las Cabras",
  },
  {
    answer: "060603",
    display: "El Pájaro",
  },
  {
    answer: "060604",
    display: "El Barrero",
  },
  {
    answer: "060605",
    display: "El Pedregoso (Pesé)",
  },
  {
    answer: "060606",
    display: "El Ciruelo",
  },
  {
    answer: "060607",
    display: "Sabana Grande (Pesé)",
  },
  {
    answer: "060608",
    display: "Rincón Hondo",
  },
  {
    answer: "060701",
    display: "Santa María",
  },
  {
    answer: "060702",
    display: "Chupampa",
  },
  {
    answer: "060703",
    display: "El Rincón (Santa María)",
  },
  {
    answer: "060704",
    display: "El Limón",
  },
  {
    answer: "060705",
    display: "Los Canelos",
  },
  {
    answer: "070101",
    display: "Guararé",
  },
  {
    answer: "070102",
    display: "El Espinal",
  },
  {
    answer: "070103",
    display: "El Macano",
  },
  {
    answer: "070104",
    display: "Guararé Arriba",
  },
  {
    answer: "070105",
    display: "La Enea",
  },
  {
    answer: "070106",
    display: "La Pasera",
  },
  {
    answer: "070107",
    display: "Las Trancas",
  },
  {
    answer: "070108",
    display: "Llano Abajo",
  },
  {
    answer: "070109",
    display: "El Hato",
  },
  {
    answer: "070110",
    display: "Perales",
  },
  {
    answer: "070201",
    display: "Las Tablas (Las Tablas)",
  },
  {
    answer: "070202",
    display: "Bajo Corral",
  },
  {
    answer: "070203",
    display: "Bayano",
  },
  {
    answer: "070204",
    display: "El Carate",
  },
  {
    answer: "070205",
    display: "El Cocal",
  },
  {
    answer: "070206",
    display: "El Manantial",
  },
  {
    answer: "070207",
    display: "El Muñóz",
  },
  {
    answer: "070208",
    display: "El Pedregoso (Las Tablas)",
  },
  {
    answer: "070209",
    display: "La Laja",
  },
  {
    answer: "070210",
    display: "La Miel",
  },
  {
    answer: "070211",
    display: "La Palma (Las Tablas)",
  },
  {
    answer: "070212",
    display: "La Tiza",
  },
  {
    answer: "070213",
    display: "Las Palmitas",
  },
  {
    answer: "070214",
    display: "Las Tablas Abajo",
  },
  {
    answer: "070215",
    display: "Nuario",
  },
  {
    answer: "070216",
    display: "Palmira (Las Tablas)",
  },
  {
    answer: "070217",
    display: "Peña Blanca (Las Tablas)",
  },
  {
    answer: "070218",
    display: "Río Hondo",
  },
  {
    answer: "070219",
    display: "San José (Las Tablas)",
  },
  {
    answer: "070220",
    display: "San Miguel (Las Tablas)",
  },
  {
    answer: "070221",
    display: "Santo Domingo (Las Tablas)",
  },
  {
    answer: "070222",
    display: "Sesteadero",
  },
  {
    answer: "070223",
    display: "Valle Rico",
  },
  {
    answer: "070224",
    display: "Vallerriquito",
  },
  {
    answer: "070301",
    display: "La Villa de Los Santos",
  },
  {
    answer: "070302",
    display: "El Guásimo (Los Santos)",
  },
  {
    answer: "070303",
    display: "La Colorada (Los Santos)",
  },
  {
    answer: "070304",
    display: "La Espigadilla",
  },
  {
    answer: "070305",
    display: "Las Cruces (Los Santos)",
  },
  {
    answer: "070306",
    display: "Las Guabas",
  },
  {
    answer: "070307",
    display: "Los Ángeles (Los Santos)",
  },
  {
    answer: "070308",
    display: "Los Olivos",
  },
  {
    answer: "070309",
    display: "Llano Largo",
  },
  {
    answer: "070310",
    display: "Sabana Grande (Los Santos)",
  },
  {
    answer: "070311",
    display: "Santa Ana (Los Santos)",
  },
  {
    answer: "070312",
    display: "Tres Quebradas",
  },
  {
    answer: "070313",
    display: "Agua Buena",
  },
  {
    answer: "070314",
    display: "Villa Lourdes",
  },
  {
    answer: "070315",
    display: "El Ejido",
  },
  {
    answer: "070401",
    display: "Macaracas",
  },
  {
    answer: "070402",
    display: "Bahía Honda (Macaracas)",
  },
  {
    answer: "070403",
    display: "Bajos de Güera",
  },
  {
    answer: "070404",
    display: "Corozal (Macaracas)",
  },
  {
    answer: "070405",
    display: "Chupa",
  },
  {
    answer: "070406",
    display: "El Cedro (Macaracas)",
  },
  {
    answer: "070407",
    display: "Espino Amarillo",
  },
  {
    answer: "070408",
    display: "La Mesa (Macaracas)",
  },
  {
    answer: "070409",
    display: "Las Palmas (Macaracas)",
  },
  {
    answer: "070410",
    display: "Llano de Piedra",
  },
  {
    answer: "070411",
    display: "Mogollón",
  },
  {
    answer: "070501",
    display: "Pedasí",
  },
  {
    answer: "070502",
    display: "Los Asientos",
  },
  {
    answer: "070503",
    display: "Mariabé",
  },
  {
    answer: "070504",
    display: "Purio",
  },
  {
    answer: "070505",
    display: "Oria Arriba",
  },
  {
    answer: "070601",
    display: "Pocrí (Pocrí)",
  },
  {
    answer: "070602",
    display: "El Cañafístulo",
  },
  {
    answer: "070603",
    display: "Lajamina",
  },
  {
    answer: "070604",
    display: "Paraíso (Pocrí)",
  },
  {
    answer: "070605",
    display: "Paritilla",
  },
  {
    answer: "070701",
    display: "Tonosí",
  },
  {
    answer: "070702",
    display: "Altos de Güera",
  },
  {
    answer: "070703",
    display: "Cañas",
  },
  {
    answer: "070704",
    display: "El Bebedero",
  },
  {
    answer: "070705",
    display: "El Cacao (Tonosí)",
  },
  {
    answer: "070706",
    display: "El Cortezo",
  },
  {
    answer: "070707",
    display: "Flores",
  },
  {
    answer: "070708",
    display: "Guánico",
  },
  {
    answer: "070709",
    display: "La Tronosa",
  },
  {
    answer: "070710",
    display: "Cambutal",
  },
  {
    answer: "070711",
    display: "Isla de Cañas",
  },
  {
    answer: "080201",
    display: "San Miguel (Balboa)",
  },
  {
    answer: "080202",
    display: "La Ensenada",
  },
  {
    answer: "080203",
    display: "La Esmeralda",
  },
  {
    answer: "080204",
    display: "La Guinea",
  },
  {
    answer: "080205",
    display: "Pedro González",
  },
  {
    answer: "080206",
    display: "Saboga",
  },
  {
    answer: "080501",
    display: "Chepo (Chepo)",
  },
  {
    answer: "080502",
    display: "Cañita",
  },
  {
    answer: "080503",
    display: "Chepillo",
  },
  {
    answer: "080504",
    display: "El Llano",
  },
  {
    answer: "080505",
    display: "Las Margaritas",
  },
  {
    answer: "080506",
    display: "Santa Cruz de Chinina",
  },
  {
    answer: "080507",
    display: "Comarca Kuna de Madungandi",
  },
  {
    answer: "080508",
    display: "Tortí",
  },
  {
    answer: "080601",
    display: "Chimán",
  },
  {
    answer: "080602",
    display: "Brujas",
  },
  {
    answer: "080603",
    display: "Gonzalo Vásquez",
  },
  {
    answer: "080604",
    display: "Pásiga",
  },
  {
    answer: "080605",
    display: "Unión Santeña",
  },
  {
    answer: "080801",
    display: "San Felipe",
  },
  {
    answer: "080802",
    display: "El Chorrillo",
  },
  {
    answer: "080803",
    display: "Santa Ana (Panamá)",
  },
  {
    answer: "080804",
    display: "Calidonia o La Exposición",
  },
  {
    answer: "080805",
    display: "Curundú",
  },
  {
    answer: "080806",
    display: "Betania",
  },
  {
    answer: "080807",
    display: "Bella Vista (Panamá)",
  },
  {
    answer: "080808",
    display: "Pueblo Nuevo",
  },
  {
    answer: "080809",
    display: "San Francisco (Panamá)",
  },
  {
    answer: "080810",
    display: "Parque Lefevre",
  },
  {
    answer: "080811",
    display: "Río Abajo",
  },
  {
    answer: "080812",
    display: "Juan Díaz (Panamá)",
  },
  {
    answer: "080813",
    display: "Pedregal (Panamá)",
  },
  {
    answer: "080814",
    display: "Ancón",
  },
  {
    answer: "080815",
    display: "Chilibre",
  },
  {
    answer: "080816",
    display: "Las Cumbres",
  },
  {
    answer: "080817",
    display: "Pacora",
  },
  {
    answer: "080818",
    display: "San Martín",
  },
  {
    answer: "080819",
    display: "Tocumen",
  },
  {
    answer: "080820",
    display: "Las Mañanitas",
  },
  {
    answer: "080821",
    display: "24 de Diciembre",
  },
  {
    answer: "080822",
    display: "Alcalde Díaz",
  },
  {
    answer: "080823",
    display: "Ernesto Córdoba Campos",
  },
  {
    answer: "080824",
    display: "Caimitillo",
  },
  {
    answer: "080825",
    display: "Las Garzas",
  },
  {
    answer: "080826",
    display: "Don Bosco",
  },
  {
    answer: "081001",
    display: "Amelia Denis de Icaza",
  },
  {
    answer: "081002",
    display: "Belisario Porras",
  },
  {
    answer: "081003",
    display: "José Domingo Espinar",
  },
  {
    answer: "081004",
    display: "Mateo Iturralde",
  },
  {
    answer: "081005",
    display: "Victoriano Lorenzo (San Miguelito)",
  },
  {
    answer: "081006",
    display: "Arnulfo Arias",
  },
  {
    answer: "081007",
    display: "Belisario Frías",
  },
  {
    answer: "081008",
    display: "Omar Torrijos",
  },
  {
    answer: "081009",
    display: "Rufina Alfaro",
  },
  {
    answer: "081101",
    display: "Taboga",
  },
  {
    answer: "081102",
    display: "Otoque Occidente",
  },
  {
    answer: "081103",
    display: "Otoque Oriente",
  },
  {
    answer: "090101",
    display: "Atalaya",
  },
  {
    answer: "090102",
    display: "El Barrito",
  },
  {
    answer: "090103",
    display: "La Montañuela",
  },
  {
    answer: "090104",
    display: "La Carrillo",
  },
  {
    answer: "090105",
    display: "San Antonio",
  },
  {
    answer: "090201",
    display: "Calobre",
  },
  {
    answer: "090202",
    display: "Barnizal",
  },
  {
    answer: "090203",
    display: "Chitra",
  },
  {
    answer: "090204",
    display: "El Cocla",
  },
  {
    answer: "090205",
    display: "El Potrero (Calobre)",
  },
  {
    answer: "090206",
    display: "La Laguna (Calobre)",
  },
  {
    answer: "090207",
    display: "La Raya de Calobre",
  },
  {
    answer: "090208",
    display: "La Tetilla",
  },
  {
    answer: "090209",
    display: "La Yeguada",
  },
  {
    answer: "090210",
    display: "Las Guías",
  },
  {
    answer: "090211",
    display: "Monjarás",
  },
  {
    answer: "090212",
    display: "San José (Calobre)",
  },
  {
    answer: "090301",
    display: "Cañazas",
  },
  {
    answer: "090302",
    display: "Cerro Plata",
  },
  {
    answer: "090303",
    display: "El Picador",
  },
  {
    answer: "090304",
    display: "Los Valles",
  },
  {
    answer: "090305",
    display: "San José (Cañazas)",
  },
  {
    answer: "090306",
    display: "San Marcelo",
  },
  {
    answer: "090307",
    display: "El Aromillo",
  },
  {
    answer: "090308",
    display: "Las Cruces (Cañazas)",
  },
  {
    answer: "090401",
    display: "La Mesa (La Mesa)",
  },
  {
    answer: "090402",
    display: "Bisvalles",
  },
  {
    answer: "090403",
    display: "Boró",
  },
  {
    answer: "090404",
    display: "Llano Grande (La Mesa)",
  },
  {
    answer: "090405",
    display: "San Bartolo",
  },
  {
    answer: "090406",
    display: "Los Milagros",
  },
  {
    answer: "090407",
    display: "El Higo (La Mesa)",
  },
  {
    answer: "090501",
    display: "Las Palmas (Las Palmas)",
  },
  {
    answer: "090502",
    display: "Cerro de Casa",
  },
  {
    answer: "090503",
    display: "Corozal (Las Palmas)",
  },
  {
    answer: "090504",
    display: "El María",
  },
  {
    answer: "090505",
    display: "El Prado",
  },
  {
    answer: "090506",
    display: "El Rincón (Las Palmas)",
  },
  {
    answer: "090507",
    display: "Lolá",
  },
  {
    answer: "090508",
    display: "Pixvae",
  },
  {
    answer: "090509",
    display: "Puerto Vidal",
  },
  {
    answer: "090510",
    display: "San Martín de Porres (Las Palmas)",
  },
  {
    answer: "090511",
    display: "Viguí",
  },
  {
    answer: "090512",
    display: "Zapotillo",
  },
  {
    answer: "090513",
    display: "Manuel E. Amador Terrero",
  },
  {
    answer: "090601",
    display: "Montijo",
  },
  {
    answer: "090602",
    display: "Gobernadora",
  },
  {
    answer: "090603",
    display: "La Garceana",
  },
  {
    answer: "090604",
    display: "Leones (Montijo)",
  },
  {
    answer: "090605",
    display: "Pilón",
  },
  {
    answer: "090606",
    display: "Cébaco",
  },
  {
    answer: "090607",
    display: "Costa Hermosa",
  },
  {
    answer: "090608",
    display: "Unión del Norte",
  },
  {
    answer: "090701",
    display: "Río de Jesús",
  },
  {
    answer: "090702",
    display: "Las Huacas (Río de Jesús)",
  },
  {
    answer: "090703",
    display: "Los Castillos (Río de Jesús)",
  },
  {
    answer: "090704",
    display: "Utirá",
  },
  {
    answer: "090705",
    display: "Catorce de Noviembre",
  },
  {
    answer: "090801",
    display: "San Francisco (San Francisco)",
  },
  {
    answer: "090802",
    display: "Corral Falso",
  },
  {
    answer: "090803",
    display: "Los Hatillos",
  },
  {
    answer: "090804",
    display: "Remance",
  },
  {
    answer: "090805",
    display: "San Juan (San Francisco)",
  },
  {
    answer: "090806",
    display: "San José (San Francisco)",
  },
  {
    answer: "090901",
    display: "Santa Fe (Santa Fe)",
  },
  {
    answer: "090902",
    display: "Calovébora",
  },
  {
    answer: "090903",
    display: "El Alto",
  },
  {
    answer: "090904",
    display: "El Cuay",
  },
  {
    answer: "090905",
    display: "El Pantano",
  },
  {
    answer: "090906",
    display: "Gatú o Gatucito",
  },
  {
    answer: "090907",
    display: "Río Luis",
  },
  {
    answer: "090908",
    display: "Rubén Cantú",
  },
  {
    answer: "091001",
    display: "Santiago",
  },
  {
    answer: "091002",
    display: "La Colorada (Santiago)",
  },
  {
    answer: "091003",
    display: "La Peña",
  },
  {
    answer: "091004",
    display: "La Raya de Santa María",
  },
  {
    answer: "091005",
    display: "Ponuga",
  },
  {
    answer: "091006",
    display: "San Pedro del Espino",
  },
  {
    answer: "091007",
    display: "Canto del Llano",
  },
  {
    answer: "091008",
    display: "Los Algarrobos (Santiago)",
  },
  {
    answer: "091009",
    display: "Carlos Santana Ávila",
  },
  {
    answer: "091010",
    display: "Edwin Fábrega",
  },
  {
    answer: "091011",
    display: "San Martín de Porres (Santiago)",
  },
  {
    answer: "091012",
    display: "Urracá",
  },
  {
    answer: "091013",
    display: "Rodrigo Luque",
  },
  {
    answer: "091014",
    display: "Nuevo Santiago",
  },
  {
    answer: "091015",
    display: "Santiago Este",
  },
  {
    answer: "091016",
    display: "Santiago Sur",
  },
  {
    answer: "091101",
    display: "Soná",
  },
  {
    answer: "091102",
    display: "Bahía Honda (Soná)",
  },
  {
    answer: "091103",
    display: "Calidonia",
  },
  {
    answer: "091104",
    display: "Cativé",
  },
  {
    answer: "091105",
    display: "El Marañón",
  },
  {
    answer: "091106",
    display: "Guarumal (Soná)",
  },
  {
    answer: "091107",
    display: "La Soledad",
  },
  {
    answer: "091108",
    display: "Quebrada de Oro",
  },
  {
    answer: "091109",
    display: "Río Grande (Soná)",
  },
  {
    answer: "091110",
    display: "Rodeo Viejo",
  },
  {
    answer: "091111",
    display: "Hicaco",
  },
  {
    answer: "091112",
    display: "La Trinchera",
  },
  {
    answer: "091201",
    display: "Llano de Catival o Mariato (Cabecera)",
  },
  {
    answer: "091202",
    display: "Arenas",
  },
  {
    answer: "091203",
    display: "El Cacao (Mariato)",
  },
  {
    answer: "091204",
    display: "Quebro",
  },
  {
    answer: "091205",
    display: "Tebario",
  },
  {
    answer: "100001",
    display: "Narganá",
  },
  {
    answer: "100002",
    display: "Ailigandí",
  },
  {
    answer: "100003",
    display: "Puerto Obaldía",
  },
  {
    answer: "100004",
    display: "Tubualá",
  },
  {
    answer: "110101",
    display: "Cirilo Guaynora",
  },
  {
    answer: "110102",
    display: "Lajas Blancas",
  },
  {
    answer: "110103",
    display: "Manuel Ortega",
  },
  {
    answer: "110201",
    display: "Río Sábalo",
  },
  {
    answer: "110202",
    display: "Jingurudó",
  },
  {
    answer: "120101",
    display: "Soloy",
  },
  {
    answer: "120102",
    display: "Boca de Balsa",
  },
  {
    answer: "120103",
    display: "Camarón Arriba",
  },
  {
    answer: "120104",
    display: "Cerro Banco",
  },
  {
    answer: "120105",
    display: "Cerro de Patena",
  },
  {
    answer: "120106",
    display: "Emplanada de Chorcha",
  },
  {
    answer: "120107",
    display: "Nämnoni",
  },
  {
    answer: "120108",
    display: "Niba",
  },
  {
    answer: "120201",
    display: "Hato Pilón",
  },
  {
    answer: "120202",
    display: "Cascabel",
  },
  {
    answer: "120203",
    display: "Hato Corotú",
  },
  {
    answer: "120204",
    display: "Hato Culantro",
  },
  {
    answer: "120205",
    display: "Hato Jobo",
  },
  {
    answer: "120206",
    display: "Hato Julí",
  },
  {
    answer: "120207",
    display: "Quebrada de Loro",
  },
  {
    answer: "120208",
    display: "Salto Dupí",
  },
  {
    answer: "120301",
    display: "Chichica",
  },
  {
    answer: "120302",
    display: "Alto Caballero",
  },
  {
    answer: "120303",
    display: "Bakama",
  },
  {
    answer: "120304",
    display: "Cerro Caña",
  },
  {
    answer: "120305",
    display: "Cerro Puerco",
  },
  {
    answer: "120306",
    display: "Krüa",
  },
  {
    answer: "120307",
    display: "Maraca",
  },
  {
    answer: "120308",
    display: "Nibra",
  },
  {
    answer: "120309",
    display: "Peña Blanca (Müna)",
  },
  {
    answer: "120310",
    display: "Roka o Rokari",
  },
  {
    answer: "120311",
    display: "Sitio Prado",
  },
  {
    answer: "120312",
    display: "Ümani",
  },
  {
    answer: "120313",
    display: "Dikeri",
  },
  {
    answer: "120314",
    display: "Diko",
  },
  {
    answer: "120315",
    display: "Kikari",
  },
  {
    answer: "120316",
    display: "Mreeni",
  },
  {
    answer: "120401",
    display: "Cerro Iglesias",
  },
  {
    answer: "120402",
    display: "Hato Chamí",
  },
  {
    answer: "120403",
    display: "Jädeberi",
  },
  {
    answer: "120404",
    display: "Lajero",
  },
  {
    answer: "120405",
    display: "Susama",
  },
  {
    answer: "120501",
    display: "Buenos Aires (Ñürüm)",
  },
  {
    answer: "120502",
    display: "Agua de Salud",
  },
  {
    answer: "120503",
    display: "Alto de Jesús",
  },
  {
    answer: "120504",
    display: "Cerro Pelado",
  },
  {
    answer: "120505",
    display: "El Bale",
  },
  {
    answer: "120506",
    display: "El Paredón",
  },
  {
    answer: "120507",
    display: "El Piro",
  },
  {
    answer: "120508",
    display: "Guayabito (Ñürüm)",
  },
  {
    answer: "120509",
    display: "Güibale",
  },
  {
    answer: "120510",
    display: "El Peñón",
  },
  {
    answer: "120511",
    display: "El Piro N°2 (Muakwata Kubu)",
  },
  {
    answer: "120601",
    display: "Bisira",
  },
  {
    answer: "120604",
    display: "Gworoni",
  },
  {
    answer: "120605",
    display: "Kankintú",
  },
  {
    answer: "120606",
    display: "Mününi",
  },
  {
    answer: "120607",
    display: "Piedra Roja",
  },
  {
    answer: "120610",
    display: "Calante",
  },
  {
    answer: "120611",
    display: "Tolote",
  },
  {
    answer: "120701",
    display: "Kusapín",
  },
  {
    answer: "120702",
    display: "Bahía Azul",
  },
  {
    answer: "120705",
    display: "Río Chiriquí",
  },
  {
    answer: "120706",
    display: "Tobobe",
  },
  {
    answer: "120708",
    display: "Cañaveral (Kusapín)",
  },
  {
    answer: "120801",
    display: "Samboa",
  },
  {
    answer: "120802",
    display: "Büri",
  },
  {
    answer: "120803",
    display: "Gwaribiara (Guariviara)",
  },
  {
    answer: "120804",
    display: "Man Creek",
  },
  {
    answer: "120805",
    display: "Tu Gwai (Tuwai)",
  },
  {
    answer: "120901",
    display: "Santa Catalina o Calovébora o Bledeshia",
  },
  {
    answer: "120902",
    display: "Alto Bilingüe o Gdogüeshia",
  },
  {
    answer: "120903",
    display: "Loma Yuca o Ijuicho",
  },
  {
    answer: "120904",
    display: "San Pedrito o Jiküi",
  },
  {
    answer: "120905",
    display: "Valle Bonito o Dogata",
  },
  {
    answer: "130101",
    display: "Arraiján",
  },
  {
    answer: "130102",
    display: "Juan Demóstenes Arosemena",
  },
  {
    answer: "130103",
    display: "Nuevo Emperador",
  },
  {
    answer: "130104",
    display: "Santa Clara (Arraiján)",
  },
  {
    answer: "130105",
    display: "Veracruz",
  },
  {
    answer: "130106",
    display: "Vista Alegre",
  },
  {
    answer: "130107",
    display: "Burunga",
  },
  {
    answer: "130108",
    display: "Cerro Silvestre",
  },
  {
    answer: "130109",
    display: "Vacamonte",
  },
  {
    answer: "130301",
    display: "Capira",
  },
  {
    answer: "130302",
    display: "Caimito",
  },
  {
    answer: "130303",
    display: "Campana",
  },
  {
    answer: "130304",
    display: "Cermeño",
  },
  {
    answer: "130305",
    display: "Cirí de Los Sotos",
  },
  {
    answer: "130306",
    display: "Cirí Grande",
  },
  {
    answer: "130307",
    display: "El Cacao (Capira)",
  },
  {
    answer: "130308",
    display: "La Trinidad",
  },
  {
    answer: "130309",
    display: "Las Ollas Arriba",
  },
  {
    answer: "130310",
    display: "Lídice",
  },
  {
    answer: "130311",
    display: "Villa Carmen",
  },
  {
    answer: "130312",
    display: "Villa Rosario",
  },
  {
    answer: "130313",
    display: "Santa Rosa (Capira)",
  },
  {
    answer: "130401",
    display: "Chame",
  },
  {
    answer: "130402",
    display: "Bejuco",
  },
  {
    answer: "130403",
    display: "Buenos Aires (Chame)",
  },
  {
    answer: "130404",
    display: "Cabuya (Chame)",
  },
  {
    answer: "130405",
    display: "Chicá",
  },
  {
    answer: "130406",
    display: "El Líbano",
  },
  {
    answer: "130407",
    display: "Las Lajas (Chame)",
  },
  {
    answer: "130408",
    display: "Nueva Gorgona",
  },
  {
    answer: "130409",
    display: "Punta Chame",
  },
  {
    answer: "130410",
    display: "Sajalices",
  },
  {
    answer: "130411",
    display: "Sorá",
  },
  {
    answer: "130701",
    display: "Barrio Balboa",
  },
  {
    answer: "130702",
    display: "Barrio Colón",
  },
  {
    answer: "130703",
    display: "Amador",
  },
  {
    answer: "130704",
    display: "Arosemena",
  },
  {
    answer: "130705",
    display: "El Arado",
  },
  {
    answer: "130706",
    display: "El Coco (La Chorrera)",
  },
  {
    answer: "130707",
    display: "Feuillet",
  },
  {
    answer: "130708",
    display: "Guadalupe",
  },
  {
    answer: "130709",
    display: "Herrera",
  },
  {
    answer: "130710",
    display: "Hurtado",
  },
  {
    answer: "130711",
    display: "Iturralde",
  },
  {
    answer: "130712",
    display: "La Represa",
  },
  {
    answer: "130713",
    display: "Los Díaz",
  },
  {
    answer: "130714",
    display: "Mendoza",
  },
  {
    answer: "130715",
    display: "Obaldía",
  },
  {
    answer: "130716",
    display: "Playa Leona",
  },
  {
    answer: "130717",
    display: "Puerto Caimito",
  },
  {
    answer: "130718",
    display: "Santa Rita (La Chorrera)",
  },
  {
    answer: "130901",
    display: "San Carlos (San Carlos)",
  },
  {
    answer: "130902",
    display: "El Espino",
  },
  {
    answer: "130903",
    display: "El Higo (San Carlos)",
  },
  {
    answer: "130904",
    display: "Guayabito (San Carlos)",
  },
  {
    answer: "130905",
    display: "La Ermita",
  },
  {
    answer: "130906",
    display: "La Laguna (San Carlos)",
  },
  {
    answer: "130907",
    display: "Las Uvas",
  },
  {
    answer: "130908",
    display: "Los Llanitos",
  },
  {
    answer: "130909",
    display: "San José (San Carlos)",
  },
];

/**
 * Quiz configuration for Panama's corregimientos.
 */
export const panamaCorregimientosQuiz: FeatureQuiz = {
  id: "panama-corregimientos",
  name: "Corregimientos",
  description: `Learn all ${PANAMA_CORREGIMIENTO_QUESTIONS.length} corregimientos of Panama, with filters that let you practice corregimientos by district, province, or comarca.`,

  kind: "feature",
  mapId: "panama-corregimientos",

  answerProperty: "id",
  answerType: "single",

  baseMapLayers: {
    subdivisionLabels: false,
  },

  grouping: {
    properties: [
      {
        property: "districtId",
        label: "District",
        valueType: "string",
        valueLabels: PANAMA_DISTRICT_NAMES_BY_ID,
      },
      {
        property: "provinceId",
        label: "Province / Comarca",
        valueType: "string",
        valueLabels: PANAMA_PROVINCE_COMARCA_NAMES_BY_ID,
      },
    ],
  },

  questions: PANAMA_CORREGIMIENTO_QUESTIONS,
};
