/**
 * AUTO-GENERATED FILE.
 *
 * Generated by:
 *
 *   scripts/countries/panama/generate/admin-quizzes.ts
 *
 * Do not edit the district dictionary manually. Update the processed Panama
 * district GeoJSON or generator and rerun the script instead.
 */

import type { FeatureQuiz } from "@/types/quiz";

import { PANAMA_PROVINCE_COMARCA_NAMES_BY_ID } from "./provincesComarcasQuiz";

/**
 * Panama's quiz-eligible districts by stable administrative ID.
 */
export const PANAMA_DISTRICT_NAMES_BY_ID = {
  "0101": "Bocas del Toro",
  "0102": "Changuinola",
  "0103": "Chiriquí Grande",
  "0104": "Almirante",
  "0201": "Aguadulce",
  "0202": "Antón",
  "0203": "La Pintada",
  "0204": "Natá",
  "0205": "Olá",
  "0206": "Penonomé",
  "0301": "Colón",
  "0302": "Chagres",
  "0303": "Donoso",
  "0304": "Portobelo",
  "0305": "Santa Isabel",
  "0306": "Omar Torrijos Herrera",
  "0401": "Alanje",
  "0402": "Barú",
  "0403": "Boquerón",
  "0404": "Boquete",
  "0405": "Bugaba",
  "0406": "David",
  "0407": "Dolega",
  "0408": "Gualaca",
  "0409": "Remedios",
  "0410": "Renacimiento",
  "0411": "San Félix",
  "0412": "San Lorenzo",
  "0413": "Tolé",
  "0414": "Tierras Altas",
  "0501": "Chepigana",
  "0502": "Pinogana",
  "0503": "Santa Fe",
  "0601": "Chitré",
  "0602": "Las Minas",
  "0603": "Los Pozos",
  "0604": "Ocú",
  "0605": "Parita",
  "0606": "Pesé",
  "0607": "Santa María",
  "0701": "Guararé",
  "0702": "Las Tablas",
  "0703": "Los Santos",
  "0704": "Macaracas",
  "0705": "Pedasí",
  "0706": "Pocrí",
  "0707": "Tonosí",
  "0802": "Balboa",
  "0805": "Chepo",
  "0806": "Chimán",
  "0808": "Panamá",
  "0810": "San Miguelito",
  "0811": "Taboga",
  "0901": "Atalaya",
  "0902": "Calobre",
  "0903": "Cañazas",
  "0904": "La Mesa",
  "0905": "Las Palmas",
  "0906": "Montijo",
  "0907": "Río de Jesús",
  "0908": "San Francisco",
  "0909": "Santa Fe",
  "0910": "Santiago",
  "0911": "Soná",
  "0912": "Mariato",
  "1000": "Kuna Yala",
  "1101": "Cémaco (Área 1)",
  "1102": "Sambú (Área 2)",
  "1201": "Besiko",
  "1202": "Mironó",
  "1203": "Müna",
  "1204": "Nole Duima",
  "1205": "Ñürün",
  "1206": "Kankintú",
  "1207": "Kusapín",
  "1208": "Jirondai",
  "1209": "Santa Catalina o Calovébora",
  "1301": "Arraiján",
  "1303": "Capira",
  "1304": "Chame",
  "1307": "La Chorrera",
  "1309": "San Carlos",
} as const;

/**
 * Questions for Panama's Districts quiz.
 */
const PANAMA_DISTRICT_QUESTIONS = Object.entries(
  PANAMA_DISTRICT_NAMES_BY_ID,
).map(([answer, display]) => ({
  answer,
  display,
}));

/**
 * Quiz configuration for Panama's districts.
 */
export const panamaDistrictsQuiz: FeatureQuiz = {
  id: "panama-districts",
  name: "Districts",
  description: `Learn all ${PANAMA_DISTRICT_QUESTIONS.length} districts of Panama, with filters that let you practice districts by province or comarca.`,

  kind: "feature",
  mapId: "panama-districts",

  answerProperty: "id",
  answerType: "single",

  baseMapLayers: {
    subdivisionLabels: false,
  },

  grouping: {
    properties: [
      {
        property: "provinceId",
        label: "Province / Comarca",
        valueType: "string",
        valueLabels: PANAMA_PROVINCE_COMARCA_NAMES_BY_ID,
      },
    ],
  },

  questions: PANAMA_DISTRICT_QUESTIONS,
};
