"""
Generate Botswana administrative quiz question data for GeoPedia.

The generated TypeScript contains complete FeatureQuizQuestion arrays for
Botswana's district and sub-district quizzes. Questions are generated from
the processed runtime GeoJSON so their answers and display names remain
synchronized with the map features.

Inputs:
    public/data/countries/botswana/geojson/districts.geojson
    public/data/countries/botswana/geojson/sub-districts.geojson

Output:
    src/quiz/quizzes/countries/africa/botswana/data/admin.ts

Run:
    python scripts/countries/botswana/generate/admin-quiz-data.py
"""

import json
from pathlib import Path


PUBLIC_ROOT = Path(
    "public/data/countries/botswana/geojson"
)

DISTRICTS_PATH = PUBLIC_ROOT / "districts.geojson"
SUB_DISTRICTS_PATH = PUBLIC_ROOT / "sub-districts.geojson"

OUTPUT_PATH = Path(
    "src/quiz/quizzes/countries/africa/botswana/data/admin.ts"
)

EXPECTED_DISTRICT_COUNT = 16
EXPECTED_SUB_DISTRICT_COUNT = 25


def load_features(path: Path) -> list[dict]:
    """Load the feature array from a processed GeoJSON file."""

    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if data.get("type") != "FeatureCollection":
        raise ValueError(
            f"{path} is not a GeoJSON FeatureCollection."
        )

    features = data.get("features")

    if not isinstance(features, list):
        raise ValueError(
            f"{path} does not contain a valid features array."
        )

    return features


def build_questions(
    features: list[dict],
    id_property: str,
    name_property: str,
) -> list[dict]:
    """Build sorted quiz questions from canonical feature properties."""

    questions = []
    seen_answers = set()

    for feature in features:
        properties = feature.get("properties") or {}

        answer = properties.get(id_property)
        display = properties.get(name_property)

        if not isinstance(answer, str) or not answer:
            raise ValueError(
                f"Invalid {id_property}: {answer!r}"
            )

        if not isinstance(display, str) or not display:
            raise ValueError(
                f"Invalid {name_property}: {display!r}"
            )

        if answer in seen_answers:
            raise ValueError(
                f"Duplicate quiz answer: {answer}"
            )

        seen_answers.add(answer)

        questions.append(
            {
                "answer": answer,
                "display": display,
            }
        )

    questions.sort(
        key=lambda question: question["display"]
    )

    return questions


def format_questions(
    name: str,
    questions: list[dict],
) -> str:
    """Format a FeatureQuizQuestion array as TypeScript."""

    lines = [
        f"export const {name}: FeatureQuizQuestion[] = ["
    ]

    for question in questions:
        answer = json.dumps(
            question["answer"],
            ensure_ascii=False,
        )
        display = json.dumps(
            question["display"],
            ensure_ascii=False,
        )

        lines.append(
            f"  {{ answer: {answer}, display: {display} }},"
        )

    lines.append("];")

    return "\n".join(lines)


def main() -> None:
    """Generate Botswana's administrative quiz question arrays."""

    print("Generating Botswana administrative quiz data...")
    print()

    district_features = load_features(
        DISTRICTS_PATH
    )
    sub_district_features = load_features(
        SUB_DISTRICTS_PATH
    )

    if len(district_features) != EXPECTED_DISTRICT_COUNT:
        raise ValueError(
            "Unexpected district count: "
            f"expected {EXPECTED_DISTRICT_COUNT}, "
            f"found {len(district_features)}."
        )

    if len(sub_district_features) != EXPECTED_SUB_DISTRICT_COUNT:
        raise ValueError(
            "Unexpected sub-district count: "
            f"expected {EXPECTED_SUB_DISTRICT_COUNT}, "
            f"found {len(sub_district_features)}."
        )

    district_questions = build_questions(
        district_features,
        "district_id",
        "district",
    )

    sub_district_questions = build_questions(
        sub_district_features,
        "sub_district_id",
        "sub_district",
    )

    sections = [
        (
            "/**\n"
            " * Generated quiz question data for Botswana's administrative "
            "divisions.\n"
            " *\n"
            " * Do not edit this file manually. Regenerate it with:\n"
            " * python scripts/countries/botswana/generate/"
            "admin-quiz-data.py\n"
            " */"
        ),
        (
            'import type { FeatureQuizQuestion } '
            'from "@/types/quiz";'
        ),
        format_questions(
            "BOTSWANA_DISTRICTS_QUIZ_QUESTIONS",
            district_questions,
        ),
        format_questions(
            "BOTSWANA_SUB_DISTRICTS_QUIZ_QUESTIONS",
            sub_district_questions,
        ),
    ]

    output = "\n\n".join(sections) + "\n"

    OUTPUT_PATH.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    OUTPUT_PATH.write_text(
        output,
        encoding="utf-8",
    )

    print(
        f"Districts       {len(district_questions):>3} questions"
    )
    print(
        f"Sub-districts   {len(sub_district_questions):>3} questions"
    )
    print()
    print(f"Output: {OUTPUT_PATH}")
    print()
    print("Botswana administrative quiz data generated.")


if __name__ == "__main__":
    main()